### ISSUE TITLE
Support for Quantum Device

### ISSUE THREAD

**Issue by snownz** [m4rs-mt/ILGPU#1]
How about to support a quantum devices for parallel programing, using : https://github.com/Microsoft/Quantum/

**Comment by m4rs-mt** [comment]
Writing programs for a quantum device requires an adaption of the underlying algorithms.
Furthermore, it requires a different "kind of thinking".
We might want to head into this direction in the far future. However, supporting quantum devices is currently not the main focus of the ILGPU project.
