### ISSUE TITLE
Won;t compile on VS2017

### ISSUE THREAD

**Issue by SoftSharper** [m4rs-mt/ILGPU#11]
Hi, thank you for making this fabulous project. I downloaded master branch and v.0.3.0 tagged code. When I tried to compile it I've got many errors related to class visibility and using non-nullable value type in templates. 

1>------ Build started: Project: ILGPU, Configuration: Debug Any CPU ------
1>ArrayViewExtensions.cs(242,38,242,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(242,38,242,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(254,38,254,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(254,38,254,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(264,38,264,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(264,38,264,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(308,29,308,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(308,29,308,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(152,38,152,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(152,38,152,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(173,38,173,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(173,38,173,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(163,38,163,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(163,38,163,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>ArrayViewExtensions.cs(222,29,222,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Grid.cs(70,48,70,60): error CS0246: The type or namespace name 'GroupedIndex' could not be found (are you missing a using directive or an assembly reference?)
1>ArrayViewExtensions.cs(222,29,222,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Grid.cs(80,49,80,62): error CS0246: The type or namespace name 'GroupedIndex2' could not be found (are you missing a using directive or an assembly reference?)
1>Grid.cs(70,48,70,60): error CS0246: The type or namespace name 'GroupedIndex' could not be found (are you missing a using directive or an assembly reference?)
1>Grid.cs(90,49,90,62): error CS0246: The type or namespace name 'GroupedIndex3' could not be found (are you missing a using directive or an assembly reference?)
1>Grid.cs(80,49,80,62): error CS0246: The type or namespace name 'GroupedIndex2' could not be found (are you missing a using directive or an assembly reference?)
1>Runtime\Accelerator.cs(267,32,267,40): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer<T>' is less accessible than method 'Accelerator.Allocate<T>(int)'
1>Runtime\Accelerator.cs(279,34,279,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer2D<T>' is less accessible than method 'Accelerator.Allocate<T>(Index2)'
1>Grid.cs(90,49,90,62): error CS0246: The type or namespace name 'GroupedIndex3' could not be found (are you missing a using directive or an assembly reference?)
1>Runtime\Accelerator.cs(292,34,292,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer2D<T>' is less accessible than method 'Accelerator.Allocate<T>(int, int)'
1>Runtime\Accelerator.cs(267,32,267,40): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer<T>' is less accessible than method 'Accelerator.Allocate<T>(int)'
1>Runtime\Accelerator.cs(304,34,304,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer3D<T>' is less accessible than method 'Accelerator.Allocate<T>(Index3)'
1>Runtime\Accelerator.cs(279,34,279,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer2D<T>' is less accessible than method 'Accelerator.Allocate<T>(Index2)'
1>Runtime\Accelerator.cs(318,34,318,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer3D<T>' is less accessible than method 'Accelerator.Allocate<T>(int, int, int)'
1>Runtime\Accelerator.cs(292,34,292,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer2D<T>' is less accessible than method 'Accelerator.Allocate<T>(int, int)'
1>Runtime\MemoryBufferExtensions.cs(92,30,92,54): error CS0540: 'MemoryBuffer2D<T>.IMemoryBuffer<T, Index2>.View': containing type does not implement interface 'IMemoryBuffer<T, Index2>'
1>Runtime\MemoryBufferExtensions.cs(92,30,92,54): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\Accelerator.cs(304,34,304,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer3D<T>' is less accessible than method 'Accelerator.Allocate<T>(Index3)'
1>Runtime\MemoryBufferExtensions.cs(436,29,436,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\Accelerator.cs(318,34,318,42): error CS0050: Inconsistent accessibility: return type 'MemoryBuffer3D<T>' is less accessible than method 'Accelerator.Allocate<T>(int, int, int)'
1>Runtime\MemoryBufferExtensions.cs(442,29,442,41): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(92,30,92,54): error CS0540: 'MemoryBuffer2D<T>.IMemoryBuffer<T, Index2>.View': containing type does not implement interface 'IMemoryBuffer<T, Index2>'
1>Runtime\MemoryBufferExtensions.cs(92,55,92,59): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(454,30,454,54): error CS0540: 'MemoryBuffer3D<T>.IMemoryBuffer<T, Index3>.View': containing type does not implement interface 'IMemoryBuffer<T, Index3>'
1>Runtime\MemoryBufferExtensions.cs(92,30,92,54): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(454,30,454,54): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(436,29,436,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(835,29,835,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(442,29,442,41): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(848,29,848,41): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(92,55,92,59): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(454,55,454,59): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(454,30,454,54): error CS0540: 'MemoryBuffer3D<T>.IMemoryBuffer<T, Index3>.View': containing type does not implement interface 'IMemoryBuffer<T, Index3>'
1>Runtime\MemoryBufferExtensions.cs(24,29,24,52): error CS0540: 'MemoryBuffer<T>.IMemoryBuffer<T, Index>.View': containing type does not implement interface 'IMemoryBuffer<T, Index>'
1>Runtime\MemoryBufferExtensions.cs(454,30,454,54): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(24,29,24,52): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(24,53,24,57): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(835,29,835,39): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(561,21,561,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyFrom(T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(848,29,848,41): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T>'
1>Runtime\MemoryBufferExtensions.cs(583,21,583,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyFrom(AcceleratorStream, T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(454,55,454,59): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(715,21,715,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyTo(T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(24,29,24,52): error CS0540: 'MemoryBuffer<T>.IMemoryBuffer<T, Index>.View': containing type does not implement interface 'IMemoryBuffer<T, Index>'
1>Runtime\MemoryBufferExtensions.cs(738,21,738,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyTo(AcceleratorStream, T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(187,21,187,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyFrom(T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(24,29,24,52): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'IMemoryBuffer<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(212,21,212,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyFrom(AcceleratorStream, T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(24,53,24,57): error CS0453: The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'ArrayView<T, TIndex>'
1>Runtime\MemoryBufferExtensions.cs(328,21,328,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyTo(T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(561,21,561,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyFrom(T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(351,21,351,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyTo(AcceleratorStream, T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(583,21,583,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyFrom(AcceleratorStream, T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(715,21,715,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyTo(T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(738,21,738,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer3D<T>.CopyTo(AcceleratorStream, T[][][], Index3, Index3, Index3)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(187,21,187,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyFrom(T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(212,21,212,29): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyFrom(AcceleratorStream, T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(328,21,328,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyTo(T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Runtime\MemoryBufferExtensions.cs(351,21,351,27): warning CS3019: CLS compliance checking will not be performed on 'MemoryBuffer2D<T>.CopyTo(AcceleratorStream, T[][], Index2, Index2, Index2)' because it is not visible from outside this assembly
1>Done building project "ILGPU.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by samy2** [comment]
Hi @SoftSharper,
To compile the master branch, you have to manually generate the missing source files from the template (.tt) files : right click the .tt files one at a time in solution explorer and select "Run Custom Tool".
Then you should be able to compile the solution.

**Comment by SoftSharper** [comment]
Few templates have issues on "master": ArrayView.tt 
1>------ Build started: Project: ILGPU, Configuration: Debug Any CPU ------
1>ShuffleOperations.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>AtomicFunctions.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>TypeInformation.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>Done building project "ILGPU.csproj" -- FAILED.
1>AtomicFunctions.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>ShuffleOperations.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>TypeInformation.cs(1,1,1,22): error CS0116: A namespace cannot directly contain members such as fields or methods
1>Done building project "ILGPU.csproj" -- FAILED.

Tag 0.3 has correct code and desn't have those problems.

**Comment by m4rs-mt** [comment]
@SoftSharper I checked the master branch for compilation problems. However, a clean checkout of the master branch can be compiled following the steps suggested by @samy2. Can you check if all your templates have been successfully transformed?

**Comment by m4rs-mt** [comment]
I am able to reproduce your problem with unix line endings (without git's 'core.autocrlf' conversion under Windows), the T4 template tool and VS 2017 v15.9.4. Surprisingly, this problem does not seem to occur with VS 2017 v15.9.1 and older. To avoid future compilation problems, I will remove all `newline` characters at the end of the T4 templates.

**Comment by SoftSharper** [comment]
Also I saw this problem with VS2017 15.9.4 / Windows 10. But I downloaded the source code form Git web page using "Clone or download" button. I guess, if I would use git command line I shouldn't see that issue.

I think it may be helpful if you extend the "Build notes" with a note about *.tt templates.

Again, thank you for making this project, which is very useful in many ways for a lot of us.
