### ISSUE TITLE
Better error messages when kernel program failed to run.

### ISSUE THREAD

**Issue by 12345swordy** [m4rs-mt/ILGPU#1124]
~~Kernel code in question~~
I found out the problem. However I wish the exception also contain the source code generated as part of the error message, so I don't have to waste time trying to get the source generated from the kernel function, in order to figure out what the error message generated from.

**Comment by MoFtZ** [comment]
@12345swordy as part of the exception thrown by ILGPU, there is an inner exception that contains details like the file and line number where the error occurred.
