### ISSUE TITLE
Iteration of value with loops on GPU slows down significantly

### ISSUE THREAD

**Issue by p66114129** [m4rs-mt/ILGPU#1137]
First, I appreciate the developpers for this amazing work.

I am currently using GPU to perform some image processing. I want to calculate the true image coordinates by iterating the value in order to get the true value on GPU. Every coordinates of pixels of an processed image will be calculated and iterated in order to get the true coordinates on an orignial image. However, when it comes to the parts where it should be calculating on GPU, it seems like the program just pause. 
When I remove the iteration part, remaining a single calculation, it works as fast as usual. The other test I did was iterating twice. It slows down a bit but acceptable.  However, when I try to iterate 100 times , it seems like it pause, even if i iterate only 10 times.  I've tried it with for loop and do-while loop, but the performances are both bad.

I wonder what may be the problem to cause poor performance when iterating on GPU, and how to solve it.

Here's the part of iteration of GPU code

```
static void calculate(Index1D index, ....)
{
  //... calculate original image coordinate. ps. works fine here
  
  double tmpX = oriX; //original X
  double tmpY = oriY; //original Y
  
  double preX, preY, xbar, ybar, deltaX = 0, deltaY = 0;
  
   // the loop cause poor performance
  for (int time = 1; time <= 10; time++)  // works fine when this line is comment out 
  {
      preX = oriX;
      preY = oriY;
  
      xbar = oriX - Xp;
      ybar = oriY - Yp;
  
      double r = XMath.Sqrt(XMath.Pow(xbar, 2) + XMath.Pow(ybar, 2));
  
      deltaX = xbar * XMath.Pow(r, 2) * K1 + xbar * XMath.Pow(r, 4) * K2 + xbar * XMath.Pow(r, 6) * K3
          + (2 * XMath.Pow(xbar, 2) + XMath.Pow(r, 2)) * P1 + 2 * xbar * ybar * P2 + B1 * xbar + B2 * ybar;
      deltaY = ybar * XMath.Pow(r, 2) * K1 + ybar * XMath.Pow(r, 4) * K2 + ybar * XMath.Pow(r, 6) * K3
          + 2 * xbar * ybar * P1 + (2 * XMath.Pow(ybar, 2) + XMath.Pow(r, 2)) * P2;
  
      oriX = tmpX - deltaX;
      oriY = tmpY - deltaY;
  
      if (XMath.Sqrt(XMath.Pow(oriX - preX, 2) + XMath.Pow(oriY - preY, 2)) < 0.0001)
          break; //get correct coordinates
  
      if (time == 100)
      {
          oriX = double.NaN;
          oriY = double.NaN;
      }
  }


//... orther process which works fine
}
```

**Comment by MoFtZ** [comment]
hi @p66114129, it is likely an issue with the performance of the `XMath` functions. The `Sqrt` and `Pow` functions on the `double` type are currently not using an optimised implementation on Cuda devices.

As a workaround, you can use the `LibDevice` class in ILGPU, but it will only run on Cuda devices.

https://github.com/m4rs-mt/ILGPU/blob/master/Samples/LibDeviceKernel/Program.cs

**Comment by p66114129** [comment]
Thanks for your response @MoFtZ! 

At first, I used `Math` funtions, and it was very slow as well. After that, I turned to use the `XMath` funtions. To specify the problem, the kernal runs like it's doing nothing for a long time, and the calculation finishes sometime and instantly. That's what I learned from the task manager.

I will give `LibDevice` a try!

**Comment by p66114129** [comment]
`LibDevice` works! It's running as fast as I expected. Thanks a lot!

**Comment by MoFtZ** [comment]
FYI @p66114129, in a future version of ILGPU, we think we have found a way to get XMath to use LibDevice automatically.

**Comment by MoFtZ** [comment]
Raised https://github.com/m4rs-mt/ILGPU/pull/1189 for automatically enabling LibDevice.

Calls to `XMath` and `System.Math` will use LibDevice, if available.
