### ISSUE TITLE
[BUG] Cuda 12 SDK not supported with ILGPU 1.5.X

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#1194]
### Describe the bug

Our latest stable release does not support Cuda 12 SDK which causes issues with Blas in certain cases.

### Environment

- ILGPU version: 1.5.1
- .NET version: .Net6
- Operating system: Ubuntu 22.04

### Steps to reproduce

Run any ILGPU program using CuBlas on a platform with Cuda 12.

### Expected behavior

Cuda 12 should be supported by ILGPU v1.5.X.

**Comment by MoFtZ** [comment]
I have setup a Ubuntu 22.04 LTS VM, and installed Cuda SDK 12.4 Update 1.

In `/usr/local/cuda/lib64`, I found a symlink for `libcublas.so.12`, which is the correct naming that is used in ILGPU.Algorithms in ILGPU v.1.5.x.

We are also using `[DefaultDllImportSearchPaths(DllImportSearchPath.LegacyBehavior)]` on the Native Interop.

@m4rs-mt Can you provide more details on the issue with CuBlas?

Unfortunately, I do not have access to a Ubuntu machine with an Nvidia card, so am not able to test running on the GPU itself.

**Comment by m4rs-mt** [comment]
This issue has been resolved.
