### ISSUE TITLE
MemoryBuffer2D<int>.CopyFrom with weird behaviour.

### ISSUE THREAD

**Issue by weierstrass1** [m4rs-mt/ILGPU#128]
I was trying to copy part of a 2D array to a memory buffer 2D, but CopyFrom doesn't work:

`buff.CopyFrom(bp, new Index2(xOffset, yOffset), Index2.Zero, buff.Extent);`

buff is a int Memory Buffer of 16x16, the array bp is a int 2D array of 816x1024, xOffset = 0 and yOffset = 384.

It sends a System.ArgumentOutOfRangeException, name of parameter = sourceOffset.

sourceOffset should work because bp is a lot bigger.

Why it doesn't work?

EDIT: I was reading the code and it have a bug on MemoryBuffer2D CopyFrom here:

`            if (extent.X < 0 || extent.Y < 0 ||
                extent.X > source.GetLength(0) || extent.Y > source.GetLength(1))
            {
                throw new ArgumentOutOfRangeException(nameof(extent));
            }
`

Should be this instead:

`            if (extent.X < 0 || extent.Y < 0 ||
                extent.X + sourceOffset.X > source.GetLength(0) || extent.Y + sourceOffset.Y> source.GetLength(1))
            {
                throw new ArgumentOutOfRangeException(nameof(extent));
            }
`

**Comment by m4rs-mt** [comment]
@weierstrass1 Thank you for submitting this bug report. I can confirm that this is a bug that will be fixed in the next version.

**Comment by weierstrass1** [comment]
Looks like that wrong check repeats a lot on the memory buffer 2d class.
