### ISSUE TITLE
[BUG]: <title> Lower performance compare to native code

### ISSUE THREAD

**Issue by mahdiye-imanpanah** [m4rs-mt/ILGPU#1294]
### Describe the bug

In the ILGPU samples project, there's a comparison between ILGPU and native C# implementations. Although ILGPU is expected to be faster, it's actually much slower in this case. The specific example involves multiplying two matrices, 4x3 and 3x5. I tested the application with larger data, such as 100x100 to 100x100, but the output remains the same. I also attached the output of both data multiplications. Can you please explain why this is happening?
![Clipboard - October 20, 2024 7_02 PM](https://github.com/user-attachments/assets/1c1180ec-a4c9-4bb3-a48f-6b2a037438db)
![Clipboard - October 20, 2024 8_03 PM](https://github.com/user-attachments/assets/a05f97e9-c569-48e5-80f7-917d6b04a758)

### Environment

- ILGPU version: [e.g., 1.5.1]
- .NET version: [e.g., .NET 8]
- Operating system: [e.g., Windows 11]

### Steps to reproduce

This is the project's path if you need to test: \ILGPU\Samples\MatrixMultiply.

### Expected behavior

As I mentioned, the ILGPU methods are expected to be faster than native c# ones, but they are not.

**Comment by MoFtZ** [comment]
hi @mahdiye-imanpanah.

The TILE_SIZE in the MatrixMultiply sample project is very small, for maximum compatibility. Increasing the TILE_SIZE will give better GPU results.

In addition, the MatrixMultiply sample project was intended [as an example](https://github.com/m4rs-mt/ILGPU/issues/34), and was not written to be highly performant. There a various optimisations for faster matrix multiplication, but it would make the sample code harder to understand. If you want the best performance, without writing it yourself, you should trying using CuBLAS or CuFFT, both of which have bindings in ILGPU.

**Comment by mahdiye-imanpanah** [comment]
It is not just about this sample, I tried to run some different methods using native c# and ILGPU, but in all of them, ILGPU is slower.
This is one of them, could you please tell me why is this happening?
The kernel
`
  static void MIPKernel(
    Index2D index,
    ArrayView3D<ushort, Stride3D.DenseXY> volume,
    ArrayView2D<ushort, Stride2D.DenseX> output)
  {
      // Extract the (x, y) coordinates for the current pixel.
      int x = index.X;
      int y = index.Y;

      if (x < volume.Extent.X && y < volume.Extent.Y)
      {

          // Initialize the maximum intensity value to 0.
          ushort maxIntensity = 0;

          // Iterate along the Z-axis to find the maximum value for this (x, y) pixel.
          for (int z = 0; z < volume.Extent.Z; z++)
          {
              maxIntensity = Math.Max(maxIntensity, volume[x, y, z]);
          }

          // Store the maximum intensity in the 2D output projection.
          output[x, y] = maxIntensity;
      }
  }
`

`
 using (var context = Context.CreateDefault())
 using (var accelerator = context.GetPreferredDevice(preferCPU: false).CreateAccelerator(context))
 {
     //var targetData2D = new ushort[width, height];

     // Allocate buffers using the correct input sizes.
     using (var buffer = accelerator.Allocate3DDenseXY(slabData))
     using (var buffer2D = accelerator.Allocate2DDenseX<ushort>(new LongIndex2D(width, height)))
     {
         // Load the MIP kernel.
         var mipKernel = accelerator.LoadAutoGroupedStreamKernel<
             Index2D, ArrayView3D<ushort, Stride3D.DenseXY>, ArrayView2D<ushort, Stride2D.DenseX>>(MIPKernel);

             // Launch the kernel over a 2D grid of threads.
         mipKernel(new Index2D(width, height), buffer.View, buffer2D.View);

         // Copy the result back to the CPU.
         var targetData2D = buffer2D.GetAsArray2D();
}
`
The c# code is just nested loops and it is much faster than this code.

**Comment by MoFtZ** [comment]
Running calculations on a GPU does not guarantee that it will be faster. There are overheads, such as setting up the GPU, compiling the kernel, copying data to the GPU for processing, and copying the results back from the GPU.

Most common use cases are for corporate/enterprise environments that run large datasets. The GPU is setup once, at startup. The kernel is compiled once, at startup. The calculations performed are non-trivial, and scale well to large parallel calculations.

A CPU typically runs anywhere from 2 to 64 cores, and per core, generally runs faster. Each GPU core is typically slower than a CPU core, but there are many more of them. My 10 year old GPU can run 2,000 cores. The Nvidia 4070 has around 6k cores, a 4080 has almost 10k cores.

Not all calculations are suited for running on a GPU. And for small datasets, the overheads may be too expensive.
