### ISSUE TITLE
ILGPU Release Builds in Nuget package

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#130]
The current ILGPU Nuget packages contain `Debug` and `Release` builds. This has been the default choice for two main reasons:

1.  Because many expensive exception checks within the ILGPU compiler system were modeled using `Debug.Assert` operations.
2. The ILGPU runtime uses `Debug.Assert` operations to prevent out-of-bounds accesses to memory locations that can be used in the scope kernels (since exceptions are not supported by ILGPU).

The upcoming ILGPU version v0.8.1 will contain only one release build. This has several advantages over the previous setup: faster compile times, simplified nuget package structure, easier deployment and last but not least a smaller nuget packages (which is less important). In this context, there is a question: if we drop the debug build, the release build will not include `Debug.Assert` calls by default. Many runtime checks have already been converted to `throw` statements. However, this is not easily possible for code running on the GPU due to the current lack of exception support.

There are essentially two options:

1. Adding"basic" support for `throw` instructions and `Exception` classes to the ILGPU compiler.
2. Ensure that the `Debug.Assert` calls are retained in ILGPU `Release` builds.

What do you think would be the best option?
I would prefer the second option at the moment, which is less invasive with respect to the current code base.

**Comment by jgiannuzzi** [comment]
I think that adding basic support for exceptions could set the wrong expectations about the type of code one can write in a GPU kernel.

About the second option, what would the cost be of retaining the `Debug.Assert` calls in the Release builds?

**Comment by m4rs-mt** [comment]
We should add `#define DEBUG` to the source files where we want to retain these assert calls 🤓

**Comment by GPSnoopy** [comment]
If you want to keep the assertion even in Release build, then use `Trace.Assert()` (https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace.assert?view=netcore-3.1).

Ultimately, `Debug.Assert()` is there for performance reason, such that expensive checks are not done in the final build. For example, checking out-of-bound access on a custom class indexing operator. Such a check in a loop would be quite expensive.

What are the exact places where you want to keep these checks? Having a _O(1)_ check on top of a _O(n)_ (or expensive _O(1)_ method) is fine, even in release (hence the common use of exceptions).

Either way, worth testing to see the runtime implication. Especially when the assertion is hit and needs to stop the program. Also worth documenting the behaviour for the users.

**Comment by m4rs-mt** [comment]
@GPSnoopy Yes this would be a reasonable alternative. I have already been thinking about the same possibility.

> What are the exact places where you want to keep these checks? Having a O(1) check on top of a O(n) (or expensive O(1) method) is fine, even in release (hence the common use of exceptions).

These checks are usually used within GPU kernels to verify certain preconditions or invariants (e.g. bounds accesses). The intention behind the `Debug.Assert` function was that programmers could be sure that calls to these methods would not be performed in release builds. However, developers have to enable the flag `ContextFlags.EnableAssertions` in ILGPU to ensure that these calls are preserved in the actual GPU code.

**Comment by GPSnoopy** [comment]
Then I'm not sure I understand the scope of Debug vs Release if the assertions are embedded during kernel compilation by ILGPU.

Are you asking whether the user should use `Debug.Assert` or `Trace.Assert` (on top of `ContextFlags.EnableAssertions`)? Or are you talking about extra checks that ILGPU adds?

Either way the documentation for `ContextFlags.EnableAssertions` should probably be extended. :-)

**Comment by m4rs-mt** [comment]
@GPSnoopy Currently, ILGPU debug builds (within the nuget package) retain all `Debug.Assert` calls to allow the use of assertions in GPU kernels (also within the `CPUAccelerator`). However, you can still decide whether to enable them for actual GPU kernels. If your application was created in `Debug` mode, the nuget `.targets` file will automatically select the ILGPU `Debug` version to have the ability to use assertions in your code. If you build your application in `Release` mode, there is no way to enable assertions in your GPU kernels, as all calls to `Debug.Assert` functions have been removed in advance by the compiler (as intended).

**Comment by m4rs-mt** [comment]
@GPSnoopy I completely agree that we should spend some time polishing these flags 😄

**Comment by GPSnoopy** [comment]
But if the application is compiled in `Debug` and ILGPU is compiled in `Release`, the user's `Debug.Assert` should still appear in the GPU code, right?

Or does it have a performance impact to allow that (even on `Release` application builds where `Debug.Assert` is not emitted)? I.e is there a good reason for ILGPU not to allow asserts by default?

**Comment by m4rs-mt** [comment]
> But if the application is compiled in Debug and ILGPU is compiled in Release, the user's Debug.Assert should still appear in the GPU code, right?

Yes, that's right.

> Or does it have a performance impact to allow that (even on Release application builds where Debug.Assert is not emitted)?

There has been a performance impact in the past. However, these issues could be resolved in v0.8.

> I.e is there a good reason for ILGPU not to allow asserts by default?

The only reason why you do not want to enable assertions by default in GPU kernels in `Debug` mode is because the resulting `PTX` module is annotated with `.debug`. This in turn disables *any* driver optimization by default. Unfortunately this will also happen if debug information is enabled in the current ILGPU version and a debugger is attached.
