### ISSUE TITLE
[BUG]: Illegal Memory Access for MemoryBuffer2D

### ISSUE THREAD

**Issue by elekta-cp-rnca** [m4rs-mt/ILGPU#1306]
### Describe the bug

When testing a simple matrix multiplication algorithm on GPU the CUDA runtime throws an error when 2D matrix (m,n) is equal to or greater than (65,65). Code works as expected for 2D arrays say (60,60) and smaller. In same project environment I created a MemoryBuffer1D and ran into no issues until I ran out of GPU memory as expected.

### Environment

- ILGPU version: 1.5.1
- .NET version: .NET 4.8
- Operating system: Windows 10 Enterprise LTSC (v. 10.0.17763 Build 17763)
- Hardware (if GPU-related): NVIDIA RTX 6000 Ada

### Steps to reproduce

Code provided.

Adjust ints mrow and mcol to vary behavior. Current settings are (65,65) which reproduces error in cuda.runtime. (60,60) does not throw exception to illegal memory access.

### Expected behavior

As with 1D MemoryBuffer, should not see error until memory exhausted on GPU.
[GPUMatrixTests.zip](https://github.com/user-attachments/files/17938455/GPUMatrixTests.zip)
![Screenshot 2024-11-27 1](https://github.com/user-attachments/assets/ece99ae3-2f7b-4b47-816f-e376d2c7e185)

**Comment by MoFtZ** [comment]
hi @elekta-cp-rnca, thanks for providing the source code.

In the function `Matrix_2D_Kernel`, you have a for loop that looks like this:
```CSharp
for (var i = 0; i < g_a_matrix.IntLength; i++)
    sum += g_a_matrix[new Index2D(x, i)] * g_b_matrix[new Index2D(i, y)];
```

The issue is with `g_a_matrix.IntLength` - this returns `65 * 65` = 4225.
The code is then accessing `g_a_matrix` and `g_b_matrix` using an index, which is out-of-bounds.

Instead, you should use `g_a_matrix.IntExtent.X` or `g_a_matrix.IntExtent.Y`, both of which would return `65`, in your example code.
```CSharp
for (var i = 0; i < g_a_matrix.IntExtent.X; i++)
    sum += g_a_matrix[new Index2D(x, i)] * g_b_matrix[new Index2D(i, y)];
```

**Comment by elekta-cp-rnca** [comment]
Yes ... thank you. I was running your sample MatrixMultiply (with no issues) to see if this was on me. Thanks again!

**Comment by MoFtZ** [comment]
> @MoFtZ since the loop is over i with ka=kb required (2nd index of g_a or 1st index of g_b) ... would the proper selection be g_a_matrix.IntExtent.Y or g_b_matrix.IntExtent.X ?

It does not really matter, since both values must be equal for the algorithm to work. You would likely write code before calling the GPU kernel that ensures the dimensions are the same.

**Comment by elekta-cp-rnca** [comment]
@MoFtZ always good to check interior dimension check. Thanks for the info and help. Keep up the good work. Cheers!
