### ISSUE TITLE
PTX compilation failed with bytes

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#15]
Hi,
I tested today the master branch (commit cf83683e131cde5c2182f02b7dc0ed89896851ea).
All the bugs I reported are corrected (great work!), except this one :

        [Test]
        public void CompilationTest3()
        {
            using (var context = new Context())
            {
                using (var gpu = new CudaAccelerator(context, 0))
                {
                    var method = GetType().GetMethod(nameof(Kernel3), BindingFlags.NonPublic | BindingFlags.Static);
                    var compiledKernel = gpu.Backend.Compile(method, KernelSpecialization.Empty);
                    var loadedKernel = gpu.LoadKernel(compiledKernel);
                    loadedKernel.Dispose();
                }
            }
        }

        private static void Kernel3(GroupedIndex index, ArrayView<float> array)
        {
            byte b = 1;
            for (int i = 0; i < 2; i++)
            {
                if (b > 1)
                {
                    array[0] = 1;
                }
                b = 2;
            }
        }

The exception I get : ILGPU.Runtime.Cuda.CudaException : 'a PTX JIT compilation failed'

**Comment by m4rs-mt** [comment]
It turns out that the PTX backend still generates some invalid movement instructions (in this case for temporary registers). The problem will be fixed in the next commit.

**Comment by samy2** [comment]
I confirm that it works with the last commit! Great!
