### ISSUE TITLE
Can multiple GPU cores exchange data between each other without through host data transfer?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#154]
@m4rs-mt Can ILGPU allow data to be exchanged between several GPU cores so that multiple GPU parallel computing can be achieved?

**Comment by m4rs-mt** [comment]
@toolwtech Thank you for your question. You can enable GPU<->GPU data transfer via `EnablePeerAccess` on an `Accelerator` instance. However, this only works properly between NVIDIA GPUs at the moment. All other accelerators require memory transfers via the CPU host memory.

**Comment by toolwtech** [comment]
@m4rs-mt Just confirm: does it work between AMD GPUs either?  Is it possible to support data transfer between different brand GPUs in the future? Thanks for your response!

**Comment by m4rs-mt** [comment]
@toolwtech This feature is currently not supported on *any* OpenCL device "officially". However, you might want to experiment with buffer<->buffer copies via the `CopyTo` function. It uses `clEnqueueCopyBuffer` under the hood to copy data from one OpenCL buffer to another one.

We may want to add "official" support for these scenarios in a future release.
