### ISSUE TITLE
LDToken/Static array is not supported

### ISSUE THREAD

**Issue by Luminisc** [m4rs-mt/ILGPU#17]
I'm having issue with creation of new array in kernel.
If I'm using something like
```
var sobelXKern = new short[3, 3]
{
    { -1,0,1 },
    { -2,0,2 },
    { -1,0,1 }
};
var sobelXKern = new short[9]
{
    -1,0,1,
    -2,0,2,
    -1,0,1
};
```

The compiler will create ldtoken instruction, which is not supported.

Is there any way to have predefined/readonly array to use in kernel?
![ldtoken](https://user-images.githubusercontent.com/10280045/57588394-3594f780-751c-11e9-9f98-4a8e0b423d89.PNG)

**Comment by m4rs-mt** [comment]
@Luminisc Arrays are class (reference) types that are currently not supported. However, as outline in the ILGPU roadmap, one of the upcoming versions will provide limited support for class types. This also includes support for arrays with lengths known at compile time.
