### ISSUE TITLE
64bit length MemorBuffers

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#173]
The current implementation of all `MemoryBuffer` classes does not provide the possibility to allocate an instance with more than `int.MaxValue` number of elements. This makes the use of buffers with 64bit-length allocations challenging. Since modern GPUs offer much more memory than `2GB`s RAM, it definitely makes sense to support large memory buffer allocations.

We have been thinking about different ways to realize such `long`-length `MemoryBuffer` allocations. The ".Net way" to implement these allocations would (probably) be via two properties: `LongLength` of type `long` and `LongExtent` of type `LongIndexX`. We could rename the default index types `(Index1|Index2|Index3)` to `(IntIndex|IntIndex2|IntIndex3)` and introduce their corresponding `long` counterparts `(LongIndex|LongIndex2|LongIndex3)`. This makes it easy to differentiate between 32bit and 64bit 1D/2D and 3D indexes. Furthermore, you could still use the 32bit index types in favor of the 64bit versions to save registers and improve performance in the scope of memory-address computations.

What do you think?

**Comment by MoFtZ** [comment]
I am undecided on changing the current naming of `(Index1|Index2|Index3)` to `(IntIndex1|IntIndex2|IntIndex3)`. If anything, I'm leaning towards keeping the existing names.

Pros for change:
- Easy to visually differentiate between 32-bit and 64-bit indices.
- Easy to do a "find in files" for `IntIndex1`.

Cons for change:
- users will have to refactor their existing code.
- 64-bit length MemoryBuffers usage is rare (?)
    - we have `Length` because that's the common usage, so why require `IntIndex1` for common usage?

QUESTION: How common is it for a GPU algorithm to need access to the full 64-bit length?

For example, the initial kernel launch provides a 64-bit length MemoryBuffer. Then subsequent operations partition this into smaller sub-views of that large buffer. Therefore, these other operations only need to work with a 32-bit length buffer. Does that make sense?

**Comment by m4rs-mt** [comment]
I stumbled across several use cases with large matrices in the domain of neural networks. Since these matrices can become arbitrarily large, this extension would reduce the implementation/partitioning effort.

Unfortunately, users will have to revise their implementations during an upgrade process. We could keep the old index types for now and mark them as `obsolete`. This ensures that people have a sufficient amount of time before they a really enforced to upgrade their implementations.

> we have Length because that's the common usage, so why require IntIndex1 for common usage?

What exactly do you mean? I guess we should keep `Length` and add another property called `LongLength` that returns a 64bit integer (like `Array.LongLength`).

**Comment by MoFtZ** [comment]
> I stumbled across several use cases with large matrices in the domain of neural networks. Since these matrices can become arbitrarily large, this extension would reduce the implementation/partitioning effort.

OK, so my idea for only providing `int` indexing into `ArrayView` is not a good idea :-1: 

> > we have Length because that's the common usage, so why require IntIndex1 for common usage?
> 
> What exactly do you mean? I guess we should keep `Length` and add another property called `LongLength` that returns a 64bit integer (like `Array.LongLength`).

I am referring to the expected usage by end users.

If using 64-bit length buffers is rare, then most users only need to think about `Index1` and `Length`. Then, in the rare cases, they would upgrade to using `LongIndex1` and `LongLength`.

However, if 64-bit length buffers are more common (less rare), having `IntIndex1` would force them to consider whether they should be using `IntIndex1` vs `LongIndex1`.

**Comment by m4rs-mt** [comment]
@MoFtZ that's true. Maybe we should keep the `IndexX` types and only offer additional `LongIndexX` alternatives. However, I thought that people would not think about the "32bit nature" of the `IndexX` types, since the name of the structure does not give any clues.

**Comment by GPSnoopy** [comment]
I think I'm okay with `Index`/`Length` and `LongIndex`/`LongLength`. This keeps the existing code compatible and makes it explicit when moving to 64-bit indexing (which is usually slower on GPUs).

Two indexing operator overloads are then needed, one for `int` and one for `long`. Might be worth googling if there are obscure overloading rules that would rain on our parade. Although a quick search seems to imply it's okay? (https://stackoverflow.com/questions/27458883/method-overloading-with-types-int-and-long-which-method-will-get-called-and-whe)

I wonder how many cheap protections we can add to make sure a user does not call `Length` on an array with a long size (e.g. throw an OverflowException as per `System.Array.Length`). Host side it might be easy (depending on how clever the .NET JIT compiler is when calling it in a loop). GPU side could get a lot more complicated.

**Comment by m4rs-mt** [comment]
@GPSnoopy we could add `Assert` checks that can be enabled/disabled via the `ContextFlags` enumeration.

**Comment by m4rs-mt** [comment]
I have played around with the different proposals and I have been thinking about this property definition of an `IArrayView`:
```c#
        /// <summary>
        /// Returns the length of this array view in bytes.
        /// </summary>
        int LengthInBytes { get; }
```
We should change this to
```c#
        /// <summary>
        /// Returns the length of this array view in bytes.
        /// </summary>
        long LengthInBytes { get; }
```
in order to be compatible with other .Net types like the `Stream` class. However, this would be a breaking change.

**Comment by GPSnoopy** [comment]
IMHO `long LengthInBytes` is an acceptable compromise given that it will not be as widely used as `Length` and that `LengthInBytes` can already easily overflow an `int32` even if `Length` is well under the `int32` limit (e.g. 256M doubles will be 2GB).
