### ISSUE TITLE
Why does the CLAccelerator constructor require a CLAcceleratorId?

### ISSUE THREAD

**Issue by jptemplin** [m4rs-mt/ILGPU#174]
Interesting project! I tried hacking the Mandelbrot sample to include my OpenCL-capable Intel processor in the tests, but I noticed that the CLAccelerator constructor needs a CLAcceleratorId second parameter. The other accelerator constructors don't. Why is this? Is there an easier way to instantiate the OpenCL accelerator, and/or an easier way to get the CLAcceleratorId?

```
public static void CompileKernel(string acceleratorType)
{
    context = new Context();
    if (acceleratorType == "CUDA")
        accelerator = new CudaAccelerator(context);
    else if (acceleratorType == "CPU")
        accelerator = new CPUAccelerator(context);
    else
    {
        var acceleratorId = CLAccelerator.CLAccelerators[0];
        accelerator = new CLAccelerator(context, acceleratorId);
     }
     mandelbrot_kernel = accelerator.LoadAutoGroupedStreamKernel<
         Index1, int, int, int, ArrayView<int>>(MandelbrotKernel);
}
```

BTW: my results after running the graphic at roughly 4x the size. At the default size, CPU was only slightly slower than OpenCL.

CPU Mandelbrot 00:02.666   -   26669535 Ticks
ILGPU-CPU Mandelbrot 00:00.892   -   8924998 Ticks
ILGPU-OpenCL Mandelbrot 00:00.144   -   1445435 Ticks
ILGPU-CUDA Mandelbrot 00:00.040   -   403217 Ticks

My DeviceInfo (my CPU is an Intel i7-7700K):

AcceleratorId: CPU, CPUAccelerator
Name: CPUAccelerator
MemorySize: 9223372036854775807
MaxThreadsPerGroup: 8
MaxSharedMemoryPerGroup: 2147483647
MaxGridSize: (2147483647, 2147483647, 2147483647)
MaxConstantMemory: 2147483647
WarpSize: 1
NumMultiprocessors: 1

AcceleratorId: Cuda, GeForce GTX 1070
Name: GeForce GTX 1070
MemorySize: 8589934592
MaxThreadsPerGroup: 1024
MaxSharedMemoryPerGroup: 49152
MaxGridSize: (2147483647, 65535, 65535)
MaxConstantMemory: 65536
WarpSize: 32
NumMultiprocessors: 15

AcceleratorId: OpenCL, Intel(R) HD Graphics 630
Name: Intel(R) HD Graphics 630
MemorySize: 13703417856
MaxThreadsPerGroup: 256
MaxSharedMemoryPerGroup: 65536
MaxGridSize: (256, 256, 256)
MaxConstantMemory: 1024
WarpSize: 16
NumMultiprocessors: 24

**Comment by m4rs-mt** [comment]
The reason why the OpenCL accelerator requires an `AcceleratorId` instance is the fact that OpenCL differentiates between different platform and device ids. In this scope, it is often unclear which device from which platform to pick "by default". In contrast to OpenCL, the `CudaAccelerator` will be implicitly instantiated using the default PCIe card slot (`Cuda deviceId = 0`, which usually corresponds to your primary Cuda-capable device).

**Comment by jptemplin** [comment]
Thanks so much for the reply. I have only one OpenCL device in my system, but I can see how you might have more than one.
