### ISSUE TITLE
XMath does not include Atan2

### ISSUE THREAD

**Issue by Costigan** [m4rs-mt/ILGPU#18]
I'm using version 5.1 installed in a c# project by NuGet.
The upgrade guide for release 5.0 says that GPUMath was replaced by XMath.  In doing so, some functions were apparently omitted, including Acos, Asin, Atan and ATan2.  The MathIntrinsicKind enumeration still contains that seem to correspond to these functions.

What drove the removal of these functions?
Might they be included again in a future release?
(I'm hoping for .NET Core support but need these functions.)

Btw, this project is very nice to use.  Thank you.

**Comment by m4rs-mt** [comment]
Yes, you're absolutely right. I will restructure these functions in the next release anyway. At this point I will add the missing mathematical functions :)

**Comment by Costigan** [comment]
Great.  Thank you.

**Comment by m4rs-mt** [comment]
The new ILGPU.Algorithms library has integrated support for the missing `XMath` functions.
See [https://github.com/m4rs-mt/ILGPU.Algorithms](https://github.com/m4rs-mt/ILGPU.Algorithms)

**Comment by Costigan** [comment]
Hello.  I'm trying to port to 0.6.0.  XMath.Atan2() is missing again.  I'm compiling for netcor3.0 and have installed the ILGPU (0.6.0) and ILGPU.Lighting (0.3.0) packages, and XMath.Atan2() is missing.  Do I need to install something else?

**Comment by m4rs-mt** [comment]
@Costigan `Atan2` will be available in v0.7. Version v0.6 does not include an `Atan2` implementation yet. `ILGPU.Algorithms` supports `XMath.Atan2` for `CPU` and `PTX` targets.
