### ISSUE TITLE
Is there any attribute to exclude method of struct to be compiled in generic kernel?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#188]
I have following class and struct (e.g)
```c#
public class Parser
{
 ....
}

interface ITest
{
    void SetParameter(Parser parse)
    void Calculate() 
}

public struct Test:ITest
{
    public void SetParameter(Parser parse){}
    public void Calculate(){}
}

public static void Kernel<T><ArrayView<int>>
    where T : struct, ITest
{
.....
}

void Main()
{
...
   var kernel = accelerator.LoadStreamKernel<
                            ArrayView<int>>(Kernel<Test>);
...
}
```
compiling Kernel<Test> will fail because there is CLASS ("Parser") in method of "SetParameter",  Is there attribute or decoration for methods  or fields that can be excluded to compile to GPU kernel so that we can use the "struct" in both CPU and GPU?

**Comment by MoFtZ** [comment]
hi @toolwtech, as long as the `SetParameter` method is not being used in the kernel, ILGPU will ignore it.

I have attached some sample code which shows a 'good' kernel using the `Calculate` method, and a 'bad' kernel that calls into `SetParameter` (and therefore throws an exception).

[UnusedStructMethodWithClass.zip](https://github.com/m4rs-mt/ILGPU/files/4907862/UnusedStructMethodWithClass.zip)

**Comment by toolwtech** [comment]
Thanks! @MoFtZ
