### ISSUE TITLE
Throw error when creating auto grouped kernel

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#194]
I am trying to see if I can dynamically create a kernel, but get following error

 Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

Attached is the sample code.  Do I do something wrong?  Thanks!
[ImplicitlyGroupedKernels.zip](https://github.com/m4rs-mt/ILGPU/files/4927116/ImplicitlyGroupedKernels.zip)

**Comment by m4rs-mt** [comment]
First of all, this is an error message that has been created by the .Net runtime system. It essentially tells you that your delegate signature (that you are trying to bind your method to) is not compatible with respect to the method parameters.

In this case, you are missing the `AcceleratorStream stream` parameter, which is the first one. Your delegate needs to have the following signature:
```c#
internal delegate void KernelDelegate(
    AcceleratorStream stream,
    Index1 index,
    ArrayView<int> data);
```
If you want to use the default accelerator stream, you can use the `LoadAutoGroupedStreamKernel` method.

**Comment by toolwtech** [comment]
Got it, thanks! @m4rs-mt
