### ISSUE TITLE
Symbols package is missing on Nuget.org

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#195]
ILGPU was recently [modified](#141) to build a symbols package that gets uploaded to Nuget.org.

This [blog post](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server) suggests that there should be a link to download symbols:
![image](https://user-images.githubusercontent.com/27792737/87676079-81e06500-c7bb-11ea-992e-f79df81bcd28.png)

However, when looking at the [ILGPU page](https://www.nuget.org/packages/ILGPU/0.8.1.1) in Nuget, there is no link to download the symbols package. And subsequently, debugging in VS2019 using SourceLink does not find any symbols.

According to the `publish-nuget` step in the [build for v0.8.1.1](https://github.com/m4rs-mt/ILGPU/runs/834123889), the symbols package was successfully uploaded.
```
Pushing ILGPU.0.8.1.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 729ms
Your package was pushed.
Pushing ILGPU.0.8.1.1.snupkg to 'https://www.nuget.org/api/v2/symbolpackage'...
  PUT https://www.nuget.org/api/v2/symbolpackage/
  Created https://www.nuget.org/api/v2/symbolpackage/ 357ms
Your package was pushed.
```

Need to investigate why the symbols package is missing.

**Comment by m4rs-mt** [comment]
@MoFtZ The problem seems to be related to the non-portable PDB symbols of the .Net 4.7 build.

**Comment by m4rs-mt** [comment]
I have found an internal Nuget publication log:
```
The symbol package ILGPU 0.8.1.1 failed validation because of the following reason(s):

The uploaded symbols package contains one or more pdbs that are not portable.
```

**Comment by MoFtZ** [comment]
ok, I'll raise a PR to remove the net47 pdb.

**Comment by MoFtZ** [comment]
Hmm.. can't find a way to remove just the net47 pdb. Maybe need to wait until we can safely upgrade net47 to net472?
