### ISSUE TITLE
Can MemoryBuffer be allocated to zero array?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#198]
It seems that  accelerator.Allocate<..>(0) doesn't work.  It would bring flexibility if zero array can be allocated to MemoryBuffer (say, empty buffer) like "int[] a = new int[0]"

**Comment by toolwtech** [comment]
@Yey007 Let me give you an example, assuming that I have a kernel as followings:

static void Kernel(ArrayView<int> dataView1, ArrayView<int> dataView2){};

dataView2 may has zero array depending on my input (actually it always happens in my program, dataView1 is associated with dataView2, but sometimes dataView2 doesn't have value.  e.g.  in mechanical simulation, dataView2 is boundary condition etc. ) .  How can you simplify the kernel above?

What I can do is, 

Create another kernel:

static void kernel1((ArrayView<int>){}

and then, 

if(buffer!=null)
{
   kernel(dataView1, buffer.View);
}else
{
  Kernel1(dataView1);
}
and also I have to add "if" to allocate or not allocate data to the buffer.

or, I allocate buffer with one array, and add another argument to kernel to indicate dataView2 can not be used:

static void Kernel(ArrayView<int> dataView1, ArrayView<int> dataView2, int flag){};

If zero array can be assigned to buffer, I only need to add one "IF" in Kernel

if(dataView2.Length==0)
{
...
}

Not sure if there is any other way to simplify code if zero array can't be allocated to buffer. It is a little annoying to add extra codes.

**Comment by MoFtZ** [comment]
@toolwtech ILGPU does not currently support zero-length memory buffer allocations. This follows the same behaviour as the underlying CUDA API `cuMemAlloc` - `If bytesize is 0, cuMemAlloc() returns CUDA_ERROR_INVALID_VALUE`. The documentation for this can be found [here](
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gb82d2a09844a58dd9e744dc31e8aa467).

As you mentioned, using the current ILGPU API, you will need an `if` check to avoid allocating a zero-length memory buffer, and you will also need to launch a different kernel.

One way that you can simplify your kernels is to create an empty `ArrayView` within the kernel - this can be zero-length, and then call the other kernel.

```CSharp
public static void KernelTwoParameters(Index1 index, ArrayView<int> input1, ArrayView<int> input2)
{
    // Do work
}

public static void KernelWithOneParameter(Index1 index, ArrayView<int> input1)
{
  var emptyInput2 = new ArrayView<int>();
  KernelWithTwoParameters(index, input1, emptyInput2);
}
```

**Comment by toolwtech** [comment]
Thanks for your suggestion! @MoFtZ
