### ISSUE TITLE
Is there any way to create generic Kernel without knowing type at compile time?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#199]
It seems that I have to use Reflection to get method of "LoadStreamKernel" and invoke this method to create Kernel, but I am getting lost at how to reflect method to "Action<..>".  I am not sure if it is a correct way to do that. It would be easy for someone who is very familiar with generic code and reflection. Attached is sample code, Is there anyone  that can help?  Thanks!

**Comment by MoFtZ** [comment]
@toolwtech Have you seen the GenericKernel sample from [ILGPU.Samples](https://github.com/m4rs-mt/ILGPU.Samples)? Is that what you are trying to achieve?

**Comment by toolwtech** [comment]
@MoFtZ  I've already gone through those examples including GenericKernel. Yes, it is fairly easy to create generic kernel if type is known at compile time. But what I want to achieve is to create the generic kernel based on the type at runtime. I am stuck at some point (comment of "fails" in the sample code") . Generic kernel can be created without knowing type at compile time if that point can be fixed up.  Maybe there is better solution.

**Comment by MoFtZ** [comment]
@toolwtech have you tried something like:
1. Get your generic kernel method using reflection - `typeof(Program).GetMethod("MyKernel")`
1. Turn the generic kernel into a concrete method - `var methodInfo = MethodInfo.MakeGenericMethod(types);`
1. Use the low-level ILGPU Kernel APIs to compile - see `LowLevelKernelCompilation` sample.

**Comment by toolwtech** [comment]
@MoFtZ Nice! thanks you very much!
