### ISSUE TITLE
Missing support for __constant__ & __launch_bounds__ ?

### ISSUE THREAD

**Issue by trmcnealy** [m4rs-mt/ILGPU#2]
## Example \_\_launch_bounds__

> Cpp
```cpp
#define MAX_THREADS_PER_BLOCK 256
#define MIN_BLOCKS_PER_MP     2
__global__ void
__launch_bounds__( MAX_THREADS_PER_BLOCK, MIN_BLOCKS_PER_MP )
Kernel1() { }
```

> LLVM-IR
```cpp
define void @Kernel1() #0 {
  %1 = call i32 @cudaLaunch(i8* bitcast (void ()* @Kernel1 to i8*))
  br label %2
  ret void
}
!0 = !{void ()* @Kernel1, !"kernel", i32 1}
!1 = !{void ()* @Kernel1, !"maxntidx", i32 256}
!2 = !{void ()* @Kernel1, !"minctasm", i32 2}
```

>CS
```cs
/// <summary>
/// LaunchBounds
/// Specify Launch Bounds for CUDA execution
/// </summary>
public struct LaunchBounds
{
    /// <summary>
    /// Max threads per block
    /// </summary>
    public readonly uint maxTperB;
    /// <summary>
    /// Min blocks per SM
    /// </summary>
    public readonly uint minBperSM;

    public LaunchBounds(uint maxT = 1024, uint minB = 1)
    {
        maxTperB = maxT;
        minBperSM = minB;
    }
}

var kernel = accelerator.LoadKernel<>(MyKernel, LaunchBounds);
```

## Example \_\_constant__

> Cpp
```cpp
__constant__ int constant_var;
```

> LLVM-IR
```cpp
@constant_var = internal global i32 0, align 4
```

**Comment by m4rs-mt** [comment]
Default constants (and read-only static fields) in the .Net world are already supported by ILGPU (refer to the [ILGPU constant sample](https://github.com/m4rs-mt/ILGPU.Samples/tree/master/Src/SimpleConstants) for more information).
Constant values will be "sliced" (inlined) into the instruction stream or will be stored in constant memory.
Note that only simple value types are currently supported.
We may want to add additional support for arrays that are automatially stored in constant memory.

**Comment by m4rs-mt** [comment]
I have added support for specializing kernels during the compilation process (see cb06d9420ee1edb52740c10da9c34a965d34402e).
You can use the `ILGPU.Compiler.KernelSpecialization` structure to express domain-specific knowledge.
As desired, you can specific the maximum number of threads per group and the minimum number of groups per multiprocessor (currently).
The functionality will be extended in the future.

Minimal example:
```
var kernel = acclelerator.LoadKernel<...>(MyKernel,
    new ILGPU.Compiler.KernelSpecialization(
       maxNumThreadsPerGroup: 32,
       minNumGroupsPerMultiprocessor: 2));
```


These changes will be included in the next release.
