### ISSUE TITLE
[Suggestion] Indexing in 3D view via Index2

### ISSUE THREAD

**Issue by Luminisc** [m4rs-mt/ILGPU#20]
Just as suggestion, want to have ability to indexing to 3D view with Index2 and variable, instead of deconstruction of Index2 into index.X, index.Y like its done in many shader languages.

Example:
```
void Func(ArrayView3D<T> array)
{
    Index2 index = new Index2();
    // suggestion
    array[index, 1] = somevalue;
    array[1, index] = somevalue;
    //instead of
    array[index.X, index.Y, 1] = somevalue;
    array[1, index.X, index.Y] = somevalue;
}
```

**Comment by m4rs-mt** [comment]
This is definitely a feature we should add to allow more comfortable programming of shader-like kernels.
