### ISSUE TITLE
When AMD GPUs will be supported?

### ISSUE THREAD

**Issue by GiorgosXou** [m4rs-mt/ILGPU#21]
I know it is not the best thing to ask about fetures and especially when they will be supported, but i was wondering because, on the [roadmap](http://www.ilgpu.net/Home/Roadmap) i haven't seen anything about it yet and for a project i am working on it is needed, so is there any plan for it or is it considered to be supported in the near future? or [...]

Any reply would be appreciated, 
Thanks in Advance,
George. (:

**Comment by m4rs-mt** [comment]
@GiorgosXou ILGPU will support an OpenCL backend in version 0.7 (see #16), which will be available in Q3. This allows the use of the latest AMD and Intel GPUs :)

PS: I will update the roadmap as soon as possible.

**Comment by m4rs-mt** [comment]
The current status of the general `OpenCL` backend is now tracked in different issues. I will close general this issue for now.
