### ISSUE TITLE
Crash in kernel compilation when using multiple fixed buffers in a struct (0.9-beta1)

### ISSUE THREAD

**Issue by dje-dev** [m4rs-mt/ILGPU#213]
Thank you for the new fixed feature, this will be very useful. I believe the code below demonstrates a problem in code generation (CUDA only) with this new feature. 

Perhaps related, if only the first fixed array is defined but made larger (2048 elements) a different error is seen: "device kernel image image is invalid."
 ```c#
public unsafe struct TestStruct
{
  public fixed int Bytes1[2];
  public fixed int Bytes2[1];   // Compilation is successful if this line is commented out
}
  
  static unsafe void MyKernel(Index1 index, TestStruct ss)
  {
    // PROBLEM: yields IndexOutOfRangeException in PTXCodeGenerator.GenerateCode
    if (LocalStruct.Bytes1[0] == 7) return; 
    
    // PROBLEM: yields "CUDA_ERROR_INVALID_PTX"
    if (ss.Bytes1[0] == 7) return; 
}


  static readonly TestStruct LocalStruct;

  static void Main()
  {
    using (var context = new Context())
      foreach (var acceleratorId in Accelerator.Accelerators)
        using (var accelerator = Accelerator.Create(context, acceleratorId))
          accelerator.LoadAutoGroupedStreamKernel<Index1, TestStruct>(MyKernel);          
  }
```

**Comment by m4rs-mt** [comment]
@dje-dev Thank you for submitting this issue.

> Perhaps related, if only the first fixed array is defined but made larger (2048 elements) a different error is seen: "device kernel image image is invalid."

This error message indicates that a particular structure is too to fit into constant memory of your GPU and is issued by the GPU driver. The upcoming capability API (#103) will provide high-level error messages in the future.

Regarding the compilation errors: I can confirm that loading an unsafe structure from a static field does not seem to work properly. This piece of code throws an internal compiler error, indicating that some functions to handle these cases are currently missing. However, I cannot reproduce the problems you mentioned regarding "default" buffer accesses. Both cases you posted seem to work like a charm.
