### ISSUE TITLE
Generating variable number of items.

### ISSUE THREAD

**Issue by Delpire** [m4rs-mt/ILGPU#214]
Hello! I am playing around with ILGPU to generate some geometry. I am implementing the marching cubes algorithm in ILGPU.

Basically in my kernel I know what the maximum number of triangles that **could** be returned, but most of the time its going to be a lot less. Each cube in the marching cubes algorithm can return 1 to 5 triangles. So I am creating an array that is size `NumberOfCubes * 5` and using a structure to determine if an element was set by my kernel.

This results in me allocating a lot more memory than I need, and when I return to C# I need to cull out the triangles that weren't set.

If I was doing this outside of the GPU, I would just use a List so that I could simply append new triangles to the end and finish with a list of only triangles I've generated. I've never written a compute shader before, but I believe many of them support this some how.

Is there any way to achieve a similar result with ILGPU, or maybe to use another kernel to remove all the unused structs?

I may be using ILGPU in a totally unintended way. 😁

**Comment by m4rs-mt** [comment]
@Delpire welcome to the ILGPU community. Your  task sounds like a perfect use case for applying a `stream-compaction` algorithm or implementing an unordered list with `atomic operations`.  A good starting point for implementing the MC algorithm on the GPU is this set of [slides](https://www.nvidia.com/content/gtc-2010/pdfs/gtc10_session2020_hp5mc_dyken_ziegler.pdf).

**Comment by m4rs-mt** [comment]
A very simple sample could look like this:
```c#
static void GenerateTrianglesKernel(..., VariableView<int> elementCounter, ...)
{
    // ...
    // Compute number of triangles to add
    // ...
    
    // Compute the next element offset
    int offset = Atomic.Add(ref elementCounter.Value, numberOfTriangles);
    // Add elements to the output buffer
    for (int i = 0; i < numberOfTriangles; ++i)
    {
        int targetIndex = offset + i;
        // Store triangle to target index
    }
}
```

**Comment by Delpire** [comment]
@m4rs-mt Thank you so much! That seems to be exactly what I needed and has sped up my performance quite significantly!

That slide deck is super interesting. I'm nowhere near their level of performance, but it is an interesting read. Thank you for sharing it.
