### ISSUE TITLE
Using LongIndex1 as a parameter to a kernel

### ISSUE THREAD

**Issue by hrioan** [m4rs-mt/ILGPU#218]
I am working on version 9.0 beta and I am trying to pass a LongIndex as the first parameter to my kernel. However I am getting the following runtime error: "An entry point must receive a compatible index type as first parameter".

Is there any reason why we can't do that? We can already use a long as an index to a buffer. I am currently splitting the long index and try to pass it as an Index2, then reconstruct it in the kernel - however this seems to have an impact on performance.

**Comment by m4rs-mt** [comment]
@hrioan Thank you for your issue report. It is currently not possible to use a `LongIndexX` as first parameter in the scope of implicitly grouped kernels. This is due to the case that current GPUs thread grids are limited to 32-bit indexes on all common GPU platforms anyway. However, implementing this feature requires additional backend code-generation extensions that we can add in one of the next commits.

**Comment by xxl-cc** [comment]
My kernel parameter type is  ArrayView<float> , and my index parameter is  ArrayView<float>.Extent . When I upgrade from 0.8.1 to 0.9, the same exception is thrown. Do I need to call the index conversion function ToIntIndex() explicitly?The workload is relatively large.

**Comment by m4rs-mt** [comment]
@xxl-cc This feature is currently not available. We have to think about a clever design to realize such an extension first. However, if you pass an extent of a `MemoryBuffer` or an `ArrayView` to a delegate kernel launcher, the cast will be automatically done for you. If you launch your kernel using an untyped launcher (like `myKernel.Launch(...)`) you have to convert the `LongIndexX` extent to an `IntIndex` first.

**Comment by m4rs-mt** [comment]
@xxl-cc We have added advanced support for working with 64-bit array views in the upcoming version of the Algorithms library (v1.0). This feature will allow you to let ILGPU algorithms scale appropriately based on their underlying implementation. From now on, you can implement grid-stride loops using the `IGridStrideKernelBody` interface to have them automatically scale to any number of elements.
