### ISSUE TITLE
How to avoid rounding the cast of 8bit to 32bit via struct property.

### ISSUE THREAD

**Issue by renpei-okada** [m4rs-mt/ILGPU#221]
Hi!
Thank you for providing a very useful and amazing revolutionary library in .NET !!

I have a question.
When accessing via the property, the cast of byte8 to float32 causes rounding.
It does not occur when accessing via the field.
I used Interop.IntAsFloat() and the result was the same.
When cpu backend, it does not  occur.
Via property, how should I avoid it ?

Windows 10 2004
.NET  core 3.1
ILGPU 0.8.1 PTX backend
RTX2070

```C#
[StructLayout(LayoutKind.Sequential, Size = 4)]
public struct Bgra32
{
    public byte b;
    public byte g;
    public byte r;
    public byte a;

    public byte B { get => b; set => b = value; }

    public byte G { get => g; set => g = value; }

    public byte R { get => r; set => r = value; }

    public byte A { get => a; set => a = value; }

    public Bgra32(byte b, byte g, byte r, byte a) : this()
    {
        this.B = b;
        this.G = g;
        this.R = r;
        this.A = a;
    }

    public override readonly string ToString() => $"Bgra32({b}, {g}, {r}, {a})";
}

static void Kernel1(Index1 i, ArrayView<Bgra32> arr1, ArrayView<Bgra32> arr2)
{
    float f0 = arr1[i].B; // 128
    float f1 = arr1[i].G; // 127
    float f2 = arr1[i].R; // 1
    float f3 = arr1[i].A; // 255

    arr2[i].B = (byte)f0;
    arr2[i].G = (byte)f1;
    arr2[i].R = (byte)f2;
    arr2[i].A = (byte)f3;

    // OUTPUT
    // arr[i].B ---> 0
    // arr[i].G ---> 127
    // arr[i].R ---> 1
    // arr[i].A ---> 0
}

static void Kernel2(Index1 i, ArrayView<Bgra32> arr1, ArrayView<Bgra32> arr2)
{
    float f0 = arr1[i].b; // 128
    float f1 = arr1[i].g; // 127
    float f2 = arr1[i].r; // 1
    float f3 = arr1[i].a; // 255

    arr2[i].B = (byte)f0;
    arr2[i].G = (byte)f1;
    arr2[i].R = (byte)f2;
    arr2[i].A = (byte)f3;

    // OUTPUT
    // arr[i].B ---> 128
    // arr[i].G ---> 127
    // arr[i].R ---> 1
    // arr[i].A ---> 255
}
```

**Comment by m4rs-mt** [comment]
@renpei-okada Thank your for submitting this issue and welcome to the ILGPU community. This looks interesting. I guess this might be related to the fact the `byte` value is converted to an `int` by default on the evaluation stack in .Net before invoking the actual property accessor. I am going to investigate this in more detail 🤓

**Comment by m4rs-mt** [comment]
@renpei-okada we found the issue. It is related to an invalid emission of signed/unsigned conversion instructions. In your case, the emitted PTX instruction used to convert the bytes to float values in the first kernel is `cvt.rn.f32.s8`. However, it should be `cvt.rn.f32.u8`. We are going to provide a patch.
