### ISSUE TITLE
ILGPU.Algorithm corresponding to ILGPU 0.9-beta1

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#225]
Is Lib of ILGPU.Algorithm available corresponding to the latest ILGPU 0.9-beta1?

**Comment by m4rs-mt** [comment]
@toolwtech we are currently working on the next `Algorithms` library that is compatible with the latest beta release. However, there are some minor issues remaining (like #217).

**Comment by toolwtech** [comment]
@m4rs-mt looking forward to using the latest beta release.
