### ISSUE TITLE
Big structure makes ILGPU generate extremely huge kernel code

### ISSUE THREAD

**Issue by dvnguyen-uofa** [m4rs-mt/ILGPU#229]
When my kernel having a structure like this, it makes ILGPU generate a kernel source that has number of lines as much as twice the size of the structure in bytes.
`
unsafe struct MyBuffer
{
      public fixed Data[64*1024]
}
`

You might wonder why I have to create such a big structure. Well, since I can't use dynamic memory allocation in ILGPU kernel code, I use this variable to reserve a big chunk of memory in stack space. Then I take its address and use it freely in kernel.

I wish ArrayView provide a method so that I can take and use its address in kernel.

**Comment by MoFtZ** [comment]
@dvnguyen-uofa 
ILGPU v0.8.x added support for `linear arrays in local memory`.

This means that you can write a kernel that uses `new` to allocate a local array.

```CSharp
static void Kernel(Index1 index, ArrayView<int> output)
{
    var temp = new int[64 * 1024];

    // snip
}
```

Does this meet your requirements?

**Comment by MoFtZ** [comment]
FYI, I also tried `stackalloc`, but it looks like it's currently not supported.
```CSharp
static unsafe void StackAllocKernel(Index1 index, ArrayView<int> output)
{
    var temp = stackalloc int[64 * 1024];

    // snip
}

**Comment by dvnguyen-uofa** [comment]
It looks promising. However, I couldn't take the address of the array, e.g. `unsafe { fixed(int* pTemp = temp){ } }` would cause an Exception: "Not supported compare or arithmetic value of type 'None'" somewhere in CodeGenerator.MakeInstrinsicBranch. I will have to find a way to work around this.

**Comment by m4rs-mt** [comment]
@dvnguyen-uofa You cannot take the address of an array element currently using unsafe code (since this limits portability to other platforms). However, you can pass a reference to an array element to another function.

**Comment by m4rs-mt** [comment]
An alternative would be to provide a class `LocalMemory` that works similar to `SharedMemory`. Instead of returning an unsafe pointer, it can return an `ArrayView` that can be safely used in the scope of the whole kernel.

**Comment by dvnguyen-uofa** [comment]
I think it would be more powerful if we can get unsafe pointer of the buffer or ArrayViews. The reason is I have a piece of C++ code that heavily use pointers to manipulate data, and I am transforming it to work with ILGPU.

**Comment by m4rs-mt** [comment]
@dvnguyen-uofa Unsafe pointers are not more powerful than views and are not easily portable to other platforms. Moreover, views preserve a lot more domain knowledge that makes transformations and optimizations significantly easier. If you play around with views, you will recognize that they offer highly similar functionality and ensure a certain programming paradigm that abstracts from pointers while making the code easier to understand.

**Comment by dvnguyen-uofa** [comment]
I think you are right. I misused the term powerful in this case as I am too much familiar with using C++ pointers for manipulating data and so I have objective when learning another model.

I think your idea of providing the class LocalMemory will help cut down some works when porting C++ code to ILGPU. I will have a vote for it.

By the way, thank you for this library. It makes .NET become a lot stronger in GPU programming.

**Comment by Yey007** [comment]
I'm sure I'm missing something here, but why do we need a separate `LocalMemory` when `var temp = new int[64 * 1024];` works? I mean sure, it would give a more obvious way of allocating in local memory but I don't see an advantage besides that.

**Comment by dvnguyen-uofa** [comment]
Hi Yey007, although we can allocate an array of int with that statement. But lacking the capability of having a pointer to the buffer make it isn't usable for some sitution.

For example, if I do some calculation and then I want to iterate over the array as an array of bytes, or if I want to pass only a portion of the array to another function for calculation, then I will have to write a lot of code for doing that. Having a LocalMemory class with features of ArrayView can help a bit on it.

**Comment by MoFtZ** [comment]
@dvnguyen-uofa Have you tried using `Span<>` within the kernel? I'm not sure if it's supported by ILGPU, but it might give some of the behaviour you're interested in.

**Comment by dvnguyen-uofa** [comment]
No, It does not support inside a kernel. There is a throw statement somewhere inside the Span class and ILGPU doesn't support throw opcode.

**Comment by dvnguyen-uofa** [comment]
@MoFtZ : I wrote a struct Span by myself and it works. It doesn't solve the issue of accessing the array in a different element type though. The performance might not be good also. But anyway, this will solve my issue temporally. Thank for the ideas guys.
