### ISSUE TITLE
LowerArray transform is broken when a local array is not declaring at the beginning of a function

### ISSUE THREAD

**Issue by nguyenvuduc** [m4rs-mt/ILGPU#234]
Having a kernel like this will break the OpenCL backend compiler:
```
public static void test_local_array_kernel(Index1 index, int testParam)
{
            if (index == 1)
            {
                // sample block
            }

            var localArray = new byte[20];
            localArray[2] = 10;
}
```
It seems the `LowerArray::Lower` method is not able to find the block that contains the localArray and it is broken.

ILGPU 0.8.1.1

**Comment by MoFtZ** [comment]
@nguyenvuduc Thanks for reporting this issue.

This was [found recently](https://github.com/m4rs-mt/ILGPU/pull/191) and [fixed](https://github.com/m4rs-mt/ILGPU/issues/201) in ILGPU v0.9.0-beta1.

As a workaround, and as you mentioned, you can move the allocation to the start of the method. Alternatively, you should be able to downgrade to ILGPU v0.8.0.

**Comment by nguyenvuduc** [comment]
Thank you, I will close this issue.

Duplicate of #191
