### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'cublas64_10': 

### ISSUE THREAD

**Issue by LukePoga** [m4rs-mt/ILGPU#241]
Its said that we dont need to install cuda toolkit, just latest nvidia driver. but i have installed the latest Graphics Driver, and still get this error. Please fix your Getting Started if you actually need to install the toolkit!

System.DllNotFoundException: 'Unable to load DLL 'cublas64_10': 

And we are up to Cuda 11. Why is it trying to load Cuda 10? Please make these limitations clear so I can just use the product without running around for hours.

**Comment by LukePoga** [comment]
installed cuda 10.2 didnt work
installed cuda 10.0 and it finally worked. 

WHY ARE YOU SUPPORTING OLD CUDAs ONLY? I need CUDA 11 for turing core work. Its been out for a LONG TIME...

**Comment by MoFtZ** [comment]
@LukePoga The ILGPU community is a place of mutual respect and collaboration. Your recent interactions have not been of an appropriate standard, and I would ask that you conduct yourself in a polite and respectful manner.

With regards to your question on CuBlas, as you mentioned, it is currently only available for v10. As a community project, our resources are constrained, and it is, unfortunately, not possible to give priority to every feature.

I am personally not familiar with this section of the code, and CuBlas in general. Are there any API changes between v10 and v11?

If you have the time and inclination, we would welcome any contributions you can make to help improve this section of the code. In particular, the CuBlas integration exists in the ILGPU.Algorithms repository under [Src/ILGPU.Algorithms/Runtime/Cuda](https://github.com/m4rs-mt/ILGPU.Algorithms/tree/master/Src/ILGPU.Algorithms/Runtime/Cuda).

**Comment by m4rs-mt** [comment]
The issue you are describing seems to be related to the `CuBlas` interop offered by the `Algorithms` library. This part of the extension library (as indicated via the `CuBlas` class name) requires access to the native `CuBlas` library. The availability of this native library differs on different platforms and cannot be provided by ILGPU or its extension libraries.


*All* ILGPU functions and *most* of the Algorithms library (except the CuBlas interop) do not need to have access to any third-party SDKs and can be used on all .Net Core compatible platforms.

> And we are up to Cuda 11. Why is it trying to load Cuda 10?

Please note that we are currently working on an updated algorithm library to give you the best possible experience on the latest platforms. However, the latest ILGPU 0.9.X release is already fully compatible with the Nvidia Ampere series and Cuda 11-based drivers. An updated Algorithms library will be available within the near future.

**Comment by MoFtZ** [comment]
Looks like there were no API changes between cuBlas v10 and v11.

Also, not sure why v10.2 is failing, because it uses the same DLL name as v10.0. Maybe an issue with the search path?

**Comment by LukePoga** [comment]
Amazing thanks.

There are many optimisations for Ampere in v11.
