### ISSUE TITLE
Loop Unrolling

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#251]
ILGPU currently does not support loop unrolling in any form. We should add a new loop-unrolling transformation to aggressively unroll certain loops to improve performance. On the one hand, this will increase the overall size of the code, but on the other hand it will also significantly increase the potential for optimization (similar to inlining).

**Comment by Yey007** [comment]
Do you think this will be added only to O2 or Release/Debug as well?

**Comment by m4rs-mt** [comment]
@Yey007 I guess we should add this to the O2 pipeline first. Let's see whether we enable this in `Release` mode.
