### ISSUE TITLE
Synchronization issues with OpenCL

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#258]
When a memory copy is performed in Cuda, followed by a kernel launch, the two operations are performed sequentially.

In OpenCL, even though we are using an in-order queue, the kernel launch sometimes occurs before the memory copy has finished.

I noticed this behaviour in the past, and [this article](https://community.intel.com/t5/OpenCL/clEnqueueWriteBuffer-does-not-finish-before-Kernel/td-p/1077032) seems to confirm it:

> Intel Employee:
> You can get an event from each of the non-blocking clEnqueueWriteBuffer call and then wait for those events to complete prior to launching the kernel.
> Otherwise, you are asking for trouble, since non-blocking calls are not guaranteed to finish when you launch your kernel: you just lucked out with NVidia runtime.
> 

We should probably modify `CLStream` to track the last event, and use this when queuing subsequent commands.

**Comment by MoFtZ** [comment]
As per https://github.com/m4rs-mt/ILGPU/pull/246#issuecomment-689155307, maybe we can use one of the marker functions `clEnqueueMarkerWithWaitList` or `clEnqueueBarrierWithWaitList`?

Before (or after) adding a command to a queue, we add a marker. This will then provide sequential behaviour like CUDA without having to keep explicitly track the last event.

For example, we could add a marker to wait for previous commands to finish, then enqueue our own command that waits on the marker's event. Or we could add our command, then added a barrier marker, to ensure that subsequent commands cannot run until our initial command has completed..

One concern is that I'm unsure about the performance implications of adding markers.

**Comment by m4rs-mt** [comment]
@MoFtZ Sounds good to me. I guess the overall overhead can be assumed to be negligible. I made several experiments on different machines and did not encounter any significant slowdowns 🚀
