### ISSUE TITLE
Using three-dimensional data as a parameter, the speed difference of the same function is eight times

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#265]
public int coordinate2index(Int3 d)
        {
            return d.X * (n_crystal_x * n_crystal_y) + d.Z * n_crystal_x + d.Y;
        }
        public int coordinate2index(int m, int x, int y)
        {
            return m * (n_crystal_x * n_crystal_y) + y * n_crystal_x + x;
        }
Execute 200 million cycles, and the first function takes several times the execution time of the second function。

**Comment by m4rs-mt** [comment]
@xxl-cc Can you provide more information and a small sample program to reproduce this effect?

**Comment by xxl-cc** [comment]
public void Test2()
        {
            Stopwatch watch = new Stopwatch();
            watch.Start();
            int look = 200000000;

            Int3 d = new Int3(1, 2, 3);
            for (int i = 0; i < look; i++)
            {
                var t = coordinate2index(d);
            }

            watch.Stop();
            Console.WriteLine(watch.ElapsedMilliseconds);
            watch.Restart();

            for (int i = 0; i < look; i++)
            {
                var t = coordinate2index(1,2,3);
            }
            watch.Stop();
            Console.WriteLine(watch.ElapsedMilliseconds);
        }
        private int n_crystal_x = 3;
        private int n_crystal_y = 5;
        public int coordinate2index(Int3 d)
        {
            return d.X * (n_crystal_x * n_crystal_y) + d.Z * n_crystal_x + d.Y;
        }
        public int coordinate2index(int m, int x, int y)
        {
            return m * (n_crystal_x * n_crystal_y) + y * n_crystal_x + x;
        }

**Comment by m4rs-mt** [comment]
@xxl-cc It looks like you are executing the functions using the default .Net compilation pipeline, and not in the scope of an ILGPU kernel...?

**Comment by xxl-cc** [comment]
I took this function out on its own, and it was actually handled in my kernel

**Comment by m4rs-mt** [comment]
@xxl-cc Did you enable `AggressiveInlining`? It would be great if you could provide a simplified program that reproduces this issue. This significantly helps us to reproduce your findings 🤓
