### ISSUE TITLE
Does kernel function support tuple type？

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#266]

**Comment by MoFtZ** [comment]
hi @xxl-cc, ILGPU does not currently support tuple types (`System.ValueTuple`). The reason is because that struct is defined using `[StructLayout(LayoutKind.Auto)]`.

According to the .NET documentation:
> LayoutKind.Auto: The runtime automatically chooses an appropriate layout for the members of an object in unmanaged memory. Objects defined with this enumeration member cannot be exposed outside of managed code. Attempting to do so generates an exception.

As a replacement, you can use `ILGPU.Util.DataBlock`, or provide your own structures.
