### ISSUE TITLE
CopyTo performance

### ISSUE THREAD

**Issue by LTOctum** [m4rs-mt/ILGPU#28]
Hi @m4rs-mt,

I'm using your library to write an image operation method to convert different pixel formats (for example planar/interlaced to packed).

The conversion itself cost around 1ms (3840x2160 RGB image) but the CopyTo method takes around 15ms.
CopyFrom instead is also only around 1ms.

The code is converting each pixel with a simple kernel.
Using CudaAccelerator with Nvidia Quadro M2200.

Code snipped:
```
private ArrayPoolItem<byte> ConvertToBGR888xPacked(Image image, bool addAlphaChannel)
        {
            var size = image.Width * image.Height;
            var planarBufferSize = size * image.BytesPerPixel;
            var packedBufferSize = size * (addAlphaChannel ? image.BytesPerPixel + 1 : image.BytesPerPixel);

// ILGPU relevant code
            _lastInputBuffer8Bit.CopyFrom(image.GetData<byte>(), 0, 0, planarBufferSize);
            var sw = Stopwatch.StartNew();
            _kernelRGB888PlanarToBGR888xPacked(image.Width * image.Height, image.Width, image.Height, addAlphaChannel ? image.BytesPerPixel + 1 : image.BytesPerPixel, _lastInputBuffer8Bit.View, _lastOutputBuffer8Bit.View);
            _accelerator.Synchronize();
            sw.Stop();
            Console.WriteLine($"Sync: {sw.ElapsedMilliseconds}");
            sw.Restart();
            var item = new ArrayPoolItem<byte>(packedBufferSize, _bytePool);
            _lastOutputBuffer8Bit.CopyTo(item.Value, 0, 0, packedBufferSize);
            sw.Stop();
            Console.WriteLine($"Copy: {sw.ElapsedMilliseconds}");
            return item;
        }
```
Is there any way to increase the performance of CopyTo?

Thanks in advance.

**Comment by m4rs-mt** [comment]
@LTOctum That sounds like an interesting problem. `CopyFrom` and `CopyTo` do not differ much in their functionality and are not known to cause significant overhead. I recommend allocating memory in advance with a `CPUAccelerator` instance for best performance. In this case, the memory buffer is allocated in native memory and the pointer is automatically pinned to reduce the time it takes to copy data to the CPU.
As far as I can see, you are using a managed memory buffer that causes a `GCHandle` to be allocated to pin the memory pointers. This can lead to significant runtime performance overhead. Furthermore, I recommend using `AcceleratorStream`s to perform async copy operations.

May be you can create a simplified example that reproduces this issue?

**Comment by LTOctum** [comment]
@m4rs-mt The way with the CPUAccelerator sounds interesting, do you have a code snipped how to use the buffer allocated by CPUAccelerator withing CudaAccelerator?

> var item = new ArrayPoolItem<byte>(packedBufferSize, _bytePool);
> _lastOutputBuffer8Bit.CopyTo(item.Value, 0, 0, packedBufferSize);

Is not using any GCHandle, it's just renting the same array from an pool (a quick optimization as LOH would fragmentate over time with arrays bigger then 85kb (the array has a size of ~34mb)).

The time is the same with:
> _lastOutputBuffer8Bit.GetAsArray()

I will provide you with an simplified example.

**Comment by LTOctum** [comment]
@m4rs-mt I did find the bottleneck in my code, but maybe it is still interesting for you.
If i use a new Array, the CopyTo (and also CopyFrom) method will take significant longer then expected (see the comment in the code).

Reusing the same buffer will cut the time from 11-15ms to 4-7ms.

```
using System;
using System.Diagnostics;
using System.Linq;
using ILGPU;
using ILGPU.Runtime;

namespace ilgpuTest
{
  class Program
  {
    private static Action<Index, int, int, int, ArrayView<byte>, ArrayView<byte>> _kernel;

    static void Main(string[] args)
    {
      var width = 3840;
      var height = 2160;
      var bytesPerPixel = 3;
      var pixels = width * height;
      var length = width * height * bytesPerPixel;
      var buffer = CreateBuffer(width, height, bytesPerPixel);
      var buffer2 = new byte[length];

      using (var context = new Context())
      {
        var cudaId = Accelerator.Accelerators.First(a => a.AcceleratorType.Equals(AcceleratorType.Cuda));
        using (var accelerator = Accelerator.Create(context, cudaId))
        {
          for (int x = 0; x < 10; x++)
          {
            _kernel = accelerator.LoadAutoGroupedStreamKernel<Index, int, int, int, ArrayView<byte>, ArrayView<byte>>(KernelMethod);
            var inputBuffer = accelerator.Allocate<byte>(length);
            var ouputBuffer = accelerator.Allocate<byte>(length);

            var swFrom = Stopwatch.StartNew();
            inputBuffer.CopyFrom(buffer, 0, 0, length);
            swFrom.Stop();
            Console.WriteLine($"{x} - CopyFrom: {swFrom.ElapsedMilliseconds}");
            _kernel(pixels, width, height, bytesPerPixel, inputBuffer.View, ouputBuffer.View);
            accelerator.Synchronize();
            var result = new byte[length];
            var swCopy = Stopwatch.StartNew();
            ouputBuffer.CopyTo(result, 0, 0, length);
            // ouputBuffer.CopyTo(buffer2, 0, 0, length); // Use this to increase the speed (only first run will be slow).
            swCopy.Stop();
            Console.WriteLine($"{x} - CopyTo: {swCopy.ElapsedMilliseconds}");
          }
        }
      }
    }

    private static void KernelMethod(Index pixelIndex, int width, int height, int bpp, ArrayView<byte> source, ArrayView<byte> destination)
    {
      var offset = width * height;
      var r = source[pixelIndex];
      var g = source[pixelIndex + offset];
      var b = source[pixelIndex + offset * 2];

      destination[pixelIndex * bpp] = b;
      destination[pixelIndex * bpp + 1] = g;
      destination[pixelIndex * bpp + 2] = r;
    }

    private static byte[] CreateBuffer(int width, int height, int bytesPerPixel)
    {
      var length = width * height * bytesPerPixel;
      var result = new byte[length];

      byte c = 0;
      for (var p = 0; p < length; p++)
      {
        result[p] = c++;
      }

      return result;
    }
  }
}
```
