### ISSUE TITLE
Allocated local memory on the GPU is uninitialized

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#287]
Within a kernel, if we allocate memory e.g. `var temp = new int[9];`, the contents of that array will be uninitialized. However, if we do that allocation on the CPU accelerator, it will be initialized to 0, as per the conventions of .NET.

This can make it difficult to debug issues, since it behaves differently on the GPU. Should we initialized the contents of the array?

**Comment by m4rs-mt** [comment]
Yes, you are right. I guess we should add initialization code for managed arrays by creating `ArraySetElement` values for each individual value in the IR for now. Alternatively, we could try to initialize the arrays in the different backends during final code generation.

**Comment by MoFtZ** [comment]
would it be easy to detect usage of the array before it is initialized? this would allow us to selectively initialize the array - only when it is used, and before a value is set.

**Comment by MoFtZ** [comment]
Sounds good 👍

**Comment by m4rs-mt** [comment]
@MoFtZ I am currently working on a newly designed `LocalMemory` class, as described above. However, I am also experimenting with removing all "explicit" array values from the IR. I guess, we can safely transform managed arrays into `ArrayView` values inside of the ILGPU IR and express all array operations using "default" pointer-based values. This makes the `LowerArrays` transformation obsolete and allows us to introduce a new transformation that optimizes local (and shared) memory accesses working on `ArrayView` values in a more convenient way.
