### ISSUE TITLE
Kernel compilation issue with OptimizationLevel.O2

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#292]
Hi,
The following test works with ILGPU 0.8.1.1, but not with ILGPU 0.9.1 when running with .net framework 4.8 in release mode:

    class ILGpuTest
    {
        [Test]
        public void CompilationTest()
        {
            using var context = new Context(ContextFlags.None, OptimizationLevel.O2);
            using var gpu = new CudaAccelerator(context, 0);
            var method = typeof(ILGpuTest).GetMethod(nameof(MyKernel), BindingFlags.NonPublic | BindingFlags.Static);
            var compiledKernel = gpu.Backend.Compile(EntryPointDescription.FromExplicitlyGroupedKernel(method), KernelSpecialization.Empty);
            Assert.NotNull(compiledKernel);
        }

        private static void MyKernel(ArrayView<int> gpu_array)
        {
            int j = 0;
            for (int i = 0; i < 2; i++)
            {
                j++;
                if (i == 1) break;
                j++;
            }
            gpu_array[0] = j;
        }
    }

**Comment by m4rs-mt** [comment]
@samy2 Thank you for submitting this issue report with a minimal example of how to reproduce this problem. I can reproduce this issue using the example provided. The problem seems to be related to the new `LoopUnrolling` transformation. I will take a closer look at it.

**Comment by samy2** [comment]
Thank you for the quick fix!
