### ISSUE TITLE
Regression in arithmetic simplications affecting ILGPU v0.9.2-beta1

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#296]
The changes in https://github.com/m4rs-mt/ILGPU/pull/283 has caused a regression in ILGPU.Algorithms.

For example, ILGPU.Algorithms.Tests.Cuda.CudaGroupExtensionTests_Debug.ExclusiveScanAdd fails with "an illegal memory access was encountered".

Looking at the PTX output, there's a one line difference.

Requires further investigation.

**Comment by MoFtZ** [comment]
It looks like the divide operation is being translated into a shift operation. Then, the shift operation and the subtraction operation are being incorrectly folded together.

Minimal example of the problem:
```CSharp
internal static void NestedBinaryKernel(Index1 index, ArrayView<int> data)
{
   data[index] = (index / 32) - 1;
}
```

**Comment by m4rs-mt** [comment]
I am going to have a closer look 👀

**Comment by MoFtZ** [comment]
My initial thoughts are that this is related to [Operator Precedence](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence). The shift operator and the addition operator are of different precedence, and so one must occur separately to the other.

I'm also assuming that the C# compiler should have already dealt with reordering the operators, so that the operations on the MSIL stack are correctly ordered. This should mean we only need to check if the two binary operators are of the same precedence, if so, then we can combine them.
