### ISSUE TITLE
Act of a cpu and a accelerator differs (may be bug)

### ISSUE THREAD

**Issue by sohaspaces** [m4rs-mt/ILGPU#301]
I think this library really great, but this code using the library prints result which doesn't make sense.
```c#
using System;
using System.Linq;
using System.Runtime.InteropServices;
using ILGPU;
using ILGPU.Runtime;

namespace ILGPUTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var accelerator = Accelerator.Create(new Context(), Accelerator.Accelerators.FirstOrDefault((x) => x.AcceleratorType == AcceleratorType.Cuda));
            
            var gpu = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<float>, MyStruct>(Gpu);
            var view = accelerator.Allocate<float>(1);

            var v = new MyStruct() { x = 255 };


            gpu(new Index1(1), view, v);
            view.CopyTo(out var gpuResult, new LongIndex1(0));
            Console.WriteLine(gpuResult);

            Cpu(out var cpuResult, v);
            Console.WriteLine(cpuResult);
        }
        static void Cpu(out float output, MyStruct input)
        {
            output = input.x;
        }
        static void Gpu(Index1 index, ArrayView<float> output, MyStruct input)
        {
            output[0] = input.x;
        }

    }

    public struct MyStruct
    {
        public byte x;
    }
}
```

Obviously, the method gpu (Compiled for CUDA by using Acclerator.LoadAutoGroupedStreamKernel) and Cpu is supposed to act the same as each other except for memory to write the result on.
But the result of the first one (=-1) and the second one(=255) differs.

The value of the field x of the input is 255, so the result must be 255 though it was cast as float (System.Single).

But it can be -1 if the byte value is cast as sbyte (because of 0xFF is 255 in byte, and -1 in sbyte).
And i guess it is clue to solve this bug

**Comment by sohaspaces** [comment]
I found the fact that the problem doesn't occur when the type of accelerator is AcceleratorType.CPU.
I didn't test the case of AcceleratorType.OpenCL because My graphic card is NVIDIA that doesn't support OpenCL.
But I think this can help to fix the problem by reducing the range in which the problem occurs.

**Comment by m4rs-mt** [comment]
@sohaspaces Thank you for submitting this issue and welcome to the ILGPU community. A small hint: Instead of writing
```c#
Accelerator.Create(new Context(), Accelerator.Accelerators.FirstOrDefault((x) => x.AcceleratorType == AcceleratorType.Cuda));
```
you can also use
```c#
new CudaAccelerator(context);
```
which will automatically picks the main Cuda accelerator for you.

Regarding your issue: I am able to reproduce this problem with the latest version of ILGPU. This problem seems to be related to #221, which also involved unsigned int8 (`byte`) types. A proper workaround for the moment would be to use `short` or `int` types to avoid this issue.

**Comment by sohaspaces** [comment]
```c#
using System;
using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;

namespace ILGPUTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var accelerator = new CudaAccelerator(new Context());
            var gpu = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<float>, MyStruct>(Gpu);
            var view = accelerator.Allocate<float>(1);
            var v = new MyStruct() { x = ushort.MaxValue };


            gpu(new Index1(1), view, v);
            view.CopyTo(out var gpuResult, new Index1(0));
            Console.WriteLine(gpuResult);

            Cpu(out var cpuResult, v);
            Console.WriteLine(cpuResult);
        }

        static void Cpu(out float output, MyStruct input)
        {
            output = input.x;
        }

        static void Gpu(ILGPU.Index1 index, ArrayView<float> output, MyStruct input)
        {
            output[0] = input.x;
        }

    }

    public struct MyStruct
    {
        public ushort x;
    }
}

```
In this code, the same phenomenon occurs. (byte became ushort, 255 became ushort.MaxValue, nothing else changed).
But it doesn't occur in case of uint and ulong.

**Comment by sohaspaces** [comment]
Upgrading to the lasted version you uploaded today (based on my time zone) also fixes this issue!
Thanks!

**Comment by sohaspaces** [comment]
The issue doesn't occur when I assign the field x to a local variable and assign the local variable to the view.
The issue also doesn't occur when I pass the value by not using MyStruct, but ushort type directly.
Furthermore, the issue also doesn't occur when I alternate the field x with a property.
Knowing these facts makes more easier to avoid this issue, but still, It is a bug that should be fixed.
