### ISSUE TITLE
Regression in ILGPU.Algorithms XMath unit tests from Aggresive Inlining

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#308]
With the changes in ILGPU for [aggressive inlining](https://github.com/m4rs-mt/ILGPU/pull/294), and after updating ILGPU.Algorithms to use [ILGPU v0.9.2-beta1](https://github.com/m4rs-mt/ILGPU.Algorithms/pull/62), some XMath unit tests are failing.

Reverting just the aggressive inlining commit in ILGPU will avoid the issue.

Further investigation required.

**Comment by m4rs-mt** [comment]
Can we mark them with `[MethodImpl(MethodImplOptions.NoInlining)]`? Does this circumvent the problem?

**Comment by MoFtZ** [comment]
Looks like it's affecting `XMath.Cordic.Exp(double)`, and any method that uses it (e.g. Cosh).

@m4rs-mt Yes, added NoInlining to the method fixes the issue. I will make the necessary changes to https://github.com/m4rs-mt/ILGPU.Algorithms/pull/62.

The original call stack during the crash was triggering `AssertNoControlFlowUpdate`. Looks like this occurred because the `Exp` calls itself again for some input values.
