### ISSUE TITLE
[0.9.2-beta1] PTXInstructionSet.ISA_71 missing from PTXCodeGenerator.SupportedInstructionSets

### ISSUE THREAD

**Issue by deng0** [m4rs-mt/ILGPU#309]
It seems it was forgotten to add PTXInstructionSet.ISA_71 to PTXCodeGenerator.SupportedInstructionSets.

**Comment by deng0** [comment]
hmm... not sure if that is related: 
After I added ISA_71 to SupportedInstructionSets I was able to compile and run a CUDA kernel on the Ampere GPU.
But for another kernel I get the following exception, when trying to compile the kernel:
```
System.MissingMethodException: Method not found: 'System.String ILGPU.Backends.PTX.PTXInstructions.GetArithmeticOperation(ILGPU.IR.Values.UnaryArithmeticKind, ILGPU.ArithmeticBasicValueType, Boolean)'.]
   bei ILGPU.Algorithms.PTX.PTXMath.GenerateMathIntrinsic(PTXBackend backend, PTXCodeGenerator codeGenerator, Value value)
   bei ILGPU.Backends.PTX.PTXCodeGenerator.GenerateCodeInternal(Int32 registerOffset)
   bei ILGPU.Backends.PTX.PTXKernelFunctionGenerator.GenerateCode()
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

**Comment by MoFtZ** [comment]
@deng0 Thanks for reporting the issues.

It looks like I missed that the new sm_86 architecture is only supported by the 7.1 instruction set. As you said, we'll need to add 7.1 to the supported instruction sets.

Regarding your second issue, this is affecting the ILGPU.Algorithms library. There is a breaking change in the API, which requires some minor changes - see https://github.com/m4rs-mt/ILGPU.Algorithms/pull/62

**Comment by m4rs-mt** [comment]
@deng0 @MoFtZ As you said, sm_86 requires the 7.1 ISA on the one hand. On the other hand, the A100 GPUs were completely compatible with the 7.0 ISA.
