### ISSUE TITLE
After the screen is closed automatically, GPU calculation is abnormal

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#318]
I set no action and then turn off the screen after 10 minutes. When the computer is activated again, the GPU calculation is stopped and throw  Unknown exception， the GPU occupancy in the task manager is zero. I am sure that the computing task has not been completed.

**Comment by m4rs-mt** [comment]
@xxl-cc thank you for your issue report. This problem sounds like it is directly/indirectly related to the GPU driver that seems to invalidate (parts of?) the context. I am not sure what we can do to circumvent the problem 🤔 any Ideas?

**Comment by m4rs-mt** [comment]
Closed for the time being due to inactivity
