### ISSUE TITLE
How to generate random numbers on GPU?

### ISSUE THREAD

**Issue by mast3rm1nd** [m4rs-mt/ILGPU#325]
Is there any way to to generate random numbers on GPU?
Currently I'm pre-generating array of XorShift128Plus and passing it to GPU, different thread uses it's own instance of XorShift128Plus. All of this almost doubled my calculation times after I discovered that using same static XorShift128Plus results in same random over all threads, but it works now.
Thank you.

**Comment by MoFtZ** [comment]
@mast3rm1nd do you have any specific requirements for your random numbers? uniform distribution? 32-bit? 64-bit? etc.

I'm not particularly familiar with the topic, but I found this comment about ["jumping"](https://en.wikipedia.org/wiki/Xorshift#Other_variants) in Wikipedia interesting. You initialize the RNG with a seed, and then get each thread to "jump" a different amount, and therefore they get a different starting point.

Alternatively, could you use a first RNG to seed a second RNG? For example:
- Create a single, static XorShift128Plus instance,
- Get each thread to use this RNG instance to get a different random value,
    - Thread #1 gets the first random value,
    - Thread #2 gets the second random value (calls Next() twice, or jump to 2nd value).
    - Thread #X gets the x-th random value, etc.
- Then, each thread uses their random value to seed a second RNG.

**Comment by mast3rm1nd** [comment]
I need uniformly distributed  doubles between 0 and 1
Just tried, "jumping" variant takes even more time (I'm spawning 2 million threads)
It would be great if you implement native RNG if it's possible.
Anyway, thank you for such operative reply = )

**Comment by m4rs-mt** [comment]
@mast3rm1nd Thank you for your issue report. As @MoFtZ outlined, there is currently "not native RNG" support in ILGPU or one of its libraries. Alternatively, you can use the .Net `Random` class to generate the initial seeds for the `XorShift128Plus` instances (use `XorShift128Plus.Create(random)` and copy them into your GPU buffer. Afterwards, you can use each individual `XorShift128Plus` instance locally within each thread (however, don't forget to write the state of the RNG back to global memory 😄).

**Comment by MoFtZ** [comment]
@mast3rm1nd With your initial working application that generates random numbers, do you know what is causing the performance hit?

If it's generating the initial XorShift128Plus instances on the CPU, maybe you could try [generating it in parallel] (https://devblogs.microsoft.com/pfxteam/getting-random-numbers-in-a-thread-safe-way/).

**Comment by mast3rm1nd** [comment]
Already did parallel generation\processing of  input\output data, and it indeed helped greatly.
So currently weakest spots is need in large amount of GPU memory and pre\post-processing by CPU.

**Comment by MoFtZ** [comment]
When spawning your 2 million threads, how many instances of XorShift128Plus are you creating? Are you able you reduce the number of instances by sharing them between groups?

Also, with the "jumping", these RNGs appear better suited (https://en.m.wikipedia.org/wiki/Counter-based_random_number_generator_(CBRNG).

**Comment by mast3rm1nd** [comment]
I'm creating 2 mln instances of XorShift128Plus
Pre-calculating and allocating all my stuff takes ~0.7 second
Everything regarding GPU performance is great, thank you : )
