### ISSUE TITLE
Performance profiler (question)

### ISSUE THREAD

**Issue by sohaspaces** [m4rs-mt/ILGPU#332]
Is there something like a performance profiler that can analyzes codes that executed in an accelerator such as GPU?

**Comment by m4rs-mt** [comment]
@sohaspaces Thank you for your question and welcome to the ILGPU community 🤓 ILGPU is compatible with the NVIDIA Performance Analysis tools like [Nsight](https://developer.nvidia.com/nsight-visual-studio-edition).
