### ISSUE TITLE
CudaException: invalid argument in LoadImplicitlyGroupedStreamKernel()()

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#341]
Hi there! First, thank you for this library. It's extremely useful.

I have an issue with a simple reproduction. The short summary is that kernels loaded using LoadImplicitlyGroupedStreamKernel have some surprising limits on the parameters they can be called with. If the parameter:

- Is either an Index2 or an Index3, and
   - Has an entry other than X that's at least 2^16, we get ILGPU.Runtime.Cuda.CudaException: invalid argument.
   - Otherwise, if the product of its entries is at least 2^38, we get System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'gridDim')

Test code:
```
using var context = new Context(ILGPU.IR.Transformations.OptimizationLevel.Release);
using var gpu = new CudaAccelerator(context);
void TestKernel1D(Index1 index, int a) { };
void TestKernel2D(Index2 index, int a) { };
void TestKernel3D(Index3 index, int a) { };
var TK1 = gpu.LoadImplicitlyGroupedStreamKernel<Index1, int>(TestKernel1D, 64 * 2);
var TK2 = gpu.LoadImplicitlyGroupedStreamKernel<Index2, int>(TestKernel2D, 64 * 2);
var TK3 = gpu.LoadImplicitlyGroupedStreamKernel<Index3, int>(TestKernel3D, 64 * 2);
TK1(new Index1(1 << 30), 5);           // OK
TK2(new Index2(1 << 30, 1 << 7), 5);   // OK
TK2(new Index2(1, 1 << 16), 5);        // Second index over 2^16: CudaException
TK2(new Index2(1 << 30, 1 << 8), 5);   // Index product over 2^38: ArgumentOutOfRangeException
TK2(new Index2(1 << 30, 1 << 16), 5);  // Both problems: CudaException
TK3(new Index3(1 << 30, 1, 1), 5);     // OK
TK3(new Index3(1, 1 << 16, 1), 5);     // Second index over 2^16: CudaException
TK3(new Index3(1, 1, 1 << 16), 5);     // Third index over 2^16: CudaException
TK3(new Index3(1 << 30, 1 << 3, 1 << 3), 5);  // OK
TK3(new Index3(1 << 30, 1 << 4, 1 << 4), 5);  // Index product over 2^38: ArgumentOutOfRangeException
```

If these are limits that exist outside of your library, I suggest adding searchable documentation that explains the problems. I couldn't find any posts or documentation about this online, though I guess that's what this bug report could help with now.

**Comment by Ruberik** [comment]
The CudaException also appears to occur when I use an index such as those described above to retrieve an entry in an ArrayView2D.

**Comment by MoFtZ** [comment]
@Ruberik it looks like you are running into the limits of the grid size on the Cuda accelerator.

These are detailed in the Cuda [Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications) and [Wikipedia](https://en.wikipedia.org/wiki/CUDA#Version_features_and_specifications).

`Maximum x-dimension of a grid of thread blocks = 2^31-1`
`Maximum y- or z-dimension of a grid of thread blocks = 65535`

At runtime, you can use the `MaxGridSize` property of the `CudaAccelerator` to determine the limits.

**Comment by Ruberik** [comment]
@MoFtZ Thanks for pointing that out! So when someone calls a function loaded with LoadImplicitlyGroupedStreamKernel, it looks like there's a way to check whether they're calling it with a valid parameter, and give a useful error message. Is there a way to tag this thread as a feature request?

**Comment by m4rs-mt** [comment]
@Ruberik Sounds good to me. Better error messages are always a good idea, and I think this is the perfect place to provide better (and consistent) error messages.
