### ISSUE TITLE
Cuda vs CPU different results

### ISSUE THREAD

**Issue by CsabaStupak** [m4rs-mt/ILGPU#356]
I'm playing with the library, trying to write my own reducer. My input array is `[4,1,0]` and it should return `sum = 5`. It works fine for _CPU_ but works incorrectly for _Cuda_ - it returns `sum = 4`. I know that the algorithm library has such _sum_ reducer already. However I need to implement more complicated reducer algorithms so I started with such simple.

The code is:

```
var kernelSum = accelerator.LoadStreamKernel<
     ArrayView<float>, ArrayView<float>, float>(
     KernelSum);

var memConfig = SharedMemoryConfig.RequestDynamic<float>(2);

kernelSum((1, 2, memConfig), src, trg, 1f);

private static void KernelSum(
	ArrayView<float> src, ArrayView<float> trg, float fScale)
{
	// 1st reduction of the large input array
	int nPos = Group.IdxX;
	int nStride = Group.DimX;

	float fReduce = 0;
	for (var ndx = nPos; ndx < src.Length; ndx += nStride)
		fReduce += src[ndx];

	var dynMem = SharedMemory.GetDynamic<float>();
	dynMem[nPos] = fReduce;

	// The result dynamic memory can be large
	// Each thread will reduce two items from the dynamic memory
	int nDynLng = (int)dynMem.Length;
	for (nStride = nDynLng; nStride > 1; )
	{
		Group.Barrier();

		nDynLng = nStride;
		nStride = (nStride + 1) / 2;

		if (nPos + nStride < nDynLng)
			dynMem[nPos] += dynMem[nPos + nStride];
	}

	Group.Barrier();

	// Reduction finished, let the 1st thread write the result
	if (Group.IsFirstThread)
		trg[0] = fScale * dynMem[0];
}
```

Not sure if there is a bug in my code or something is wrong in the IGL library Cuda part. I debugged the code using _CPU_ accelerator and it looked fine. I did not try with _Cuda_ however.

Maybe this issue is related to algorithm issue I reported:
#https://github.com/m4rs-mt/ILGPU.Algorithms/issues/68

Thanks for any advice :-)

**Comment by MoFtZ** [comment]
@CsabaStupak I have not run the code, just a visual inspection, but the potential issue that stands out to me is the following code:

```CSharp
	// The result dynamic memory can be large
	// Each thread will reduce two items from the dynamic memory
	int nDynLng = (int)dynMem.Length;
	for (nStride = nDynLng; nStride > 1; )
	{
		Group.Barrier();

		nDynLng = nStride;
		nStride = (nStride + 1) / 2;

		if (nPos + nStride < nDynLng)
			dynMem[nPos] += dynMem[nPos + nStride];
	}
```
At the end of the for loop, you are updating the SharedMemory buffer `dynMem`. There is a potential issue here because the SharedMemory buffer is shared between all the threads of a group, and you are reading/writing the buffer across multiple threads without any thread-safety.

**Comment by CsabaStupak** [comment]
The synchronization should be OK, since I'm calling `Group.Barrier()` and during the thread execution they do not touch any data of other threads from the `dynMem`.

It looks like the `for `cycle is incorrectly translated - note I do not use the 3rd expression in the `for`. Everything starts to work if I replace it to while `cycle`:

```
int nPos = Group.IdxX;
var dynMem = SharedMemory.GetDynamic<float>();

// 1st reduction of the large input array
int nStride = Group.DimX;
float fReduce = 0;
for (var ndx = nPos; ndx < src.Length; ndx += nStride)
	fReduce += src[ndx];

dynMem[nPos] = fReduce;

// The result dynamic memory can be large
// Each thread will reduce two items from the dynamic memory
int nDynLng;
while (nStride > 1)
{
	Group.Barrier();

	nDynLng = nStride;
	nStride = (nStride + 1) / 2;

	if (nPos + nStride < nDynLng)
		dynMem[nPos] += dynMem[nPos + nStride];
}

Group.Barrier();

// Reduction finished, let the 1st thread write the result
if (Group.IsFirstThread)
	trg[0] = fScale * dynMem[0];
```

**Comment by MoFtZ** [comment]
@CsabaStupak I noticed a difference between the for-loop and while-loop implementations.

The first expression of the for loop sets `nStride = nDynLng`, but the while-loop implementation does not do this step. When I remove that first expression from the for-loop implementation, the kernel will generate the correct result.

It looks like calling `Length` on the shared memory buffer returns -1, maybe because it's dynamic.
