### ISSUE TITLE
List of MemoryBuffer2D<float> to kernel

### ISSUE THREAD

**Issue by CsabaStupak** [m4rs-mt/ILGPU#359]
I'm trying to write a kernel which processes a list of `MemoryBuffer2D<float>`. Unfortunately I don't know how to create such kernel which would have `List<MemoryBuffer2D<float>>` or _array_ of `MemoryBuffer2D<float>[]`. 

As a workround I could create a `MemoryBuffer3D<float>`, in a cycle copy the list of `MemoryBuffer2D<float>` content to this 3D buffer, then process the 3D buffer and distribute the result to 2D buffers, but this adds another performance hit.

Thanks for advice :-)

**Comment by m4rs-mt** [comment]
@CsabaStupak Unfortunately, it is not possible to pass an array of `ArrayView<T>` elements to a kernel (and it is also not possible to create an `ArrayView` of another `ArrayView<T>` like `ArrayView<ArrayView<T>>`). However, what you can do is to use a single 3D memory buffer or you could generate a compile-time accessible structure using a maximum number of array views in parameter space. Maybe we should add additional support to fixed array buffers to include support for nested `ArrayView` elements or provide an additional `ConstantMemory` API to explicitly store data into the constant-memory module on the GPU device.

**Comment by CsabaStupak** [comment]
That would be a nice to have feature. Currently not so important however - I'm redesigning my code to work with 3D memory buffer. This approach will save some GPU memory and will improve the performance of my code.
Thanks :-)
