### ISSUE TITLE
How to perform image effects (like brightness, contrast,blur,displace) on GPU for manu amount of mages

### ISSUE THREAD

**Issue by Aleksey1555** [m4rs-mt/ILGPU#365]
Hello.
I have ove 3 000 000 images and i need tool to perform about 4 effects (Brightness, Contrast, Displacement, JPEG -convertion
And i need fastes library to do this.
Please help!
P.S. i can write some effect on ILGPU, but maybe there is special libraries for this?

**Comment by m4rs-mt** [comment]
@Aleksey1555 Of course you can use ILGPU in combination with multiple kernels. However, you can also use one of the available libraries like [OpenCV}(https://opencv.org/platforms/cuda/) which offer GPU acceleration for a set of predefined filters.

**Comment by Aleksey1555** [comment]
@m4rs-mt , Thanks
