### ISSUE TITLE
Allocate<float>(new LongIndex2(x, y)) fails if x*y does not fit into int

### ISSUE THREAD

**Issue by yuryGotham** [m4rs-mt/ILGPU#366]
long x = 69;
                    long y = 31527848;
                    Console.WriteLine("Trying to allocate " + (x * y).ToString("0,000") + " floats on GPU");
                    Console.WriteLine("2^31: " + ((long)1 << 31).ToString("0,000"));

                    //var result = gpu.Allocate<float>(new LongIndex2(x, y));
                    // the above throws an exception:
                    //Trying to allocate 2,175,421,512 floats on GPU
                    //2^31: 2,147,483,648
                    //Process terminated.Assertion Failed
                    //32-bit index out of range
                    //at ILGPU.ArrayView2D`1..ctor(ArrayView`2 baseView)
                    //at ILGPU.ArrayView2D`1.op_Implicit(ArrayView`2 baseView)
                    //at ILGPU.Runtime.MemoryBuffer2D`1..ctor(MemoryBuffer`2 buffer)
                    //at ILGPU.Runtime.Accelerator.Allocate[T](LongIndex2 extent)

                    var result = gpu.Allocate<float>(x * y); // this works just fine

**Comment by m4rs-mt** [comment]
@yuryGotham Thank you for your issue report. I was able to reproduce the problem using the sample code provided. The issue is related to an invalid assertion check that "wants to ensure" that multidimensional views have a total length of `int.MaxValue` ([this line](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/ArrayViews.tt#L82) causes the issue).

**Comment by yuryGotham** [comment]
I guess the bigger question that I have is weather the indexing will work fine during the runtime in the GPU.
Let's say I have a view with dimension Index2(8, 1024 * 1024 * 1024) - approximately 8 billion.

What will happen in the GPU when I access view[7, 1024 * 1024 * 1024 - 1]? Will it just overflow? Will it do int64 math and become slow? Or will it do something smart to address that memory location correctly and efficiently using int32 only?

**Comment by m4rs-mt** [comment]
All addresses on a 64-bit GPU system will be represented using 64-bit addresses under the hood. The only difference between the accesses is whether you use a 32-bit or a 64-bit offset. ILGPU differentiates between both scenarios: it uses 32-bit integer math in the case of 32-bit offsets in your program and 64-bit integer math to compute the offsets in the 64-bit world. However, the actual address computation uses 64-bit integer math.

In the case of 32-bit offsets it uses sequences like:
```asm
mul.wide.u32 %rd4, %r1, 4;
add.u64      %rd3, %rd1, %rd4;
```
where `r1` is the 32-bit offset computed in your kernel program, `4` is the constant size in bytes of your access (an integer in this case) and `rd1` is the source buffer address in your GPU memory in a 64-bit register. However, if the offset is a 64-bit integer, ILGPU uses an efficient multiply-add operation working on 64-bit integers like:
```asm
mad.lo.u64    %rd4, %rd3, 4, %rd1;
```

> What will happen in the GPU when I access view[7, 1024 * 1024 * 1024 - 1]? Will it just overflow? Will it do int64 math and become slow? 

When accessing views using 32-bit indices, the resulting index operation will be performed on 32-bit offsets for performance reasons. As a result, this operation can overflow, like in your example. If you already know, that your offsets will not fit into a 32-bit integer, you have to use 64-bit offsets in your kernel.

> Will it do int64 math and become slow?

If you are using 64-bit offsets, the emitted indexing operating will be slightly more expensive in terms of register usage and computational overhead (at least conceptually). The actual runtime difference depends on your kernel program 🤓.

> Or will it do something smart to address that memory location correctly and efficiently using int32 only?

There is no magic in the compiler that is able to determine whether a value could potentially overflow at some point at runtime. Please note that such magic would require additional static program analyses to compute safe upper bounds for all values. This over approximation can easily lead to performance penalties in general.

**Comment by yuryGotham** [comment]
@m4rs-mt Thank you for the explanation!

Please correct me if I misunderstood, but all I have to do if I want to avoid overflow is to cast the indices to long when referring to the views that have more than 2^31 elements. I converted my program to use long in such cases and there is minimal performance penalty (the program is still mostly memory bandwidth bound).

When do you expect to release ILGPU nuget that removes the invalid assertion check?

**Comment by m4rs-mt** [comment]
> Please correct me if I misunderstood, but all I have to do if I want to avoid overflow is to cast the indices to long when referring to the views that have more than 2^31 elements. I converted my program to use long in such cases and there is minimal performance penalty (the program is still mostly memory bandwidth bound).

That's right 👍  The only thing you need to do is to convert your 32-bit index into a 64-bit index explicitly and it will just work.
The next version `v0.10.0-beta2` should be available in the scope of the next two weeks. This will also contain a fix for the assertion check.
