### ISSUE TITLE
Repository tags

### ISSUE THREAD

**Issue by sohaspaces** [m4rs-mt/ILGPU#368]
This repository has no tags. It makes it hard to find this repository for people who don't know this.
I suggest adding tags like GPU, compiler, dotnet to this repository to promote this project to many people who need it.

**Comment by m4rs-mt** [comment]
@sohaspaces Good idea! I will add in some Github topics to the repository 🤓. I was thinking about `GPU`, `compiler`, `dotnet`, `IL`, `PTX`, `NVIDIA`, `AMD`, `OpenCL`, `Cuda`, `Jit`...
