### ISSUE TITLE
Project 1 generates "Cuda is not supported on this platform" error.  Project 2 doesn't, on the same system.

### ISSUE THREAD

**Issue by Costigan** [m4rs-mt/ILGPU#369]
I'm getting this error when trying to create a Cuda accelerator: "Cuda is not supported on this platform".  I have a different project in the same solution where the same code (text) successfully creates the accelerator.  Same laptop.  Same NVIDIA card.  Run within 10s of seconds of each other.  Both are console projects, although the one that works is a windows forms application.  (I run it as a console application to have Console.Out.)  In that application, the main window gets created before trying to create the CudaAccelerator.  I have an NVIDIA Quadro M3000M running Cuda Driver 10.1.  I don't know what other info is relevant nor how to get it.

            using (var context = new Context())
            using (var acc1 = new CudaAccelerator(context))
            {
                context.EnableAlgorithms();
                ...
            }

In the solution where it fails, Accelerator.Accelerators contains only the CPU accelerator.  In the one where it succeeds, both the CPU and Cuda accelerators are listed.

Under what circumstances does a Cuda Accelerator fail to get created?

(I tried to work it out for myself by downloading and trying to compile ILGPU so that I could add its source to my solution, but it doesn't compile.  I believe the problem is related to the code analyzers.  My copy of visual studio has started to act strangely recently, so I don't think there's any problem with ILGPU.  I just mention this to say that that avenue for figuring out what's going on is currently blocked.)

**Comment by m4rs-mt** [comment]
@Costigan This sounds really strange and should definitely not happen 😟. The Cuda Accelerator can fail to get created if the native driver library could not be loaded (for whatever reason...). Can you check whether both projects will be executed in 64-bit mode (assuming that your OS platform is a 64-bit OS 😄)?

Regarding the compilation issues: are you using the `net50` SDK to compile ILGPU? We have already seen that there are a several program analysis warnings that are currently treated like errors during the compilation process.

**Comment by Costigan** [comment]
I am embarrassed.  That is, of course, relevant, and I should have included that info in the previous message.  If I had, I probably would have found the problem.  I had the solution platform set to Debug x64 but the build platforms for the two projects were different.  The one that failed to create the accelerator was set to Any CPU.  (The prefer 32 bit checkbox was unchecked and, for some reason, disabled.)  I thought running on the 64-bit CLR was enough, although the documentation does say to uncheck that checkbox.

I think my issue simplifies to 'could the error message be improved in this case?'

Regarding building ILGPU (so I could single-step through the attempt to create the CudaAccelerator, I'm using Visual Studio 16.8.3, so I believe I am using the net50 SDK.  I've also seen analyzers treat issues that were warnings as errors.  I don't understand why and have tried disabling the analyzers in the project code analysis property sheet and changing the RunAnalyzers property in the csproj.  I'm still getting lots of errors when compiling the ILGPU project, and some are curious.  For instance, LongIndex1 isn't defined.  It's definitely defined in the nuget package I'm using.  What I'm trying to compile is a downloaded the .zip of the 0.9.1 tag.  I unloaded the test projects to focus on ILGPU.  I also needed to switch from net47 to net48 because it wasn't finding files at some explicit paths, and I opened and saved each of the text templates.

Searching for LongIndex1 yields 47 hits, but none are its definition.  It has to be somewhere, but I'm not finding it.   So I'm unsure whether the problem is the analyzers or the zip archive.  I don't doubt that there's some issue with my environment, but I don't know how to track that down at the moment.

**Comment by m4rs-mt** [comment]
> The prefer 32 bit checkbox was unchecked and, for some reason, disabled.) I thought running on the 64-bit CLR was enough, although the documentation does say to uncheck that checkbox.

I have never experienced any problems regarding the checkbox and `AnyCPU` builds on any platform. I am also wondering why the checkbox has been disabled in your solution. Are you accidentally building for a specific target platform in the `Configuration Manager`?

> I think my issue simplifies to 'could the error message be improved in this case?'

Makes sense to me. There is already support in ILGPU to test for a valid "bitness" of the current runtime system. Maybe we should add an additional check to the individual Cuda/OpenCL accelerator constructors that verifies whether the current application is compatible with the bitness of the host system. If not, we can immediately throw an exception.

> Searching for LongIndex1 yields 47 hits, but none are its definition.

Hm... are you really sure that you have translated all T4 templates in the beginning properly? The zip file contains Unix line endings that sometimes cause the T4 template engines to fail. However, this should not happen since we have additional line-ending checks in CI.
