### ISSUE TITLE
Different exception thrown in different graphic cards

### ISSUE THREAD

**Issue by AnakinCN** [m4rs-mt/ILGPU#382]
Hi

I tried writing a sample using structures with ILGPU, and it throws different in  different graphic cards (OpenCL & CUDA), none succeeded.

I believe is something with my code, but how to debug this? There's no detailed information on the exception.

[BlackILGPUnoClass.zip](https://github.com/m4rs-mt/ILGPU/files/5801038/BlackILGPUnoClass.zip)

Thank you in advance.

**Comment by MoFtZ** [comment]
@AnakinCN
The issue is in this bit of code:
```CSharp
public struct EnvelopeItemsStruct
{
    public EnvelopeItem[] Items;
     public int Cursor;
}
```

The member field `Items` is using an array, which is a reference type, and is not supported by ILGPU.

As an alternative, you might be able to use [fixed buffers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers).

And you are correct, the error messages are very generic - we should try to improve this bit of the code.
I get something like this:
```
System.ArgumentOutOfRangeException
  Message=Specified argument was out of the range of valid values. (Parameter 'type')
  StackTrace:
   at ILGPU.Backends.EntryPoints.ArgumentMapper.MapType(Type type)
   at ILGPU.Backends.EntryPoints.ArgumentMapper.MapStructType(Type structType)
   at ILGPU.Backends.EntryPoints.ArgumentMapper.MapType(Type type)
   at ILGPU.Backends.EntryPoints.ArgumentMapper.MapStructType(Type structType)
   at ILGPU.Backends.EntryPoints.ArgumentMapper.MapType(Type type)
   at ILGPU.Backends.EntryPoints.ArgumentMapper.Map[TILEmitter,TMappingHandler](TILEmitter& emitter, TMappingHandler& mappingHandler, ParameterCollection& parameters)
   at ILGPU.Backends.PTX.PTXArgumentMapper.Map[TILEmitter](TILEmitter& emitter, EntryPoint entryPoint)
```

**Comment by MoFtZ** [comment]
> I tried writing a sample using structures with ILGPU, and it throws different in different graphic cards (OpenCL & CUDA), none succeeded.

When I test on OpenCL and Cuda, they both throw the same exception. What different exceptions are you getting?

**Comment by AnakinCN** [comment]
> As an alternative, you might be able to use [fixed buffers](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers).
> 
Since the 'unsafe' 'fixed' mark only supports simple numeric, I guess there is no way I use collections or arrays containing custom struct, even with fixed length. Is that right?

>When I test on OpenCL and Cuda, they both throw the same exception. What different exceptions are you getting?
>

In GTX 960 the exception is as yours. In the other, the OpenCL one, the exception message is "". I guess it's because symbol downloading incompletion, which does not matter. Thank you!

**Comment by MoFtZ** [comment]
@AnakinCN you will likely need to refactor how you store your data.

Rather than an array of structures, break the structure into arrays of it's individual fields.

```CSharp
struct EnvelopeItem
{
    public float Start;
    public float End;
}

struct EnvelopItemsStruct
{
    pubilc fixed EnvelopItem Items[255]; // Not supported
}

struct AlternateEnvelopItemsStruct
{
    public fixed float Start[255]; // Array of individual fields
    public fixed float End[255];
}
```

**Comment by AnakinCN** [comment]
> @AnakinCN you will likely need to refactor how you store your data.
> 
> Rather than an array of structures, break the structure into arrays of it's individual fields.
> 
> ```cs
> struct EnvelopeItem
> {
>     public float Start;
>     public float End;
> }
> 
> struct EnvelopItemsStruct
> {
>     pubilc fixed EnvelopItem Items[255]; // Not supported
> }
> 
> struct AlternateEnvelopItemsStruct
> {
>     public fixed float Start[255]; // Array of individual fields
>     public fixed float End[255];
> }
> ```

Thank you.
