### ISSUE TITLE
Feature request: Add the ability to receive data from gpu sensors

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#387]
I propose to add the ability to add methods that return the current parameters of the accelerator:
* temperature
* fan speed
* cpu and memory frequencies

**Comment by m4rs-mt** [comment]
@mikhail-khalizev Thanks for this feature request 👍 I guess these queries would be possible via the [NVML](https://developer.nvidia.com/nvidia-management-library-nvml) library for Cuda-capable devices. Maybe we can create a wrapper for the `ILGPU.Algorithms` package. However, this also requires adding several properties to the `CudaAccelerator` class in order to instantiate an NVML context.

**Comment by MoFtZ** [comment]
Raised PR that adds some `NvmlAPI` bindings, and an `NvmlDevice` wrapper.

This wrapper supports easy access to:
- temperature
  - [nvmlDeviceGetTemperature](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g92d1c5182a14dd4be7090e3c1480b121)
  - [nvmlDeviceGetTemperatureThreshold](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g271ba78911494f33fc079b204a929405)
- fan speed
  - [nvmlDeviceGetFanSpeed](
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1ge8e3e5b5b9dcf436e4537982cf647d4e)
  - [nvmlDeviceGetFanSpeed_v2](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g888c927906705a639b1ac4bdf6b7bfef)
- cpu and memory frequencies
  - [nvmlDeviceGetClockInfo](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1ge8bef48b0ae6c2bb4004875621532238)
  - [nvmlDeviceGetMaxClockInfo](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1gf324666a13ea96c0becf561bc29fd11d)

**Comment by lostmsu** [comment]
I wonder if this should be in the scope of this library...

**Comment by ShagufthaT** [comment]
Is there a way to get the percentage of GPU utilized by an application in real-time?
