### ISSUE TITLE
A PTX JIT compilation failed

### ISSUE THREAD

**Issue by AlexAba** [m4rs-mt/ILGPU#39]
I have an exception: "A PTX JIT compilation failed" at 

`var myKernel = accelerator.LoadAutoGroupedStreamKernel<Index, ArrayView<int>>(MyKernel);`.

I have windows 10, nVidia GeForce 940MX, Visual Studio 2017

            using (var context = new Context())
            {
                using (var accelerator = new CudaAccelerator(context))
                {
                    var myKernel = accelerator.LoadAutoGroupedStreamKernel<Index, ArrayView<int>>(MyKernel);

                    using (var buffer2 = accelerator.Allocate<int>(1000))
                    using (var buffer = accelerator.Allocate<int>(1000))
                    {

                        s1.Start();

                        myKernel(buffer.Length, buffer.View);

                        accelerator.Synchronize();
                        s1.Stop();

                        var data = buffer.GetAsArray();

                        for (var i = 0; i < 100; i++)
                        {
                            Console.Write(" " + data[i]);
                        }
                    }
                }
            }

**Comment by m4rs-mt** [comment]
@AlexAba this sounds like a driver issue. Have you tried updating your graphics drivers (as also proposed in #36)?

**Comment by AlexAba** [comment]
I have update my drivers to last version. And when I use 0.5.1 version it's all ok.

**Comment by m4rs-mt** [comment]
Hmm.... Can you provide the kernel code in such a way that we can investigate the problem more closely?

**Comment by AlexAba** [comment]
`const int n = 10;`
`static void MyKernel(Index index, ArrayView<int> dataView)`
`        {`
`           int z = 0;`
`           for (int t = 0; t < n; t++)`
`            {`
`                z += 5;`
`           }`
`            dataView[index] = z;`
`        }`
