### ISSUE TITLE
Feature request: long shift

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#390]
Hi.

Now I am faced with the following problem.
I need to shift the right 24 bits of a 512 bit local variable.

```csharp
     [StructLayout (LayoutKind.Sequential, Size = 64, Pack = 1)]
     public struct StepRow
     {
         public ulong u0;
         public ulong u1;
         public ulong u2;
         public ulong u3;
         public ulong u4;
         public ulong u5;
         public ulong u6;
         public ulong u7;
      }

      public static void Kernel (...)
      {
         StepRow row;
         ...
         row >>= 24; // How?
         ...
      }
```

It looks simple to do it efficiently if we had regular C or C++. Since we have a shift of exactly 3 bytes, we could take a pointer to the beginning of the structure and add 3:

```c++
{
     StepRow row;
     ...
     StepRow * ptr = (StepRow *) (((char *) &row) + 3);
     row.u0 = ptr->u0;
     row.u1 = ptr->u1;
     row.u2 = ptr->u2;
     row.u3 = ptr->u3;
     row.u4 = ptr->u4;
     row.u5 = ptr->u5;
     row.u6 = ptr->u6;
     row.u7 = ptr->u7;
     // And after that set 3 high bytes of `row` to 0.
}
```

But is there a way to do this as efficiently and quickly in C# on GPU for local variable?

**Comment by mikhail-khalizev** [comment]
Of course there is a way to do it step by step (slowly).
But maybe there are some other ways that I don't know ...

```csharp
    public struct StepRow
    {
        public ulong u0;
        public ulong u1;
        public ulong u2;
        public ulong u3;
        public ulong u4;
        public ulong u5;
        public ulong u6;
        public ulong u7;

        public void ShiftRight24()
        {
            u0 >>= 24;
            u0 |= u1 << 40;

            u1 >>= 24;
            u1 |= u2 << 40;

            u2 >>= 24;
            u2 |= u3 << 40;

            u3 >>= 24;
            u3 |= u4 << 40;

            u4 >>= 24;
            u4 |= u5 << 40;

            u5 >>= 24;
            u5 |= u6 << 40;

            u6 >>= 24;
            u6 |= u7 << 40;

            u7 >>= 24;
        }
    }
```

**Comment by mikhail-khalizev** [comment]
I forgot that C# has an unsafe context in which we can use pointers. This solves this problem.

**Comment by m4rs-mt** [comment]
Thanks for your feature request. Unfortunately, I don't have a very efficient solution for this task right now. We can try to emit swizzle-like operations to do this in an efficient way. However, using pointers means that the structure will be stored in `local` memory, which in turn will reside in `global` memory. Furthermore, (correct me if I'm wrong) the reads after `StepRow * ptr = (StepRow *) (((char *) &row) + 3);` will not be aligned to `8-bytes` any more and require "slow" IO loads. Hence I think using many shift and or operations might be much faster (depending on the register pressure in your program).

**Comment by mikhail-khalizev** [comment]
Ha-ha. I just receive `ILGPU.Runtime.Cuda.CudaException: "misaligned address"` exception, when do it in local memory (stack).


```
                StepRow item = ...

                var ptr = (ulong*)((byte*)&item + 3);
                
                item.u0 = ptr[0];
                item.u1 = ptr[1];
                item.u2 = ptr[2];
                item.u3 = ptr[3];
                
                item.u4 = ptr[4];
                item.u5 = ptr[5];
                item.u6 = ptr[6];
                item.u7 = ptr[7];
                
                item.u7 &= 0x000000ff_ffffffff;
```

**Comment by m4rs-mt** [comment]
I guess this issue should disappear as soon as #386 is merged 🤔
