### ISSUE TITLE
Can you provide an example of multi GPU cooperative work? I try to change single GPU to multi GPU, but there are always exceptions.

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#397]
invalid resource handle

**Comment by m4rs-mt** [comment]
@xxl-cc Thank you for your request. I'm not sure what the intent behind your question is. Would you like to see an example of how to split your workload across multiple GPUs by launching kernels on different devices at the same time?

**Comment by geobimmodeling** [comment]
@m4rs-mt I'd like to see examples
1.   Split workload across multiple GPUs by launching kernels on different devices at the same time
2.   Buffer data share between multiple GPUs. Can buffer data be shared between multiple GPUs from the same device (say, through NLINK of Nvidia)?

**Comment by MoFtZ** [comment]
@geobimmodeling @xxl-cc 

I'm not sure if this is what you were after, but here is an example of using multiple GPUs to sort some arrays. It performs a round-robin between the available Cuda accelerators.

[RoundRobinExample.zip](https://github.com/m4rs-mt/ILGPU/files/5974819/RoundRobinExample.zip)

Note that this is different from using multiple GPUs to cooperatively sort an array. I found this paper while doing some research on the topic, but have not tried to implement it (http://impact.crhc.illinois.edu/shared/papers/p1-tanasic.pdf).

And it also does not show how to share buffers between GPUs. It theory, you should be able to call `Accelerator.EnablePeerAccess`, but I do not have access to an NVLINK setup.

**Comment by xxl-cc** [comment]
When multiple GPUs are parallel computing, does each GPU declare a context, or do multiple GPUs share a context?

**Comment by xxl-cc** [comment]
It's my fault，The action of multiple GPUs should not be the same field
