### ISSUE TITLE
Feature request: improve kernel name

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#398]
Currently all kernels displayed as `ILGPUKernel` (see screenshot below).

I suggest adding the ability to manually name the kernels from code.
And by default use the name of the kernel method from C#.

![image](https://user-images.githubusercontent.com/18654696/105497721-4aa1c200-5cd0-11eb-9ead-043018015f17.png)

**Comment by m4rs-mt** [comment]
@mikhail-khalizev Sounds good to me. That should simplify the profiling tasks a lot 🤓.
