### ISSUE TITLE
10 sec delay after data transfer from CPU to GPU

### ISSUE THREAD

**Issue by Aleksey1555** [m4rs-mt/ILGPU#400]
Hello.
I have in issues,  i have 3GB of data to load to GPU and i am doing it like this:

```
class SomeClass
{
   Context cntx = null;
   CudaAccelerator ca = null;
   Pix[,,] pix = null;
   public void f()
    {
        pix = new Pix[ImagesLen, ImgHeight, ImgWidth]; // in my case  Pix[166120, 286, 226] = 3Gb , and pix gives 3 byte 
        // Here code that fill pix array
        //  .........
        //Context and CudaAccelerator already loading and working 
        MemoryBuffer3D<Pix> mbpix = null;
        mbpix = ca.Allocate<Pix>(pix);    /// And the result is that , this function work too slow - 7 sec of 3 Gb data
    }
}
strct Pix  // struct Not a class 
{
   public byte r;
   public byte g;
   public byte b;
}
```
I think this is some kind problem, becase can;t that 3 gb trasfers about 10 sec
or possible i am Wrong.
Please Help...

**Comment by Aleksey1555** [comment]
some additions:

I try MemoryBuffer without 2D or 3D and uploading data into GPU occurred instantly!!!!

**Comment by artyomdp** [comment]
Looks like I'm having same issue.
I have two arrays flat [amount*dimension] and 2d [amount, dimension]
Copying 2d array is almost 10 times slower:
```csharp          
using (var context = new Context())
{
    using (var accelerator = new CudaAccelerator(context))
    {
        using (var buffer_vectors = accelerator.Allocate<float>(amount * dimension))
        {
            sw.Start();
            for (int i = 0; i < iterations; i++)
            {
                buffer_vectors.CopyFrom(vectors, 0, ILGPU.LongIndex1.Zero, vectors.Length);
            }
            Console.WriteLine("MemoryBuffer - copy complete in {0}\n", sw.Elapsed);
        }

        using (var buffer_vectors2d = accelerator.Allocate<float>(amount, dimension))
        {
            sw.Restart();
            for (int i = 0; i < iterations; i++)
            {
                buffer_vectors2d.CopyFrom(vectors2d, Index2.Zero, Index2.Zero, (amount, dimension));
            }
            Console.WriteLine("MemoryBuffer2D - copy complete in {0}\n", sw.Elapsed);
        }
    }
}
```

> MemoryBuffer - copy complete in 00:00:03.5726977
>MemoryBuffer2D - copy complete in 00:00:25.1288403

**Comment by MoFtZ** [comment]
@Aleksey1555 @artyomdp
My guess is that this is related to https://github.com/m4rs-mt/ILGPU/issues/346.

With 2D and 3D memory buffers, when ILGPU is copying to the GPU accelerator, the contents of the buffer will be converted from [row-major to column-major order](https://en.wikipedia.org/wiki/Row-_and_column-major_order).

**Comment by Aleksey1555** [comment]
I think this post #346 not about performance!!! The talking about arrays row/column ordering.
How can it help's the performance problem?
Problem - that any 2d or 3d array need to convert to linear array, and this process take's some time!
In my situation - 10 seconds to wait.

**Comment by Aleksey1555** [comment]
How ILGPU detecting that array not o columnn-major order?
And how to tell ILGPU that my array is in column-major order?

**Comment by Aleksey1555** [comment]
OK, this convertion is need becase we use row major order and the GPU column-major order.
What if i create an array with column-ordering by myself? Will ILGPU start converting process? Another words - Can i disable this convertion operation.?
P.S. I can restructure my program for column-major order)

**Comment by m4rs-mt** [comment]
@Aleksey1555 @artyomdp I think @MoFtZ is right 👍. This seems to be related to the same problem that the data transfer performs a "hidden" (opaque to the user) transpose operation, which can easily consume a lot of time. We should discuss possible improvements/workarounds in #346.

**Comment by Aleksey1555** [comment]
I Also don't understand how ILGPU works:
I create 2d array in .Net with row-major order , after ILGPU make column-major order
and what's going on - in KERNEL i seem my 2D array in row-major order!!!
Look's like the situation is :    row-major ->column-major -> row-major(but for kernel)
And if  i have array of [2,5] then after conversion it will be [5,2] and, then GPU starting to work with my array
but what reason of this convertion? array still 2D not 1D. I Can by mayself decide int whitch row-column-order i want to pass my array

**Comment by Aleksey1555** [comment]
I have to save that any 2d array may be interpret like row-major or column-order. I think ( but maybe i wrong) this ordering (row or column major) affect's only to how the data will be stored in 1 dim array.

**Comment by Ruberik** [comment]
These might be useful:
```
    public static class ILGPUExtensions {
        /// <summary>
        /// Warning: untested.
        /// </summary>
        public static unsafe MemoryBuffer3D<T> AllocateNoTranspose<T>(this Accelerator accelerator, T[,,] data) where T : unmanaged {
            var result = accelerator.Allocate<T>(new LongIndex3(data.GetLength(2), data.GetLength(1), data.GetLength(0)));
            long chunkSize = int.MaxValue;
            for (long startIndex = 0; startIndex < data.LongLength; startIndex += chunkSize) {
                int lengthToCopy = (int)Math.Min(data.LongLength - startIndex, chunkSize);
                var destination = new LongIndex3(startIndex % data.GetLength(2), (startIndex / data.GetLength(2)) % data.GetLength(1), startIndex / data.GetLength(2) / data.GetLength(1));  // If there's a line that's wrong, this is it.
                fixed (T* t = data) {
                    result.CopyFrom(new ReadOnlySpan<T>(t + startIndex, lengthToCopy), 0, destination, lengthToCopy);
                }
            }
            return result;
        }

        // Note that data can't have more than uint.MaxValue elements due to a limitation in C#.
        public static unsafe MemoryBuffer2D<T> AllocateNoTranspose<T>(this Accelerator accelerator, T[,] data) where T : unmanaged {
            var result = accelerator.Allocate<T>(new LongIndex2(data.GetLength(1), data.GetLength(0)));
            long chunkSize = int.MaxValue;
            for (long startIndex = 0; startIndex < data.LongLength; startIndex += chunkSize) {
                int lengthToCopy = (int)Math.Min(data.LongLength - startIndex, chunkSize);
                var destination = new LongIndex2(startIndex % data.GetLength(1), startIndex / data.GetLength(1));
                fixed (T* t = data) {
                    result.CopyFrom(new ReadOnlySpan<T>(t + startIndex, lengthToCopy), 0, destination, lengthToCopy);
                }
            }
            return result;
        }

        public static T[,,] GetAs3DArrayNoTranspose<T>(this MemoryBuffer3D<T> data) where T : unmanaged {
            var result = new T[data.Extent.Z, data.Extent.Y, data.Extent.X];
            var result1D = new T[data.Length];
            data.CopyTo(result1D, LongIndex3.Zero, 0, data.Extent);
            var rowLength = result.GetLength(2);
            var blockLength = result.GetLength(1) * rowLength;
            ParallelChunked.For(0, result1D.Length, 2000, (startIndex, endIndex) => {
                for (int i = startIndex; i < endIndex; i++) {
                    result[i / blockLength, (i % blockLength) / rowLength, i % rowLength] = result1D[i];
                }
            });
            return result;
        }

        public static T[,] GetAs2DArrayNoTranspose<T>(this MemoryBuffer2D<T> data) where T : unmanaged {
            var result = new T[data.Extent.Y, data.Extent.X];
            var result1D = new T[data.Length];
            data.CopyTo(result1D, LongIndex2.Zero, 0, data.Extent);
            var rowLength = result.GetLength(1);
            ParallelChunked.For(0, result1D.Length, 2000, (startIndex, endIndex) => {
                for (int i = startIndex; i < endIndex; i++) {
                    result[i / rowLength, i % rowLength] = result1D[i];
                }
            });
            return result;
        }
    }
```

**Comment by Aleksey1555** [comment]
@Ruberik  Thanks!

**Comment by Aleksey1555** [comment]
@Ruberik  hello!
Can you say me what is ParallelChunked.For?
there is no such function in .Net

**Comment by Aleksey1555** [comment]
please

**Comment by Ruberik** [comment]
My mistake:
```
    public static class ParallelChunked {
        public static void For(int startInclusive, int endExclusive, int chunkSize, Action<int, int> rangeAction) {
            var num = endExclusive - startInclusive;
            Parallel.For(0, (num + chunkSize - 1) / chunkSize, chunk => {
                rangeAction(startInclusive + chunk * chunkSize, Math.Min(endExclusive, startInclusive + (chunk + 1) * chunkSize));
            });
        }
    }
```

**Comment by Ruberik** [comment]
`ParallelChunked.For` intends to solve two problems:

1. Parallel.For has too much overhead for short function executions.
2. Parallel.For doesn't guarantee good memory locality within threads.

For point 1, a chunkSize of 20 is generally good enough. For point 2, I haven't honestly tested it much, but since I'm copying arrays of multiple gigabytes, I think 2000 is small enough that I don't have to worry about a straggling thread taking a long time.

It isn't intended to work well with expensive function executions (just use Parallel.For) or large chunk sizes (just use a small chunk size), which is why I haven't bothered to fix the last chunk being smaller than the rest. I'm sure there's some use case where that would be helpful, but I haven't come across it yet.

**Comment by Aleksey1555** [comment]
Thanks!!!!!
