### ISSUE TITLE
Issue with v0.10 Beta2

### ISSUE THREAD

**Issue by geobimmodeling** [m4rs-mt/ILGPU#406]
I have a kernel that works with v0.10 Beta 1, but failed with Beta2. please see attached sample code.  Search "Bug" that indicates the line causing problem. 
[V10Beta2Test2.zip](https://github.com/m4rs-mt/ILGPU/files/5922840/V10Beta2Test2.zip)

**Comment by m4rs-mt** [comment]
@geobimmodeling Thank you very much for your problem report. I can confirm that the given input program leads to an internal compiler crash during optimization. However, a minimal reproducible example would simplify things on our end and would be appreciated.

**Comment by MoFtZ** [comment]
@m4rs-mt @geobimmodeling 

I've managed to reduce the example code into this:
```CSharp
using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;

namespace V10Beta2Test2
{
    class Program
    {
        static void MyKernel(ArrayView<int> view)
        {
            int value = 0;

            for (int i = 0; i < 2; i++)
            {
                if (value < 1)
                {
                    int newValue = 0;
                    if (newValue == 0)
                    {
                        value = newValue;
                    }
                }
            }
        }

        static void Main()
        {
            using var context = new Context();
            using var accelerator = new CudaAccelerator(context);
            var kernel = accelerator.LoadStreamKernel<ArrayView<int>>(MyKernel);
        }
    }
}
```

**Comment by m4rs-mt** [comment]
@MoFtZ Thank you for the reduced example. I will take a closer look at it 👀.

**Comment by geobimmodeling** [comment]
@MoFtZ @m4rs-mt Sorry, I will try my best to reduce code for debug. I though problem could be caused by my special struct (Double2x2) that is used to mimic 2-dimensional array in kernel.  AND, that kernel containing Double2x2 can be properly compiled with V 0.10 Beta 1. So I grabbed it to the example code.

**Comment by geobimmodeling** [comment]
@MoFtZ How did you manage to reduce the code? did you track into this line "if(Math.Abs(e[i, j])<0.1)" to simplify it?

**Comment by m4rs-mt** [comment]
@MoFtZ @geobimmodeling Applying #409 simplifies @MoFtZ's sample input correctly to:
```asm
MyKernel_2[Inline, EntryPoint]_126(Struct<Ptr<Int32, Generic> [0], Int64 [8]> view_128)
Entry_127:
        ret_132: undef_125
```

**Comment by MoFtZ** [comment]
I have tested the PR with the reduced code and the original code. Both no longer have the issue.

**Comment by MoFtZ** [comment]
> @MoFtZ How did you manage to reduce the code? did you track into this line "if(Math.Abs(e[i, j])<0.1)" to simplify it?

It's just trial and error. I remove or alter a small section, and make sure the problem still exists, then keep repeating.
