### ISSUE TITLE
Feature request: Add the ability to control the rounding mode for arithmetic operations

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#407]
For mathematical calculations, there is a need to adjust the rounding mode when performing operations with floating point numbers (not to be confused with rounding when converting to an integer). In C/C++, the `fesetround` function is usually responsible for this. 

Could you add this feature?

An example of addition operations from the CUDA doc:

![image](https://user-images.githubusercontent.com/18654696/106838991-54eb9500-66ae-11eb-9456-b528750182ab.png)

**Comment by m4rs-mt** [comment]
@mikhail-khalizev This is an interesting feature request 🤓. Currently, ILGPU uses a .Net-compliant rounding mode for integer to float conversions and vice versa. Regarding your question, the FP -> FP rounding mode is set to `round-to-nearest-even` (corresponding to the "default" C++ behavior). Based on dotnet/runtime#4544, there does not seem to be a comparable function on the C# side. 

However, adding this feature for scientific computing makes a lot of sense to me. I propose that we add this feature to the `CudaAccelerator` only in order point out that it is not supported on other platforms at the moment.
