### ISSUE TITLE
Rework static analysis

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#41]
As we have just switched to VS2019 (312280c90a65d4334a820bc9780663ea7418c6d6) we should definitely rework the internal static-program analysis pipeline. The current ILGPU project relies on an (now) obsolete version of the well known Post-build Code Analysis. We should definitely upgrade the analysis to a newer version.

**Comment by m4rs-mt** [comment]
After updating to the latest Visual Studio version, the FXCop analyzers seem to stop running after a successful build. Also, I usually don't get any warnings.
@MoFtZ Are there known solutions to this problem? I couldn't find any solutions to this issue on the Web so far.

**Comment by MoFtZ** [comment]
hi @m4rs-mt, I've noticed that the FXCop analyzers appear to run in the background, and in some cases only when a file is open.

I personally turn on "Enable full solution analysis", though this may have a performance impact for very large projects.
![image](https://user-images.githubusercontent.com/27792737/68083375-24e68e00-fe7c-11e9-8035-d7b2ab05a213.png)

In rare situations when there are errors/warnings/messages that should not be there, I have found a "Rebuild All" or restarting Visual Studio itself, will fix the problem.

**Comment by m4rs-mt** [comment]
@MoFtZ Thank you very much. The activation of the "full solution analysis" seems to solve the problem. Rebuilding and restarting Visual Studio seems to work from time to time. I also noticed the background tasks, but unfortunately the errors/warnings/messages don't appear after some time.
