### ISSUE TITLE
Support for OpenTK

### ISSUE THREAD

**Issue by JanTamis** [m4rs-mt/ILGPU#414]
Are there any plans to support OpenTK? I know there is support for SharpDX but it would be nice to send the result of a calculation to the graphics card.

**Comment by MoFtZ** [comment]
@JanTamis I am not familiar with OpenTK. Looking at the API, it looks like they provide low-level bindings for OpenCL. Some of these can probably already be used in combination with ILGPU. What kind of integrations do you think would be beneficial?

**Comment by m4rs-mt** [comment]
I am closing this issue for now due to inactivity.
