### ISSUE TITLE
Documentation request: add intrinsic example

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#416]
I have a need to multiply two UInt64 numbers and get UInt128. Potentially, CUDA has instructions "mul.lo.u64" and "mul.hi.u64" for this.

Could you supplement the documentation http://www.ilgpu.net/Documentation with an example of how to write intrinsic yourself (for example for "mul.hi.u64")?

**Comment by MoFtZ** [comment]
@mikhail-khalizev Have you seen the [custom intrinsic example](https://github.com/m4rs-mt/ILGPU.Samples/tree/master/Src/CustomIntrinsics) in [ILGPU.Samples](https://github.com/m4rs-mt/ILGPU.Samples)?

**Comment by mikhail-khalizev** [comment]
No, I didn't notice this example, unfortunately.

Now I looked. But there is still the question of how to use `mul.hi.u64` directly, since now the example uses the C # expression:

```csharp
        /// <summary>
        /// The Cuda (PTX) implementation.
        /// </summary>
        public static int ComputePTX(int x) => 2 * x;
```

**Comment by MoFtZ** [comment]
There are two types of intrinsics in that sample code. The first is remappped intrinsics, which points the code to a different method.

The second is code generated intrinsics (`CustomCodeGeneratorIntrinsic`). In the method `GeneratePTXCode`, you create your command, something like this:
```CSharp
using (var command = codeGenerator.BeginCommand("mul.hi.u64"))
{
   command.AppendArgument(.....);
   command.AppendArgument(.....);
}
```

**Comment by mikhail-khalizev** [comment]
Thanks!
