### ISSUE TITLE
Struct member variable after fixed array cannot be used in comparison operation.

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#418]
I have reduce the code from issue #417 into a minimal example of the problem.

When `Cursor` is defined after `Array`, ILGPU will fail to compile. When `Cursor` is defined before `Array`, it compiles without issue.

```CSharp
public unsafe struct ArrayStruct
{
    public fixed int Array[2];
    public int Cursor;
}

private static void FailingKernel(Index1 index, ArrayView<int> view)
{
    var a = new ArrayStruct();
    if (a.Cursor > 0)
    {
        view[index] = index;
    }
}

static void Main()
{
    using var context = new Context();
    using var accelerator = new CudaAccelerator(context);

    accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<int>>(FailingKernel);
}
```
The exception thrown is:
`NotSupportedException: Not supported compare or arithmetic value of type 'None'`

**Comment by m4rs-mt** [comment]
Oh, that looks interesting and is definitely a bug we should fix 🤓.
