### ISSUE TITLE
Feature request: support of constant array

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#419]
There is now a `SimpleConstants` example that shows that constants can be used. But not constant arrays.

Consider adding support of constant arrays in the kernel:
```
        private static readonly ulong[] Data = new ulong[8]
        {
            0x6A09E667F3BCC908UL,
            0xBB67AE8584CAA73BUL,
            0x3C6EF372FE94F82BUL,
            0xA54FF53A5F1D36F1UL,
            0x510E527FADE682D1UL,
            0x9B05688C2B3E6C1FUL,
            0x1F83D9ABFB41BD6BUL,
            0x5BE0CD19137E2179UL,
        };

        static void MyKernel(ArrayView<int> dataView)
        {
            dataView[0] = (int)Data[0];
        }
```

**Comment by m4rs-mt** [comment]
@mikhail-khalizev Thank you for your feature request. In theory, this is a very nice feature. However, marking the field as `readonly` does not guarantee that the contents of the array will not change between different kernel calls. What we could do is to use the `ContextFlags.InlineMutableStaticFieldValues` flag to suppress compiler warnings/errors and inline the array as suggested.

**Comment by CsabaStupak** [comment]
My understanding is that the GPU _const_ memory is much faster. By this I could put my _weights_ to const memory - no need to copy them to shared memory in the kernel. 👍

**Comment by m4rs-mt** [comment]
I am currently working on support for multidimensional arrays and constant arrays, which can be inlined into the kernel 🤓
