### ISSUE TITLE
Can ILGPU give access to the  low-level CUDA functions like nvJPEG ?

### ISSUE THREAD

**Issue by Aleksey1555** [m4rs-mt/ILGPU#422]
here - https://docs.nvidia.com/cuda/nvjpeg/index.html

**Comment by m4rs-mt** [comment]
@Aleksey1555 Thank you for your feature request. This might be an interesting feature for the `Algorithms` library, I think.

**Comment by m4rs-mt** [comment]
@Aleksey1555 We have been discussing about adding new bindings to Algorithms library. @MoFtZ is currently working on great extensions to cover most API bindings from several well-known and prominent Cuda libraries. However, we came to the conclusion that supporting the `nvJPEG` library is too much work at the moment. Perhaps you can elaborate on a specific use case you have in mind?
