### ISSUE TITLE
AMD FirePro W4100 GPU is not recognized as CLAccelerator

### ISSUE THREAD

**Issue by avsol** [m4rs-mt/ILGPU#424]
I am running DeviceInfo sample from the ILGPU.Samples GitHub repo on my Dell workstation, but it lists only CPU and Intel(R) HD Graphics accelerators. The primary graphics card AMD FirePro W4100 is not listed.
I tried looking in the Accelerator.Accelerators as well as in the CLAccelerator.AllCLAccelerators collections.

> foreach (var acceleratorId in Accelerator.Accelerators) // CLAccelerator.AllCLAccelerators)
> {
>     // Create default accelerator for the given accelerator id.
>     // Note that all accelerators have to be disposed before the global context is disposed
>     using (var accelerator = Accelerator.Create(context, acceleratorId))
>     {
>         Console.WriteLine($"AcceleratorId: {acceleratorId.AcceleratorType}, {accelerator.Name}");
>         PrintAcceleratorInfo(accelerator);
>         Console.WriteLine();
>     }
> }

**Comment by avsol** [comment]
Interesting, that this GPU was recognized when I tried `OpenCLCompiler` from the `Amplifier` library (https://github.com/tech-quantum/Amplifier.NET)

**Comment by MoFtZ** [comment]
hi @avsol, it looks like the AMD FirePro W4100 only supports [up to OpenCL 1.2](https://www.techpowerup.com/gpu-specs/firepro-w4100.c2611). Unfortunately, ILGPU requires a minimum of OpenCL 2.0.

Are you using ILGPU v0.10 ? According to the [release notes](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.10.0), it included a change to detect OpenCL accelerators, even if they are not supported. These would then appear in `CLAccelerator.AllCLAccelerators`.
> Added new CLPlatformVersion and fixed OpenCL 1.2 compatibility issues

**Comment by avsol** [comment]
Yes, you are right. I was using ILGPU v.0.9.2
The version 0.10 does list the AMD Capeverde accelerator as unsupported in the AllCLAccelerators collection.
(Though AMD claims to support OpenCL 2.0, even latest driver doesn’t show up)

**Comment by m4rs-mt** [comment]
@avsol It looks like the driver supports the OpenCL 2.0 API layer, but the GPU itself does not support the OpenCL C 2.0 execution model. Maybe this is the problem in this area?
