### ISSUE TITLE
Can we generate some kernels and load them dynamically?

### ISSUE THREAD

**Issue by faruknane** [m4rs-mt/ILGPU#432]
Hi,
First of all, I am so impressed by the work you have been doing. It's a great project.

"JIT" compiler might be really helpful for optimizing data flows whereas you can't do it with static compilers. I have been considering building a library for tensor operations and auto differentiation. Like tensorflow did with XLA in 2017, I'd like to optimize the data flow as well. For a very basic example, to sum three vectors normally people code like res = sum(sum(x, y), z). This type of usage is reducing efficiency. I need to automatically detect the vectors that are to be summed in the computing graph and generate a kernel for the number of those vectors. In the example that is three. 

So, my kernel would be like,

(non-template example)
```csharp
static void MyKernel(Index1 index, ArrayView<float> res, ArrayView<float> arr1, ArrayView<float> arr2, ArrayView<float> arr3) 
        {
            res[index] = arr1[index] + arr2[index] + arr3[index];
        }
```

Could you guide me on how to generate dynamic kernels and give dynamic parameters etc?

Thank you so much again!

// I found this will take a look -> https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/LowLevelKernelCompilation/Program.cs

**Comment by faruknane** [comment]
This library is also like %3 or %4 slower than Cuda when summing two big vectors. 

In small examples, it's actually a little faster than Cuda in my example (probably because of creating streams etc). 

So, I liked that!

**Comment by m4rs-mt** [comment]
@faruknane thank you for your issue report. ILGPU features a huge variety of different compiler optimization technique to rewrite, fold and simply your program. You want want to take a look at [Specialized Kernels](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/SpecializedKernel/Program.cs) that allow you to pass "constants" to kernels in order to trigger/enable/use aggressive optimizations.

Regarding dynamic code generation, you can use on-the-fly generated dotnet `Assembly` instances and pass them to ILGPU. We are currently investigating what the best way is to enable expression trees/LINQ to be compiled by ILGPU (see also #415).

**Comment by faruknane** [comment]
@m4rs-mt It's 1 am here. I will read your reply in detail first thing tomorrow. 

From the first part, I understand that like if constval is 1 in the code below

this code -> 
```csharp
if (constval == 1)
      res[i] = 1;
else
      res[i] = 2;
```

turns out to be this -> 
```csharp
res[i] = 1;
```
So, it doesn't check if it is one. It dynamically compiles and optimizes the code and removes unnecessary operations.  Am I right?

**Comment by MoFtZ** [comment]
In ILGPU v0.9.1, we added support for using non-capturing lambdas as a kernel.

This allows you to define a kernel like this:
```CSharp
using var context = new Context();
using var accelerator = new CudaAccelerator(context);

Action<Index1, ArrayView<int>> kernel =
    (index, output) =>
     {
        output[index] = index;
    };

var action = accelerator.LoadAutoGroupedStreamKernel(kernel);
```

You should be able to use LINQ Expression Trees to create a non-capturing lambda kernels at runtime.

**Comment by faruknane** [comment]
@MoFtZ @m4rs-mt I am trying to create the method below:
```csharp
        static void Kernel<T>(
        Index1 index,
        ArrayView<T> res,
        ArrayView<T> arr1,
        ArrayView<T> arr2)
        where T : unmanaged
        {
            res[index] = Op(arr1[index], arr2[index]);
        }
```

```csharp
            ParameterExpression res = Expression.Parameter(typeof(ArrayView<float>), "res");
            ParameterExpression arr1 = Expression.Parameter(typeof(ArrayView<float>), "arr1");
            ParameterExpression arr2 = Expression.Parameter(typeof(ArrayView<float>), "arr2");
            ParameterExpression index = Expression.Parameter(typeof(Index1), "index");

            var prop = typeof(ArrayView<float>).GetProperty("Item", new[] { typeof(Index1) });

            Expression arr1_index = Expression.MakeIndex(arr1, prop, new List<Expression>() { index }); //error here
            Expression arr2_index = Expression.MakeIndex(arr2, prop, new List<Expression>() { index });
            Expression res_index = Expression.MakeIndex(res, prop, new List<Expression>() { index });

            Expression added = Expression.Add(arr1_index, arr2_index);
            Expression block = Expression.Assign(res_index, added);


            var func = Expression.Lambda<Action<Index1,
                ArrayView<float>,
                ArrayView<float>,
                ArrayView<float>>>(block, index, res, arr1, arr2).Compile();
```
the code above throws an error "System.ArgumentException: 'Property cannot have a managed pointer type. Arg_ParamName_Name'"

Also, the code below throws an error "System.InvalidOperationException: 'The binary operator Add is not defined for the types 'System.Single&' and 'System.Single&'.'"

```csharp
            ParameterExpression res = Expression.Parameter(typeof(ArrayView<float>), "res");
            ParameterExpression arr1 = Expression.Parameter(typeof(ArrayView<float>), "arr1");
            ParameterExpression arr2 = Expression.Parameter(typeof(ArrayView<float>), "arr2");
            ParameterExpression index = Expression.Parameter(typeof(Index1), "index");

            var prop = typeof(ArrayView<float>).GetMethod("get_Item", new[] { typeof(Index1) });

            Expression arr1_index = Expression.Call(arr1, prop, new List<Expression>() { index }); 
            Expression arr2_index = Expression.Call(arr2, prop, new List<Expression>() { index });
            Expression res_index = Expression.Call(res, prop, new List<Expression>() { index });

            Expression added = Expression.Add(arr1_index, arr2_index); //error here
            Expression block = Expression.Assign(res_index, arr1_index);

            var func = Expression.Lambda<Action<Index1,
                ArrayView<float>,
                ArrayView<float>,
                ArrayView<float>>>(block, index, res, arr1, arr2).Compile();
```
The conversion from ref float to float does not work with Expressions. 

This is a known issue but is not solved yet -> https://github.com/dotnet/runtime/issues/24621 

I will try to compile a method from a string written code. Back in the day, I was doing this kind of thing (compiling code from string) If I remember it correctly.

**Comment by faruknane** [comment]
@m4rs-mt could you help me to understand whether the problem is on my side or on the ILGPU side?

My goal is to create the function below:
```csharp
        static void Kernel3(
           Index1 index,
           ArrayView<float> res,
           ArrayView<float> arr1,
           ArrayView<float> arr2)
        {
            res[index] = arr1[index] + arr2[index];
        }
```

the Il code for the functon above is:

![image](https://user-images.githubusercontent.com/37745467/111178041-d42c8c80-85bb-11eb-8e79-5024aced875d.png)


So, I create a method like below. Still, the last line makes it static though. I hope I can make it dynamic somehow.

```csharp
        private delegate void KernelDeneme(Index1 index,
           ArrayView<float> res,
           ArrayView<float> arr1,
           ArrayView<float> arr2);

        static void Main()
        {
            var indexmethod = typeof(ArrayView<float>).GetMethod("get_Item", new[] { typeof(Index1) });

            DynamicMethod dynamicmethod = new DynamicMethod(
             "dynamicmethod",
             null,
             new[] { typeof(Index1), typeof(ArrayView<float>), typeof(ArrayView<float>), typeof(ArrayView<float>) },
             typeof(Program).Module);

            ILGenerator il = dynamicmethod.GetILGenerator();

            il.Emit(OpCodes.Ldarga_S, 1);
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Call, indexmethod);


            il.Emit(OpCodes.Ldarga_S, 2);
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Call, indexmethod);
            il.Emit(OpCodes.Ldind_R4);


            il.Emit(OpCodes.Ldarga_S, 3);
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Call, indexmethod);
            il.Emit(OpCodes.Ldind_R4);

            il.Emit(OpCodes.Add);
            il.Emit(OpCodes.Stind_R4);

            il.Emit(OpCodes.Ret);

            //still static!
            var methodcreated = (KernelDeneme)dynamicmethod.CreateDelegate(typeof(KernelDeneme));
        }
```

When I try to compile the method for the accelerator it throws an error. 
```csharp
                    var backend = accelerator.Backend;
                    var entryPointDesc = EntryPointDescription.FromExplicitlyGroupedKernel(methodcreated.Method);
                    var compiledKernel = backend.Compile(entryPointDesc, default);
                    
```
error:

```
Unhandled exception. ILGPU.InternalCompilerException: 'An internal compiler error has been detected' in method Void dynamicmethod(ILGPU.Index1, ILGPU.ArrayView`1[System.Single], ILGPU.ArrayView`1[System.Single], ILGPU.ArrayView`1[System.Single]) declared in type
 ---> System.NotSupportedException: Derived classes must provide an implementation.
   at System.Reflection.MethodInfo.GetGenericArguments()
   at ILGPU.Frontend.Disassembler..ctor(MethodBase methodBase, SequencePointEnumerator sequencePointEnumerator) in ILGPU.Frontend\Disassembler.cs:line 49
   at ILGPU.Frontend.CodeGenerationPhase.GenerateCodeInternal(MethodBase method, Boolean isExternalRequest, HashSet`1 detectedMethods, Method& generatedMethod) in ILGPU.Frontend\CodeGenerationPhase.cs:line 53
   --- End of inner exception stack trace ---
   at ILGPU.Backends.Backend.PreCompileKernelMethod[TBackendHook](EntryPointDescription& entry, TBackendHook backendHook) in ILGPU.Backends\Backend.cs:line 292
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook) in ILGPU.Backends\Backend.cs:line 307
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization) in ILGPU.Backends\Backend.cs:line 302
```

The file is here: 
[Program.zip](https://github.com/m4rs-mt/ILGPU/files/6142515/Program.zip)

**Comment by m4rs-mt** [comment]
@faruknane There are two problems with this piece of code. First, you call `FromExplicitlyGroupedKernel` even though your kernel seems to be an implicitly grouped kernel...? Second, the problem is related to the .Net implementation of a `DynamicMethod` that does not return an empty array, but throws a `NotSupportedException` when calling `GetGenericArguments` instead. You can argue that this is the intended behavior, since it makes no sense to ask for the generic arguments of a generic method. According to the documentation, you can also argue the other way around, that the method should return an empty array instead.

**Comment by faruknane** [comment]
@m4rs-mt Also DynamicMethod doesn't support GetMethodBody(), so I can't use DynamicMethod. I am working on creating a dynamic method without using DynamicMethod class. It will provide generic arguments and a method body info hopefully.

**Comment by m4rs-mt** [comment]
@faruknane Right! A `DynamicMethod` was intended to JIT some smaller methods at runtime without the need to inspect their internal data.

**Comment by faruknane** [comment]
@m4rs-mt Yaaay, I did it!

**Comment by faruknane** [comment]
@m4rs-mt I have a new issue for performance drop when using load implicitly kernel. I will write it as a new issue.
