### ISSUE TITLE
Performance drop issue when compiling & loading kernel using method Info

### ISSUE THREAD

**Issue by faruknane** [m4rs-mt/ILGPU#434]
The code below prints
```
Performing operations on GeForce GTX 1050 Ti [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 4294967296]
24,25
```
in my computer which has gtx 1050 ti, which is almost the same with cuda (cuda 24.5ms etc). 

```csharp
    class Program
    {
        public static void Kernel3(
              Index1 index,
              ArrayView<float> res,
              ArrayView<float> arr1,
              ArrayView<float> arr2)
        {
            res[index] = arr1[index] + arr2[index];
        }

        static void Main()
        {
            const int DataSize = 200000000;

            float[] a = new float[DataSize];
            GCHandle.Alloc(a, GCHandleType.Pinned);
            for (int i = 0; i < DataSize; i++)
            {
                a[i] = 5;
            }


            using (var context = new Context())
            {
                using (var accelerator = new CudaAccelerator(context))
                {
                    Console.WriteLine($"Performing operations on {accelerator}");
                    var kernel = accelerator.LoadAutoGroupedStreamKernel<
                            Index1, ArrayView<float>, ArrayView<float>, ArrayView<float>>(Kernel3);

                    using (var buffer = accelerator.Allocate<float>(DataSize))
                    using (var buffer2 = accelerator.Allocate<float>(DataSize))
                    using (var buffer3 = accelerator.Allocate<float>(DataSize))
                    {
                        buffer2.CopyFrom(a, 0, 0, DataSize);
                        buffer3.CopyFrom(a, 0, 0, DataSize);

                        for (int i = 0; i < 5; i++)
                        {
                            //kernel.Launch<Index1>(accelerator.DefaultStream, buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            kernel(buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            accelerator.Synchronize();
                        }

                        Stopwatch s = new Stopwatch();
                        s.Start();
                        for (int i = 0; i < 100; i++)
                        {
                            //kernel.Launch<Index1>(accelerator.DefaultStream, buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            kernel(buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            accelerator.Synchronize();
                        }
                        s.Stop();
                        Console.WriteLine(s.ElapsedMilliseconds / 100.0f);

                        //var data = buffer.GetAsArray();
                        //for (int i = 0; i < DataSize; i++)
                        //    Console.Write(data[i] + " ");
                        //Console.WriteLine();
                    }
                }
            }
        }
    }
```

--------------------------------------------------------------------------------------------------------------------------------

However, the code below prints 
```
Performing operations on GeForce GTX 1050 Ti [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 4294967296]
31,05
```

```csharp
    class Program
    {
        public static void Kernel3(
              Index1 index,
              ArrayView<float> res,
              ArrayView<float> arr1,
              ArrayView<float> arr2)
        {
            res[index] = arr1[index] + arr2[index];
        }

        static void Main()
        {
            MethodInfo method = typeof(Program).GetMethod("Kernel3"); //dt.GetMethod("Factory");

            const int DataSize = 200000000;

            float[] a = new float[DataSize];
            GCHandle.Alloc(a, GCHandleType.Pinned);
            for (int i = 0; i < DataSize; i++)
            {
                a[i] = 5;
            }


            using (var context = new Context())
            {
                using (var accelerator = new CudaAccelerator(context))
                {
                    Console.WriteLine($"Performing operations on {accelerator}");
                    var backend = accelerator.Backend;
                    var entryPointDesc = EntryPointDescription.FromImplicitlyGroupedKernel(method);
                    var compiledKernel = backend.Compile(entryPointDesc, default);

                    using (var kernel = accelerator.LoadKernel(compiledKernel))

                    using (var buffer = accelerator.Allocate<float>(DataSize))
                    using (var buffer2 = accelerator.Allocate<float>(DataSize))
                    using (var buffer3 = accelerator.Allocate<float>(DataSize))
                    {
                        buffer2.CopyFrom(a, 0, 0, DataSize);
                        buffer3.CopyFrom(a, 0, 0, DataSize);

                        for (int i = 0; i < 5; i++)
                        {
                            kernel.Launch<Index1>(accelerator.DefaultStream, buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            //kernel2(buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            accelerator.Synchronize();
                        }

                        Stopwatch s = new Stopwatch();
                        s.Start();
                        for (int i = 0; i < 100; i++)
                        {
                            kernel.Launch<Index1>(accelerator.DefaultStream, buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            //kernel2(buffer.Length, buffer.View, buffer2.View, buffer3.View);
                            accelerator.Synchronize();
                        }
                        s.Stop();
                        Console.WriteLine(s.ElapsedMilliseconds / 100.0f);

                        //var data = buffer.GetAsArray();
                        //for (int i = 0; i < DataSize; i++)
                        //    Console.Write(data[i] + " ");
                        //Console.WriteLine();
                    }
                }
            }
        }
    }
```

what might be the reason for this performance drop?

**Comment by m4rs-mt** [comment]
In the first scenario, you use a strongly typed and optimized launcher generated by the ILGPU runtime system. This type of launcher ensures the highest possible performance because ILGPU dynamically generates the appropriate MSIL (and thus X86/X64 using .Net JIT) instructions for you to realize the kernel dispatch. In the second case, you use the slow untyped direct launch functionality of kernels (which is not recommended). This function receives a parameter array (`params object[] args`), which causes all parameters to be automatically boxed. This in turn consumes time and increases GC pressure.

**Comment by faruknane** [comment]
@m4rs-mt I don't agree with you on the boxing issue. Boxing is not that time-consuming. If it were, when the data size is small, it would still create the same overhead because of boxing which is not the case. There is no time difference in small data sizes. 

Also, when I test this on CPU both scenarios are taking an equal amount of time. Does it suggest that maybe GPU code is being generated differently as you mentioned? If this is the case, I don't understand why generated code is different. Both scenarios contain the same function with the same body with the same IL codes. In the end, you use methodinfo/methodbody in your library as well in order to get IL Code? It just doesn't feel right. Could you be able to check if their PTX code somehow different?

**Comment by m4rs-mt** [comment]
> Boxing is not that time-consuming.

It is an expensive operation in terms of HPC applications. It causes cache misses and increases GC pressure in general. I did not claim that this is the problem in your case 🤓. In other words: if you want to have reliable time measurements and an HPC-capable application you have to minimize potential GC-related issues 🚀 

> Does it suggest that maybe GPU code is being generated differently as you mentioned?

I have to take a closer look at your example to give you more details 😃 I also don't follow your argument that the PTX code will be different, since ILGPU uses the same compilation pipeline in both cases and the emitted code is identical in your example in both cases:
```asm
//
// Generated by ILGPU v0.10.0
//

.version 7.1
.target sm_86
.address_size 64

.visible .entry Kernel_Kernel3(
	.param .b32 _index_70,
	.param .align 8 .b8 _res_71[16],
	.param .align 8 .b8 _arr1_72[16],
	.param .align 8 .b8 _arr2_73[16]
)
{
	.reg .pred	%p<2>;
	.reg .b32	%r<6>;
	.reg .b64	%rd<11>;
	.reg .f32	%f<4>;

	ld.param.b32	%r2, [_index_70];
	ld.param.b64	%rd1, [_res_71];
	ld.param.b64	%rd2, [_res_71+8];
	ld.param.b64	%rd3, [_arr1_72];
	ld.param.b64	%rd4, [_arr1_72+8];
	ld.param.b64	%rd5, [_arr2_73];
	ld.param.b64	%rd6, [_arr2_73+8];
	mov.b32	%r3, %ctaid.x;
	mov.b32	%r4, %ntid.x;
	mov.b32	%r5, %tid.x;
	mad.lo.s32	%r1, %r3, %r4, %r5;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 ret;

	L_680:
	mul.wide.u32	%rd8, %r1, 4;
	add.u64	%rd7, %rd1, %rd8;
	mul.wide.u32	%rd9, %r1, 4;
	add.u64	%rd8, %rd3, %rd9;
	ld.global.f32	%f1, [%rd8];
	mul.wide.u32	%rd10, %r1, 4;
	add.u64	%rd9, %rd5, %rd10;
	ld.global.f32	%f2, [%rd9];
	add.f32	%f3, %f1, %f2;
	st.global.f32	[%rd7], %f3;
	ret;
}
```

I can hook up a profiler tomorrow to find the potential bottlenecks in the second example that are not present in the first scenario 👍.

**Comment by m4rs-mt** [comment]
@faruknane I found the performance issue in your program: You use the automatic grouping functionality of ILGPU in the first program (with `LoadAutoGroupedKernel`). However, implicitly grouped kernels should not be loaded with `LoadKernel`, as in your second example. This will result in an implicit grouping with a `groupSize = 32` (the `WarpSize`) as an automatic fallback. Using `LoadAutoGroupedKernel` in the second scenario fixes the major performance differences:

```c#
using (var kernel = accelerator.LoadAutoGroupedKernel(compiledKernel))
```

Regarding boxing: I benchmarked the overhead of Boxing + the Reflection API in the context of the kernel launcher (*Please note that the unsafe kernel launcher (with `kernel.Launch`) also uses a reflection call to invoke underlying optimized launcher*). Boxing itself adds an overhead of approx. 4x-8x to the launcher. However, the full launcher adds an overhead of 7x-18x, depending on your hardware configuration (measured on different machines including an AMD Ryzen 3950X). I measured the following numbers using the median execution time of 10,000 calls:
```c#
Raw launcher code without invoking the kernel:
Boxed unsafe launcher: 0.0027649ms to 0.0038812ms
Optimized type-safe launcher: 0.0001481ms to 0.0005121ms
```

**Comment by faruknane** [comment]
@m4rs-mt 
I dived into the library and as you said, WarpSize is automatically assigned to GroupSize. Thank you again 😄 !
![image](https://user-images.githubusercontent.com/37745467/111347442-45d60a80-8690-11eb-9aa1-f73ce26c9192.png)

For boxing, I want to ask you - because I am at beginner-level - is the execution time result long enough that it does really matter? ~0.003ms seems like a really short time. 

Because things that I work on are dynamic nowadays, I feel like I have to use boxing. I can't go with generic classes etc. I'm not good at generics also. In some cases, you just want to get an instance of a generic class, you have to use a non-generic function of that generic instance but you can't get the instance because you need to specify a generic type before using it. It's annoying for me sometimes 😄. Probably, I am not able to use it efficiently. 

I started to code mergeable tensor operations. There are some mergeable kernels (element-wise operations) and non-mergeable kernels (matrix mul operation etc). I feel like I have to create a base 'Operation.cs' for both mergeable and non-mergeable operations to inherit from. However, there are a lot of operations whose operands don't have the same type. Hence, I can't assume that if the result tensor of an operation is float, then the operands are also float. 

I made the result type is generic in my case but my operands' types are unknown. I went with object[]. Again, it needs boxing. I don't know if it can be solved with generic types?
![image](https://user-images.githubusercontent.com/37745467/111357982-e16c7880-869a-11eb-9b07-0e480c9a4ff5.png)

**Comment by m4rs-mt** [comment]
> For boxing, I want to ask you - because I am at beginner-level - is the execution time result long enough that it does really matter? ~0.003ms seems like a really short time.

It always depends on the use case. In your case, you want to map generic operations and unbox them while passing them to the kernel at a particular time. However, if we consider boxing in the context of the kernel launcher, we sacrifice a non-deterministic amount of time for boxing and unboxing. In your case, on the other hand, the launcher only needs to perform unboxing, which is less expensive with a "less non-deterministic performance characteristic".

> I made the result type is generic in my case but my operands' types are unknown. I went with object[]. Again, it needs boxing. I don't know if it can be solved with generic types?

I guess there is no way around boxing in your scenario as you want to make your representation as generic as possible. Even within ILGPU boxing cannot be avoided when it comes to constant values within the IR.
