### ISSUE TITLE
Compiling kernel with constant switch condition generates incorrect OpenCL code.

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#441]
When compiling a kernel with a `switch` statement that has a constant condition, the OpenCL code generator produces incorrect code.

The following is an example kernel:
```CSharp
public static void ConstantSwitchKernel(Index1 index, ArrayView<double> output)
{
    var mode = 3;
    output[index] = mode switch
    {
        1 => 1.0,
        2 => 2.0,
        3 => 3.0,
        _ => 0.0
    };
}
```
The OpenCL code generator ends up producing code similar to:
```CPP
switch (var19)
{
case 0:
    goto L_1065;
case 1:
    goto L_1064;
case 2:
    goto L_1063;
default:
    goto L_1066;
}
```
with a compiler error of:
```
error: use of undeclared identifier 'var19'
        switch (var19)
                ^
```

 In particular, it only affects `OptimizationLevel.Debug`. This is because the other optimisation levels include the `UnreachableCodeElimination` transformation which will detect the constant condition and fold/remove the `switch` statement.

NOTE: The `ConstantSwitchKernel` kernel only fails when there are at least 4 conditions. If there are less conditions, the C# compiler converts the `switch` statement into if/else statements.

**Comment by m4rs-mt** [comment]
@MoFtZ Looks like the constant of the switch condition is not output properly...

**Comment by MoFtZ** [comment]
@m4rs-mt Yes, we already handle this for constant `if` statements, but not for constant `switch` statements. Working on a fix now.
