### ISSUE TITLE
Multidimensional Index comparison operator documentation is ambiguous

### ISSUE THREAD

**Issue by Nnelg** [m4rs-mt/ILGPU#450]
The comparison operators (specifically >, <. >=, <=) for Index2 etc. are simply documented "Returns true if the first index is smaller than the second index."

It isn't clear if this is supposed to mean `(a < b) => (a.X < b.X && a.Y < b.Y)` or `(a < b) => (a.Size < b.Size)` or something else entirely.

It's even more confusing when including the possibility of `(a.X > b.X && a.Y < b.Y)`; would `(a <= b) || (a >= b)` resolve `false`?

*Just to be clear here, I'm not creating this issue to ask the question, I'm creating it to suggest that the documentation be expanded.*

**Comment by m4rs-mt** [comment]
@Nnelg Thanks for the feedback. We should definitely improve this. Either improve the documentation or remove the comparison operators to avoid programming issues in general.
