### ISSUE TITLE
Code Style Error CS0457: ambiguous conversion (LongIndex2->Index2)

### ISSUE THREAD

**Issue by Nnelg** [m4rs-mt/ILGPU#451]
## Description

(On Visual Studio 2019)

`CS0457`

Ambiguous user defined conversions 'LongIndex2.explicit operator Index2(LongIndex2)' and 'Index2.implicit operator Index2(LongIndex2)' when converting from 'LongIndex2' to 'Index2'

## To Reproduce:

```var idx = (Index2)(new LongIndex2());```

## Notes

Yes, I have a case where this is necessary... It's needed to disambiguate between the Index2 and LongIndex2 versions of arithmetic operators. It's really just an inconvenience for coding...

The same thing happens with (Long)Index3, but apparently *not* (Long)Index1.

## Suggested Fix

Best practice would be to remove the implicit operator, as this conversion loses precision.

For backwards-compatibility, you could add the following to `MemoryBuffer2D<T>`:
```
new public Index2 Extent => (Index2)base.Extent;
public LongIndex2 LongExtent => base.Extent;
```

**Comment by m4rs-mt** [comment]
@Nnelg this has been introduced to be backwards compatible. PR #421 will not contain these casts any more.
