### ISSUE TITLE
When can ilgpu provide parallel syntax function similar to alea GPU framework？

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#455]
When can ilgpu provide parallel syntax function similar to alea GPU framework, which can support implicit conversion between variables and arrayview
like
```c#
using Alea.Parallel;
Alea.Parallel.GpuExtension.For(gpu, 0, Points.Count, i =>
{
    xComponent[i] = xComponent[i] - minX;
    yComponent[i] = yComponent[i] - minY;
    zComponent[i] = zComponent[i] - minZ;
});


var gpu = Gpu.Default;
var arg1 = Enumerable.Range(0, Length).ToArray();
var arg2 = Enumerable.Range(0, Length).ToArray();
var result = new int[Length];

gpu.For(0, result.Length, i => result[i] = arg1[i]   arg2[i]);
```

**Comment by m4rs-mt** [comment]
@xxl-cc Thank you for your feature request. Support for implicit lambda captures would be possible once we add support for lambda functions and constant value arrays. Currently, there are no plans to add support for implicit memory transfers to GPUs as they can have unintended side effects. In addition, Alea also suffers from incomplete support in terms of by-ref captures and various array value references.

**Comment by m4rs-mt** [comment]
We have recently added support for automatic transfer of "constant" array values in #419. Once we have extended support for lambda functions (parts of this feature request are also tracked in #455), you will be able to write similar programs in ILGPU v1.1 or v1.2 😍.
