### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by CsabaStupak** [m4rs-mt/ILGPU#456]
I'm trying to replace my existing code which uses _MathNet.Numerics_ (and its _MKL.Win-x64_ extension) library for Matrix manipulation. My code has about _300x300 size_ matrices and do several multiplication, addition over these matrices. On my _CPU (i7-8086K @ 4GHz)_ it takes about **1713 ms** to finish (the simplified version).

I decided to switch the code using _ILGPU Blas_ part using _CuBlas.Gemm_, _CuBlas.Geam_ functions. What surprised me that it took **57300 ms** (**~33! slower**) on my _GeForce GTX 1050_. The GPU is utilized 80% and the CPU 18%. 

I know the graphics card is not high-end, but did not expect such bad result. I tried to profile my code using VS CPU utilization but mostly the code sits in _Accelerator.Synchronize_ method - waiting the GPU to finish its function. 

I wonder if is there other mechanism to do profile - to see where the bottleneck is e.g. memory transfer, kernel compute, kernel start/compile, etc. Or simply I can't expect more from my GPU? 

Any help is appreciated :-) Thanks!

**Comment by MoFtZ** [comment]
@CsabaStupak I'm not familiar with CuBlas, but here are my thoughts for investigating the problem.
1. Are you using single-precision or double-precision floats? Your GPU may not be performant for double-precision.
2. Are you able to separately time the CuBlas API calls? It may not be super accurate, but might give a rough guide to which API call is causing the bulk of the performance hit. You might find that the compute performance is comparable, but the different in time is from copying the data to the GPU.
3. Are you using any of the ILGPU `Allocate2D` or `Allocate3D` methods? These have [known performance issues](https://github.com/m4rs-mt/ILGPU/issues/400).

**Comment by m4rs-mt** [comment]
@CsabaStupak we added basic profiling support with `ProfilingMarker` classes in PR #482. This should also fix parts of this problem. I recommend that we close this issue for now. If the problem persists, we can reopen this issue in the future 🤓.
