### ISSUE TITLE
Create XorShift128Plus in Kernel?

### ISSUE THREAD

**Issue by bnemetchek2** [m4rs-mt/ILGPU#462]
There was a previous issue/thread discussing generating large numbers of random values.  Is it possible to create a new XorShift128Plus in each thread using a seed?  The XorShift128Plus.Create function requires a parameter of Random which appears to not be a class allowable within a kernel.

i.e. the following code will result in a GPU compiler error at runtime
`var r = XorShift128Plus.Create(new Random(1));`

Error:  "Class type 'System.Random' is not supported"

**Comment by m4rs-mt** [comment]
The `XorShiftXYZ` structures are designed to be initialized on the CPU side with a specific seed. You can use the `RNG` class (an example can be found [here](https://github.com/m4rs-mt/ILGPU.Algorithms/pull/75)) to create an RNG provider on the CPU and use separate `XorShiftXYZ`-based instances in each thread of your kernel. Alternatively, you can populate an array of `ulong`s on the CPU and initialize the `XorShiftXYZ` structures in each thread with the predefined seeds.

**Comment by bnemetchek2** [comment]
Thanks for that info.  That's perfect.  Generating the seeds prior to the kernel call is very fast using FillUniform.
I wish I could have used the RNGView<XorShift128Plus> functionality as that is brilliantly implemented but I'm not yet using custom kenels, just an auto one.  

thanks again,
