### ISSUE TITLE
Partial scripting support?

### ISSUE THREAD

**Issue by chrisaliotta** [m4rs-mt/ILGPU#47]
Hello @m4rs-mt ,
It appears that Google forums is no longer publicly available so I will ask my question here.

I'm looking to provide partial scripting support in my application that will leverage ILGPU. The kernel definitions and data made available will all be uniform (meaning they will all have the same static method declaration and the same number of properties for each kernel); however, I'd like to allow for customization to be made within the body of these methods.

How might I be able to leverage Roslyn generated code and have it work with ILGPU?

The main purpose of this request is to allow engineers to change formulas without having to recompile the application.

Thanks again,
Chris

p.s - This is really an amazing library! Keep up the good work!

**Comment by m4rs-mt** [comment]
Hi, @chrisaliotta. Thanks for your feedback 👍 . The Google forums are no longer the primary contact. However, you can use the offered Discord channel to get instant support or feedback.

Regarding your question:
Yes, it is definitely possible to use code generated by Roslyn. However, what you need to do is compile the code into a runtime assembly. Afterwards, you have to resolve the desired entry point of the kernel method via Reflection and use the `LoadKernel` functionality of an accelerator class to compile and load your kernel via the Reflection API.

**Comment by chrisaliotta** [comment]
@m4rs-mt awesome! Thank you for getting back to me so quickly. I'm going to try to hack together an example and include it here for future reference. 👍 

I should have something within the next day or two :)

**Comment by chrisaliotta** [comment]
Here is my working example. It's kind of hacky, but should get others started. Thank you again for the tip!

I borrowed some Roslyn [code ](https://github.com/joelmartinez/dotnet-core-roslyn-sample/blob/master/Program.cs) from Joel Martinez to get this up and running quickly. 

See finished code file here:
[RoslynProgram.cs.txt](https://github.com/m4rs-mt/ILGPU/files/3860964/RoslynProgram.cs.txt)

**Comment by m4rs-mt** [comment]
@chrisaliotta nice work :) Yeah, definitely. However, we must ensure that we do not violate any copyright concerns regarding the "borrowed" code. I would recommend that we come up with a nice example that is completely free of any third-party code 🔢
