### ISSUE TITLE
Feature request: performance improvement for already pinned 1Dim arrays?

### ISSUE THREAD

**Issue by MarkusKuntner** [m4rs-mt/ILGPU#472]
From . Net5 onwards it is possible to pin arrays via GC.AllocateArray(). Unfortunately, as far as I know, there is no option to check whether the array is pinned. 
Is it possibile to generate an IntPtr for the already pinned memory using Fixed{} and thus to avoid one copy operation for integral and floating-point numeric type arrays? 
I see that ArrayViews are currently under development in #421, so perhaps that would be an additional option, although an unsafe one.
Congrats on that great project!

**Comment by MoFtZ** [comment]
I created a program to test the transfer times.

The four scenarios I tested were:
1. srcAlloc = Allocation using `new int[]`
2. srcToArray = Allocation using LINQ `.ToArray`
3. srcPinned = Allocation using `ExchangeBuffer`, which internally uses [cuMemAllocHost](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gdd8311286d2c2691605362c689bc64e0) to get pinned memory.
4. srcGcAlloc = Allocation using `GC.AllocateArray(pinned: true)`

On my GTX 1070, I transferring 256 MB multiple times.

I noticed that the first use for `srcAlloc` and `srcGcAlloc` took a long time - future accesses were faster.
The use of `srcToArray` and `srcPinned` was always the same speed, with pinned memory being twice as fast.

I am unsure why `srcToArray` would be fast on the first use. Perhaps @m4rs-mt knows?

```
Pass 1: srcAlloc    501 milliseconds passed
Pass 1: srcToArray  158 milliseconds passed
Pass 1: srcPinned    86 milliseconds passed
Pass 1: srcGcAlloc  447 milliseconds passed

Pass 2: srcAlloc    154 milliseconds passed
Pass 2: srcToArray  158 milliseconds passed
Pass 2: srcPinned    85 milliseconds passed
Pass 2: srcGcAlloc  161 milliseconds passed

Pass 3: srcAlloc    159 milliseconds passed
Pass 3: srcToArray  149 milliseconds passed
Pass 3: srcPinned    86 milliseconds passed
Pass 3: srcGcAlloc  154 milliseconds passed

Pass 4: srcAlloc    155 milliseconds passed
Pass 4: srcToArray  148 milliseconds passed
Pass 4: srcPinned    87 milliseconds passed
Pass 4: srcGcAlloc  152 milliseconds passed

Pass 5: srcAlloc    149 milliseconds passed
Pass 5: srcToArray  160 milliseconds passed
Pass 5: srcPinned    86 milliseconds passed
Pass 5: srcGcAlloc  157 milliseconds passed
```

PROGRAM SOURCE:
```CSharp
using System;
using System.Diagnostics;
using System.Linq;
using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;

namespace MemcpySpeed
{
    class Program
    {
        const int Length = 256 * 1024 * 1024;

        static void Main(string[] args)
        {
            var sw = new Stopwatch();
            using var context = new Context();
            using var accelerator = new CudaAccelerator(context);

            using var dst = accelerator.Allocate<int>(Length);
            var srcAlloc = new int[Length];
            var srcToArray = Enumerable.Repeat(0, Length).ToArray();
            var srcPinned = accelerator.AllocateExchangeBuffer<int>(Length);
            var srcGcAlloc = GC.AllocateArray<int>(Length);

            for (int i = 1; i <= 5; i++)
            {
                sw.Restart();
                dst.CopyFrom(accelerator.DefaultStream, srcAlloc, 0, 0, Length);
                accelerator.DefaultStream.Synchronize();
                sw.Stop();
                Console.WriteLine($"Pass {i}: srcAlloc   {sw.ElapsedMilliseconds,4} milliseconds passed");

                sw.Restart();
                dst.CopyFrom(accelerator.DefaultStream, srcToArray, 0, 0, Length);
                accelerator.DefaultStream.Synchronize();
                sw.Stop();
                Console.WriteLine($"Pass {i}: srcToArray {sw.ElapsedMilliseconds,4} milliseconds passed");

                sw.Restart();
                srcPinned.CopyToAccelerator(accelerator.DefaultStream);
                accelerator.DefaultStream.Synchronize();
                sw.Stop();
                Console.WriteLine($"Pass {i}: srcPinned  {sw.ElapsedMilliseconds,4} milliseconds passed");

                sw.Restart();
                dst.CopyFrom(accelerator.DefaultStream, srcGcAlloc, 0, 0, Length);
                accelerator.DefaultStream.Synchronize();
                sw.Stop();
                Console.WriteLine($"Pass {i}: srcGcAlloc {sw.ElapsedMilliseconds,4} milliseconds passed");

                Console.WriteLine();
            }
        }
    }
}

```

**Comment by MarkusKuntner** [comment]
Thanks for your work, this hits the nail on the head! 

The goal would be to reach the performance of `ExchangeBuffer` using an array.
As far as I understand the way ILGPU works, an array must be copied to a pinned memory area before it can be transferred to or from the GPU with `.CopyTo`  or `.CopyFrom`. Otherwise, a GC could move the memory, which would result in an invalid memory access.
Using GC.AllocateArray(Length, true) creates a pinned memory secure from the GC. I'm only getting familiar with the way the GPU works, but such an array could perhaps be transferred directly to the GPU without having to create a marshalled memory using `Marshal.AllocHGlobal` like done in the ILGPU `CPUMemoryBuffer` class.
 
But this would need a new command like `.CopyToPinned` or `CopyFromPinned`. The `Fixed{}` statement should be cheap for pinned arrays and it should be possible, to generate an IntPrt for the compatibility to the existing approach.  
But maybe it is already possible to pass pinned memory areas to ILGPU. 

The usage of pinned arrays is unsafe in a certain view, because it is not possible to check whether the array is actually pinned and the user can set an array to null. But if the user knows what he is doing, the array is safe from the GC and so are memory accesses. Perhaps a performance gain could be achieved with this.

**Comment by m4rs-mt** [comment]
@MarkusKuntner thank you for your comments and hints 🚀 Regarding `ExchangeBuffer` performance, it is only possible to copy to and from page-locked (non-pageable) memory in a highly efficient way. Correct me if I am wrong, but I assume that `GC.AllocateArray(pinned: true)` allocates a pinned array in pageable memory with respect to the RAM managed by the parent OS. If so, then we can at least benefit from the reduced overhead of pinned arrays with respect to the GC.

**Comment by MoFtZ** [comment]
@MarkusKuntner @m4rs-mt
With the test program I used above, it is not enough for the memory to be pinned.

I did not include it in the example, but using `GCHandle.Alloc(array, GCHandleType.Pinned)` to pin the memory does not improve the performance. The reason appears to be that CUDA is using an internal list to detect pinned memory rather than querying the OS.

I have found the function [cuMemHostRegister](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gf0a9fe11544326dabd743b7aa6b54223), which will add to this internal list, and tell CUDA "trust me, the memory is pinned". In my initial tests, this appears to work on `GC.AllocateArray(pinned: true)`.

I will investigate a bit more, and then maybe write up a PR.

**Comment by m4rs-mt** [comment]
@MoFtZ However I still believe that `managed pinned memory != page-locked memory` 🤓 Therefore, using `cuMemHostRegister` can have unintended side effects when the memory will be swapped out by the OS.

**Comment by MarkusKuntner** [comment]
@m4rs-mt I am with you that a pinned array is not safe. However, with `Fixed{}`, which is cheap for pinned arrays, swapping should be avoided.
@MoFtZ This approach is promising because this is not only faster, but also involves lower memory consumption. 
If this really works, thinking far ahead, a thin ILGPU wrapper for `GC.AllocateArray<T>` and `GC.AllocateUninitializedArray<T>` would be possible. This would also allow ILGPU to catch the pitfalls of unpinned or deleted arrays. So one could also create an overload for the existing commands `.CopyTo` and `.CopyFrom`.
