### ISSUE TITLE
Group.IsFirstThread bug

### ISSUE THREAD

**Issue by CsabaStupak** [m4rs-mt/ILGPU#473]
I have a kernel which processes 2D arrays. The simplified version computes a sum of the 2D array elements as follows:

```c#
void MyKernel(ArrayView2D<float> xMat, ArrayView2D<float> oMat)
{
	var shared = SharedMemory.GetDynamic<float>();
	shared[0] = 0;
	Group.Barrier();
	
	Atomic.Add(ref shared[0], xMat[Grid.GlobalIndex);
	
	Group.Barrier();
	
	if (Group.IsFirstThread)
		oMat[0, 0] = shared[0];
}
```

Here is the kernel config code:

```c#
private KernelConfig ComputeConfig(MemoryBuffer3D<float> xMat)
{
	Index3 groupDim = new Index3((int)xMat.Width, (int)xMat.Height, 1);
	Index3 groupNum = new Index3(1, 1, 1);

	var memConfig = SharedMemoryConfig.RequestDynamic<float>(1);
	return new KernelConfig(groupNum, groupDim, memConfig);
}
```

I invoke this kernel with _2x2_ array and it returns 2x sum what is incorrect. The problem is that `Group.IsFirstThread` returns _TRUE_ for _index = [0,0]_ and _[0,1]_, while I would expect it would return _TRUE_ only for `[0,0]` index.

It looks like the `Group.IsFirstThread` returns _TRUE_ if the first _X dimension == 0_.
Is it a bug or feature? :-)

Thanks, Csaba

**Comment by m4rs-mt** [comment]
@CsabaStupak Thank you for your issue report. Indeed, `Group.IsFirstThread` currently checks only the first thread in the `X` dimension and ignores the `Y` and `Z` dimensions (see https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/Group.cs#L163). Well, you can argue that this is a feature and not a bug.... 🤔. However, it is a potential source of bugs and we should definitely change this behavior.

**Comment by MoFtZ** [comment]
Currently, ILGPU performs compilation on each method in parallel, and the methods are not aware of other details like the entry point function. If we could add that information to the compilation, it would be possible to specialise the implicitly grouped kernels.
