### ISSUE TITLE
Can ILGPU support cufftw

### ISSUE THREAD

**Issue by xichaoqiang** [m4rs-mt/ILGPU#474]
Can ILGPU support cufftw?

**Comment by Yey007** [comment]
As far as I know, it is not supported at the moment but I don't think the devs will be completely against adding support sometime in the future. It probably won't be soon, though, given that there is a lot of work being done on other features (I think the OptiX experiments are still going, not sure).

**Comment by MoFtZ** [comment]
@xichaoqiang ILGPU does not currently provide .NET bindings for CUFFTW. However, it should be possible to add these bindings in the future, similar to the CuBlas bindings in [ILGPU.Algorithms](https://github.com/m4rs-mt/ILGPU.Algorithms).

If you are familiar with how to [generate .NET bindings to unmanaged DLLs](https://docs.microsoft.com/en-us/dotnet/framework/interop/consuming-unmanaged-dll-functions), you could try integrating CUFFTW into your application with the currently available ILGPU.
