### ISSUE TITLE
ReinterpretCast in ILGPU 0.6

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#48]
Hello,
In the process of migrating from ILGpu 0.3 to ILGpu 0.6, the following "trick" I used to reinterpret int to float and float to int doesn't work any more :

    /// <summary>
    /// https://stackoverflow.com/questions/173133/how-to-reinterpret-cast-a-float-to-an-int-is-there-a-non-static-conversion-oper
    /// </summary>
    public static class ReinterpretCastExtensions {
        public static unsafe float AsFloat( this int n ) => *(float*)&n;
        public static unsafe int AsInt( this float n ) => *(int*)&n;
    }

	class ILGpuTest
    {

        [Test]
        public void ReinterpretCastTest()
        {
            using (var context = new Context())
            {
                using (var gpu = new CudaAccelerator(context, 0))
                {
                    var cpuArray = new float[2];
                    cpuArray[0] = 3.14f;
                    cpuArray[1] = 1888888888.AsFloat();
                    var gpuArray = gpu.Allocate<float>(2);
                    gpuArray.CopyFrom(gpu.DefaultStream, cpuArray, 0, 0, 2);
                    var kernel = gpu.LoadKernel<GroupedIndex, ArrayView<float>>(ReinterpretCast_Kernel);
                    kernel(gpu.DefaultStream, new GroupedIndex(1, 1), gpuArray);
                    var result = gpuArray.GetAsArray(gpu.DefaultStream);
                    Assert.AreEqual(4.14f, result[0], 0.000001f);
                    Assert.AreEqual(1888888889, result[1].AsInt());
                }
            }
        }

        private static void ReinterpretCast_Kernel(GroupedIndex index, ArrayView<float> array)
        {
            array[0]++;
            int myInt = array[1].AsInt();
            array[1] = (myInt + 1).AsFloat();
        }
    }
	
This kernel was working in ILGPU 0.3 but does not compile in ILGPU 0.6.
Is there a workaround I can use to reinterpret float to int in the kernel ?
Could such a feature be implemented in a future version of ILGPU ? (Maybe like the Reinterpret methods of Alea GPU)

**Comment by m4rs-mt** [comment]
@samy2 You can use the `Interop.FloatAsInt` and `Interop.IntAsFloat` functions to do exactly the same. However, they will be mapped to intrinsics (if possible) and are supported by all ILGPU backends.

**Comment by samy2** [comment]
Oh great !! Thanks a lot.
