### ISSUE TITLE
F me

### ISSUE THREAD

**Issue by branc116** [m4rs-mt/ILGPU#487]
Dude!
You are a fucking maniac! I fing love You for makeing this! This is awesome lib. When I first found out this lib and you I was in aww. No joke! I wanted to tell you this for a long time, but I can't seem to find your contact anywhere. Keep on doing what you are doing and if you are ever in Zagreb in croatia call me for a beer 🍻 And sorry for issue :)

**Comment by MPSQUARK** [comment]
There is a contact link to the discord on the ILGPU website. 
ILGPU website : https://www.ilgpu.net/
Discord : https://discord.com/invite/X6RBCff
Reddit : https://www.reddit.com/r/ILGPU/

**Comment by m4rs-mt** [comment]
Thanks a lot for your highly motivating comments ❤️ If you prefer a private communication channel, you can always email `ilgpucompiler@gmail.com` 🤓.
