### ISSUE TITLE
1.0beta1 throw  Exception when run  context.EnableAlgorithms()

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#490]
Is the function calling mode changed in the new version?

**Comment by m4rs-mt** [comment]
@xxl-cc Unfortunately, we are still working on making the Algorithms library compatible with the next ILGPU release (you can track the progress [here in PR #85](https://github.com/m4rs-mt/ILGPU.Algorithms/pull/85).

**Comment by m4rs-mt** [comment]
@xxl-cc We are currently working on a v1.0-beta1 release of the `Algorithms` library that will be compatible with the upcoming ILGPU v1.0-beta2 🤓

**Comment by m4rs-mt** [comment]
We have released a v1.0-beta1 of the algorithms library which is fully compatible with the v1.0-beta1 ILGPU version 🥳.
