### ISSUE TITLE
Regression in writing to field of structure causing Cuda misaligned address in v1.0-beta1

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#493]
A community member has reported a regression in v1.0-beta1.
Previously worked in v0.10.0.

The issue is that assigning a value to `Fifth` in the data structure is generating `CudaException: 'misaligned address'` at runtime.

The reduced version is below. Uncommenting `Fourth` alters the structure layout, and the misalignment does not occur.
```CSharp
namespace Test
{
    public class Program
    {
        public struct MyData
        {
            public byte[] First;
            public int Second;
            public int Third;
            //public int Fourth;
            public long Fifth;
        }

        public static void MyKernel(Index1D index, ArrayView<long> view)
        {
            var d = new MyData();
            d.Fifth = 42;   // <-- misaligned address here
            view[index] = d.Fifth;
        }

        static unsafe void Main()
        {
            using var context = Context.Create(x => x.Default());
            using var accelerator = context.CreateCudaAccelerator(0);
            using var buffer = accelerator.Allocate1D<long>(1024);

            var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<long>>(MyKernel);
            kernel((int)buffer.Length, buffer.View);
            accelerator.Synchronize();
        }
    }
}
```

This appears related to the recent changes for [multi-dimensional arrays and constant arrays](#479 ).

**Comment by m4rs-mt** [comment]
An analysis of this issue revealed that we need to revise some of the functions implemented in #479. The current implementation lowers array types in the frontend during the first code generation phase. Instead, we should try to keep array types as long as possible and lower them later on when we are done with all further optimization steps (before passing the IR to one of the backends).
