### ISSUE TITLE
Load buffer from pointer missing

### ISSUE THREAD

**Issue by terraslate** [m4rs-mt/ILGPU#494]
Great project btw. Some performance tweaks wouldn't go amiss however, such as when using System.Drawing.Bitmap I often already have a Bitmap instance and using lockbits i can gain access to the underlying pixel data in the instance as a pointer (Using Scan0). I would wish to copy this directly to the GPU memory without first having to copy it to an array and then copy it from the array to the accelerator. If we are programming for performance and for the GPU we can probably handle a few unsafe functions that allow us to use existing pointers to load data and gain performance by it.

**Comment by terraslate** [comment]
Noted LoadEffectiveAddress on CPUView does the trick.

**Comment by MoFtZ** [comment]
hi @terraslate.
`Span<T>` also has a constructor that accepts a pointer and length, that can be used with ILGPU.
