### ISSUE TITLE
Cannot get result of XMath.Atsn2 as element of ArrayView

### ISSUE THREAD

**Issue by Sarkozyh** [m4rs-mt/ILGPU#495]
I need to get an array of Atan2 result values. When I try to do so I get ILGPU.Runtime.Cuda.CudaException: "a PTX JIT compilation failed". However if I just calculate values and don't try to get them as ArrayView elements everithing works fine.

Here is my Kerne

static void MyKernel(Index1 index,  ArrayView<double> res, ArrayView<int> values) 
        {
            double d1 = XMath.Sqrt(2) * (values[index] - values[index + res.Length * 4]);
            double d3 = XMath.Sqrt(2) * (values[index + res.Length * 6] - values[index + res.Length * 2]);
            double d2 = values[index + res.Length] - values[index + res.Length * 3] - values[index + res.Length * 5] + values[index + res.Length * 7];
            double d4 = - 1 * values[index + res.Length] - values[index + res.Length * 3] + values[index + res.Length * 5] + values[index + res.Length * 7];
            double X = (d1 + d2) / 2;
            double Y = (d3 + d4) / 2; 
            res[index] = XMath.Atan2(Y, X);
        }

**Comment by MoFtZ** [comment]
@Sarkozyh what version of ILGPU and ILGPU.Algorithms are you using?

ILGPU v0.9.2 works with ILGPU.Algorithms v0.9.2.

ILGPU v0.10.2 requires ILGPU.Algorithms v0.10.0-beta1.

**Comment by Sarkozyh** [comment]
Thank you! I've change my ILGPU version and it worked.
