### ISSUE TITLE
I could not compile the tag v0.7.0

### ISSUE THREAD

**Issue by nguyenvuduc** [m4rs-mt/ILGPU#52]
Hi,

Might I get your help in compiling the code?
I have downloaded Visual Studio 2019 and checkout the tag v0.7.0
I got so many compilation errors. At first glance, I thought this might be because I have a different development environment. However I found this piece of code which make me suspect that this code is not actually ready for compilation.

![image](https://user-images.githubusercontent.com/5864656/70824381-63d30200-1d9f-11ea-9ab5-11a4d1d31d6c.png)

As you can see, the ```Acclerator.DefaultStream``` is trying to access to a non-static field by using static access, it is weird that you can compiled it and pushed it to Nuget.

Hope to hear from you soon.
By the way, your work is awesome. I have tried cross platform GPU solutions made by Julia's CuArray, Python's Numba, and I found ILGPU is a lot easier to use.

Thank you.

**Comment by 12345swordy** [comment]
You need to run all t4 templates before you can compile the code.

**Comment by m4rs-mt** [comment]
@nguyenvuduc Thank you for your feedback and your bug report. It seems that the T4 templates have not been translated correctly (see @12345swordy's comment). Please make sure that you translate all T4 templates first before compiling the project.

**Comment by nguyenvuduc** [comment]
Thank @12345swordy and @m4rs-mt for your help.

The cause is I did run the T4 Custom Tool on some tt files but not all of them as you said. I ignored the tt files that already have associated cs files. In addition, the ILGPU project need to be unload and then reload after the custom tool is run.

**Comment by m4rs-mt** [comment]
Unfortunately there are almost always several problems related to T4 templates in general. I will change the extension of T4 include files to "ttinclude". However, this has caused problems with VS17 in the past. Anyway, these problems seem to be solved right now.
