### ISSUE TITLE
Enable CodeQL and DependaBot

### ISSUE THREAD

**Issue by ljubon** [m4rs-mt/ILGPU#539]
CodeQL: https://github.com/github/codeql-action#codeql-action
DependaBot: https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates

**Comment by m4rs-mt** [comment]
@ljubon Thanks a lot for your issue request and your PRs 🤓 I have to admit that I am not familiar with the `CodeQL` code analysis step. What are the benefits of having this additional analysis pipeline?

**Comment by ljubon** [comment]
Hey @m4rs-mt, with the current implementation we are using default/standard CodeQL scanning job (free) which is automating security checks. 
A nice feature they have is that we can also write our own queries and run them against our code, also code is treated like data so security vulnerabilities, bugs, and other errors are modeled as queries and they can be executed against the main CodeQL databases or our own.
The biggest benefit i can mention is that we can have scheduled runs that will generate reports for us in Security tab (e.g [like this one](https://github.com/ljubon/armada/security/code-scanning))
