### ISSUE TITLE
Failing unit test on my machine

### ISSUE THREAD

**Issue by Joey9801** [m4rs-mt/ILGPU#548]
When I run the CUDA unit tests on my machine, `ILGPU.Algorithms.Tests.Cuda.CudaXMathTests_[Debug, O2, Release].TanhFloat` fail. The failing assertion is that `ILGPU.Algorithms.XMath.Tanh(float)` returns the same number as `System.MathF.Tanh` to 6 decimal places. They all fail with:
```
Expected: -0.99974597
Actual:   -0.9997448
```
Ie the CUDA kernel is only the same to 5dp.

My system specs:

> CPU: 3950x
> GPU: 3090FE
> OS: Windows 10 Pro 20H2 19042.1083
> GPU Driver: 466.47
> CUDA version: V11.0.221
> ILGPU version: Source @ e439944
> Dotnet SDK: 5.0.302

**Comment by m4rs-mt** [comment]
@Joey9801 Thank you for this issue report. @MoFtZ I think this test error may be related to the platform specific lowering and/or software implementation we are plugging in?

**Comment by MoFtZ** [comment]
In the unit tests, the precision is really just a guide for what we can expect over a range of values. To get the tests passing on Joey9801's machine, we could lower the accuracy of the CUDA `tanh` unit test from 6 decimal places to 5 decimal places.

In `XMath`, we are using the following trigonometric identity to calculate [tanh](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU.Algorithms/PTX/PTXMath.cs#L326):
![image](https://user-images.githubusercontent.com/27792737/126887745-62267758-d021-49a1-9463-fab277dd1a3a.png)

Furthermore, we are using a [CORDIC](https://en.wikipedia.org/wiki/CORDIC) algorithm for computing the exponential. The CORDIC algorithm was chosen for ease of implementation. It is reasonably accurate, but is highly likely to have less accuracy than the algorithms used in Libm implementations.

Note that another trigonometric identity to calculate `tanh` is:
![image](https://user-images.githubusercontent.com/27792737/126888257-7b6e06b5-0fc1-4f9a-bf76-ee5f8a5e58a7.png)
And the `XMath` implementations for [sinh](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU.Algorithms/PTX/PTXMath.cs#L226) and [cosh](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU.Algorithms/PTX/PTXMath.cs#L285), both using the same CORDIC exponential algorithm, only have an accuracy to [4 decimal places](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU.Algorithms.Tests/XMathTests.Trig.tt#L43).

**Comment by m4rs-mt** [comment]
@MoFtZ I think that lowing the precision in the unit tests to 5 decimal places is fully acceptable for now. We can refine this implementation in the future. However, while thinking about `tanh`, we can also implement support for the newly added `PTX` intrinsic implementation that is available with CC >= 8.0.

**Comment by MoFtZ** [comment]
Wait a minute... we *did* add support for the [tanh intrinsic](https://github.com/m4rs-mt/ILGPU/pull/187). I think that's why the tests are failing - the 3090 is using the `tanh` intrinsic, which has lower precision that the software implementation.

We still need to lower the precision of the unit test, but this time, to support the hardware intrinsic.

**Comment by m4rs-mt** [comment]
@MoFtZ you are right 🚀
