### ISSUE TITLE
enable format code check in CI

### ISSUE THREAD

**Issue by ljubon** [m4rs-mt/ILGPU#552]
https://github.com/G-Research/gr-oss/issues/203

after working on CI for ILGPU (support .NET 5.0) I would like to suggest improvement in way of standardizing formatting code
We have .editorconfig for each project, which is cool for local setup but I would like to focus on CI formatting here

**Comment by m4rs-mt** [comment]
@ljubon Sounds like a good idea to me. However, I guess we all prefer a solution that does not change the underlying code style ILGPU uses and changes 6000+ lines in total, which makes it harder to have a reasonable code history. How can we adapt the code style tool to match the ILGPU formatting "rules"?

**Comment by ljubon** [comment]
@m4rs-mt usually this first formatting is the most painful since, as you said, we are changing lots of lines to comply with current rules. When I say rules I mean few rules we define in `ILGPU.DotSettings`. 
With experience from the last PR for formating code `ParquetSharp`... I'm expecting from you/team to let me know which rules you want to keep and/or which to add. You can do that simply by commenting on some changed lines and requesting to change/add/remove that change with future formating.

Please look at this as a process, once we polish things around we will review again changed code and agree on some final version :) Also, the goal of this PR/Issue is to format the current code in a way to be consistent, now and in the future so i expect that at the end we will have big change 💣 .
