### ISSUE TITLE
Samples not building

### ISSUE THREAD

**Issue by DanJBower** [m4rs-mt/ILGPU#560]
None of the samples appear to build

Seems to be for a few issues:

* Relative path to ILGPU source code projects are incorrect in the ProjectReferences.
* The ILGPU source code projects are not in the samples solution
* The samples appear to be written against an older version of the project

**Comment by DanJBower** [comment]
Would be happy to try fix the first two points over the weekend if it would help the project out

**Comment by m4rs-mt** [comment]
@DanJBower Yes that's right 🤓 We are still in an intermediate stage of translating the samples. I am going to write an issue about that describing the tasks ToDo. For now, you can stick to the sample in the separate [Samples](https://github.com/m4rs-mt/ILGPU.Samples) repository that are compatible with `v0.10.X`.

**Comment by DanJBower** [comment]
@m4rs-mt Thanks. Will check that repo out

**Comment by m4rs-mt** [comment]
@DanJBower I created an additional issue #562 summarizing the examples to be ported. Let's close this issue for now and continue possible discussions in the new issue/task description.
