### ISSUE TITLE
Port Samples to v1.0.X

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#562]
Currently we are on the "home stretch" regarding version `v1.0`. The most important parts of the API (should) be considered stable and frozen. This provides the opportunity to port all example projects from now on. The following example projects need to be ported:

- [x] AdjustableSharedMemory
- [x] AdvancedAtomics
- [x] AdvancedViews
- [x] AlgorithmsCuBlas
- [x] AlgorithmsGroups
- [x] AlgorithmsInitialize
- [x] AlgorithmsMath
- [x] AlgorithmsRadixSort
- [x] AlgorithmsReduce
- [x] AlgorithmsScan
- [x] AlgorithmsSequence
- [x] AlgorithmsTransform
- [x] AlgorithmsWarps
- [x] CustomIntrinsics
- [x] DeviceInfo
- [x] DynamicSharedMemory
- [x] Empty
- [x] EmptyAlgorithms
- [x] ExplicitlyGroupedKernels
- [x] GenericKernel
- [x] GroupGridIndices
- [x] ImplicitlyGroupedKernels
- [x] ~~IndexImplementation~~
- [x] LowLevelKernelCompilation
- [x] Mandelbrot
- [x] MatrixMultiply (~~affected by #567~~)
- [x] PinnedMemoryCopy
- [x] SharedMemory
- [x] SimpleAlloc
- [x] SimpleAtomics
- [x] SimpleConstants
- [x] SimpleKernel
- [x] SimpleMath
- [x] SimpleStructures
- [x] SimpleViews
- [x] SpecializedKernel
- [x] WarpShuffle

We are currently looking for additional volunteers that are motivated to upgrade the samples 😄 @MPSQUARK, @Yey007, @faruknane, @NullandKale, if you are interested and want to help us with this task this would be awesome 🥇🎉 

Please note that we should merge #561 first to fix invalid project references of all samples.

**Comment by MoFtZ** [comment]
I've ported the `Simple` folder in #563.

Going to start work on the `Algorithms` folder.

**Comment by m4rs-mt** [comment]
@MoFtZ, @MPSQUARK, @Yey007, @faruknane, @NullandKale while reviewing the examples I was wondering if we should update the language to "C# 8.0" (in quotes because not all functions are supported by all frameworks). At the very least, this would greatly simplify the "using" statements. What do you think?

**Comment by NullandKale** [comment]
I am always up for more language features. Plus this would better match my tutorials which use the new using syntax heavily.

**Comment by MoFtZ** [comment]
Sounds like a good idea. I was also thinking we might want to update the formatting to match the rest of ILGPU, and fix all warnings.

**Comment by m4rs-mt** [comment]
All open questions/tasks have been addressed in #584.
