### ISSUE TITLE
Regression when allocating 2D/3D SharedMemory inside kernel since ILGPU v1.0.0-beta1

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#567]
When compiling a kernel using `SharedMemory` to allocate 2D or 3D memory, ILGPU is throwing a `NotSupportedException` with the message `The allocation size of type 'Int32' must be statically known and not a dynamic value`.

The `SharedMemory.Allocate2D` and `SharedMemory.Allocated3D` functions were changed to accept `Index2D/Index3D` in the new Memory API, which appears to be causing an issue with the expectation of a constant value.

```CSharp
public class Program
{
    public const int DIM_X = 3;
    public const int DIM_Y = 5;

    public static void MyKernel(ArrayView<int> buffer)
    {
        var sharedMemory = SharedMemory.Allocate2D<int, Stride2D.DenseX>(new Index2D(DIM_X, DIM_Y), new Stride2D.DenseX(DIM_Y));
    }

    static unsafe void Main()
    {
        using var context = Context.CreateDefault();
        using var accelerator = context.CreateCudaAccelerator(0);

        var kernel = accelerator.LoadStreamKernel<ArrayView<int>>(MyKernel);
    }
}
```

**Comment by m4rs-mt** [comment]
We had similar problems with this kind of assignment scheme in the past. The problem was that the constants could not be propagated through all stages of the compiler until they reached the actual backend code generator.... I am going to look into it.

**Comment by MoFtZ** [comment]
What was the reason for changing the API to accept `Index2D`, rather than `int x, int y`?

**Comment by m4rs-mt** [comment]
@MoFtZ I analyzed the problem in detail and it turns out that ILGPU is not able to fold all conditionals inside the `ComputeBufferLength` call of the `Stride2D` type:
```asm
Entry_1728:
        const_1746: True [Int1]
        branch_1747: const_1746 ? BB_1731 : BB_1730
BB_1730:
        const_1748: 0 [Int32]
        branch_1749: BB_1734
BB_1731:
        const_1751: True [Int1]
        branch_1752: const_1751 ? BB_1733 : BB_1732
BB_1732:
        const_1753: 0 [Int32]
        branch_1754: BB_1734
BB_1733:
        const_1762: 23 [Int32]
        branch_1763: BB_1734
BB_1734:
        phi_1735: const_1748, const_1753, const_1762 [BB_1730, BB_1732, BB_1733]
        alloca_1764: Ptr<Int32, Shared>
        ret_1765: undef_1726
```

I think that the problem is related to one of the transformation phases not working correctly/not covering some additional edge cases.
