### ISSUE TITLE
How to access NuGet Preview Symbols?

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#589]
@76creates @jgiannuzzi
Now that we have pre-release nuget packages uploaded to Feedz.IO, how can we get access to the symbols?

**Comment by jgiannuzzi** [comment]
According to the [Feedz.io documentation](https://feedz.io/docs/package-types/symbols), you should add the following URL as a Symbol file location to your IDE: https://f.feedz.io/ilgpu/preview/symbols.

Could you please confirm that it works? If so, we can then update the documentation with instructions about how to access the preview symbols.

**Comment by MoFtZ** [comment]
Thanks @jgiannuzzi - that appears to be working 🎉 

In VS2019, under `Tools` -> `Options`:
![image](https://user-images.githubusercontent.com/27792737/129294190-c5433daa-557c-44a5-966e-d86c588d0818.png)

I am familiar with adding directory paths, but did not realise it also accepted HTTP urls.
