### ISSUE TITLE
AtomicOperationCAS_Uint Failed Test for AMD

### ISSUE THREAD

**Issue by 12345swordy** [m4rs-mt/ILGPU#59]
C:\Windows\TEMP\\OCL13720T5.cl:69:16: error: no matching function for call to 'atomic_compare_exchange_strong'
        bool var21 =  atomic_compare_exchange_strong ((atomic_ulong*)var14,  & var17, var20);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\constructicon\builds\gfx\seven\19.50\stream\opencl\compiler\clc2\ocl-headers\build\wNow64a\B_rel\opencl20_builtins.h:13704:1: note: candidate function not viable: no known conversion from '__generic atomic_ulong *' to 'volatile __global atomic_long *' for 1st argument

**Comment by m4rs-mt** [comment]
This problem seems to be related to the fact that the driver cannot infer the address space properly. However, it is unsafe to cast the pointer to a `__global` pointer in general at this point. Does this problem also occur in the scope of all other atomic operations?

**Comment by 12345swordy** [comment]
UInt32/UnInt64 for debug
double/single/UInt32/UnInt64 for release

**Comment by 12345swordy** [comment]
Code generated for UInt32
`struct kernel_type_0;
struct internal_type_10;
struct internal_type_11;

struct internal_type_11
{
	int* field_0;
	int field_1;
};
struct internal_type_10
{
	int field_0;
};
struct kernel_type_0
{
	int field_0;
	int field_1;
};

kernel void ILGPUKernel(
	global int* view_0,
	global int* view_1,
	global int* view_2,
	global int* view_3,
	struct internal_type_10 var1,
	struct kernel_type_0 var2,
	struct kernel_type_0 var3,
	struct kernel_type_0 var4,
	struct kernel_type_0 var5)
{
	// Map parameters

	struct internal_type_11 var6;
	struct internal_type_11 var7;
	struct internal_type_11 var8;
	struct internal_type_11 var9;

	// Assign views

	var6.field_0 = view_0+var2.field_0;
	var6.field_1 = var2.field_1;
	var7.field_0 = view_1+var3.field_0;
	var7.field_1 = var3.field_1;
	var8.field_0 = view_2+var4.field_0;
	var8.field_1 = var4.field_1;
	var9.field_0 = view_3+var5.field_0;
	var9.field_1 = var5.field_1;

	// Kernel indices

	struct internal_type_10 var0;
	var0.field_0 = get_global_id( 0 );
	bool var10 = var0.field_0>=var1.field_0;
	if (var10)
		 return ;


	L_640: ;
	int var11 =  var0.field_0;
	int* var12 =  & var9.field_0[var11];
	int var13 =  0;
	int* var14 =  & var6.field_0[var13];
	int var15 =  var0.field_0;
	int* var16 =  & var7.field_0[var15];
	int var17 =  *  var16;
	int var18 =  var0.field_0;
	int* var19 =  & var8.field_0[var18];
	int var20 =  *  var19;
	bool var21 =  atomic_compare_exchange_strong ((atomic_uint*)var14,  & var17, var20);
	int var22 = var21 ? var17 :  atomic_load ((atomic_uint*)var14);
	 *  var12 =  var22;
	 return ;

}`

**Comment by 12345swordy** [comment]
Ok I managed to fix the line of error
the line
```
bool var21 =  atomic_compare_exchange_strong ((atomic_uint*)var14,  & var17, var20);
```
needs to be converted to:
```
bool var21 =  atomic_compare_exchange_strong ((atomic_uint*)var14,  (__generic uint *)& var17, (__generic uint)var20);
```

**Comment by 12345swordy** [comment]
#67
