### ISSUE TITLE
ILGPU using for dataset creation

### ISSUE THREAD

**Issue by joshisunil-1983** [m4rs-mt/ILGPU#596]
Hello,

ILGPU can be used ? to create Numerous of data tables from data objects like class objects etc.

In my case one of my window application used to perform calculations on data is taking time to fill calculated variable results in data tables. I want run this part on GPU so that performance can be achieved.

may I proceed with this using ILGPU. Please guide.

**Comment by MoFtZ** [comment]
hi @joshisunil-1983. ILGPU currently provides support for [value types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types) only. Class objects are considered a `https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types`, so they cannot be used when allocating memory buffers.

If you are able, try to change some of your data to be stored as value types. Alternatively, you can manually transform your classes into value types, by copying the data/values into new arrays and structs. After the GPU operation is done, you can copy the values back and update your classes with the new values.

**Comment by joshisunil-1983** [comment]
@MoFtZ Thank you for the information.
