### ISSUE TITLE
Question: Is there a way to transfer jagged array

### ISSUE THREAD

**Issue by msvaillant** [m4rs-mt/ILGPU#6]
Hi, I am interested in using your lib for my project, but I am stuck on how to pass jagged array to Kernel. Now I use ArrayView2d, but it comes with lots of extra elements. Is there any more simple way to allocate such data on accelerator?

P.S. As I see it is also possible achieve some thing like jagged array by using simple ArrayView and copy jagged array to it, but it will also be needed to transfer sizes of sub-arrays, that is not really comfortable

**Comment by msvaillant** [comment]
@m4rs-mt, do you have any thoughts on that?

**Comment by m4rs-mt** [comment]
Hi @msvaillant. The basic problem is that copying from or to such a set of arrays requires several pin operations, which in turn take some time. However, I fully understand your point and I will add additional copy operations for jagged array in v0.5. At the moment I strongly recommend to use multidimensional arrays.

**Comment by msvaillant** [comment]
thank you for your work in any case :) I already use them, but that goes to the cost of memory allocation

**Comment by m4rs-mt** [comment]
@msvaillant, can you create a minimal code example of your specific use case? Perhaps we can use this example to work on a better solution :)

**Comment by msvaillant** [comment]
@m4rs-mt , yes of course. You can now look for example of it in [my repo](https://github.com/msvaillant/tellure/blob/dev/tsprocessor/TSProcessor.CLI/Tasks/Paint/ProgramPaint.cs). it may be really badly organized, just was a first try. And maybe in week I will provide separate sample for such a case, more accurate :)

**Comment by msvaillant** [comment]
also, I have catched one exception using this code sample (kind of "unspecified accelerator exception" while using CudaAccelerator), maybe I will open separate issue on it when i got some more free time

**Comment by msvaillant** [comment]
@m4rs-mt it is already august down and the roadmap says there should be about release :) is it ok? maybe contribution needed to speed up project?

**Comment by m4rs-mt** [comment]
@msvaillant unfortunately, the new compiler is still in the testing phase. It passes most of the unit tests (which will be released as well) but requires some further polishing. However, I am going to publish the new compiler within the next weeks. So stay tuned ;)

PS: I am going to adapt the roadmap

**Comment by m4rs-mt** [comment]
@msvaillant The new compiler currently passes almost all of our test cases and has reached the last internal test phase. The new version will therefore be released mid/end of October.  Please note that this also includes a new version of the Lightning Library.

**Comment by msvaillant** [comment]
@m4rs-mt, congrats and cheers 🎉 . And waiting to have a look on the changes and try out new version.
Are you going to provide detailed changelog of what was added and what has changed in the API?

**Comment by m4rs-mt** [comment]
I am trying to provide a detailed changelog. Furthermore, I need to update the whole documentation and all samples... this might take some additional days ;)

**Comment by msvaillant** [comment]
@m4rs-mt, can try help you with docs and changelogs before publishing, if you need. Or I will provide feedback some time after you are done ;)

**Comment by m4rs-mt** [comment]
@msvaillant Work on the new compiler is almost finished. I am in the final polishing phase and will prepare the release. The new compiler will be released on November 5th. Many thanks for your patience :)

I also try to create updated documentation and change logs. However, these documents may require some revision ;) This also applies to the samples.

**Comment by samy2** [comment]
@m4rs-mt Great news ! ILGpu V0.3 was already extremly good in my opinion. Will the new compiler be as fast, and produce optimized kernels as the former ?

**Comment by msvaillant** [comment]
@m4rs-mt, nice to hear that 🎉 Can't wait to try it out and provide you as much feedback as I can.

**Comment by m4rs-mt** [comment]
Instead of publishing v0.5, I decided to first release a public beta version (called v0.4.0-beta) of the new compiler to get additional feedback from the community :) 👍 

@samy2 Early benchmarks have shown an increase in compilation time. I'm currently invenstigating these issues.
@msvaillant Unfortunately, I could not prepare new documentation or updated samples due to crunch times at work.

**Comment by msvaillant** [comment]
@m4rs-mt, that is not a problem now for beta stage. so, the release 0.4 is only about changes in compilation process or there are also differences in the API so it will require migration stuff? 

P.S. I don't know is it good to use google group as a main feedback tool, official Discord (it might sound wild, but it is now widely used by developers as a preffered way of communication, including Microsoft - they have got several) or Gitter server are rather widely used way, also it is just easier to use and discover. Just for future consideration

**Comment by samy2** [comment]
@m4rs-mt, I would like to try 0.4.0-beta and send feedbacks, but I need one working sample using shared memory (even without comments). Is it possible to have that ?

**Comment by m4rs-mt** [comment]
@msvaillant  Yeah, you're right. I've just created a new Discord server. The server URL will be published on the ILGPU website. This should simplify our communication in any case 👍 
The API has only changed in terms of accelerator streams, math functions, and shared memory.
@samy2  I will publish a small example here soon, so that you can continue your tests. 🔢

**Comment by samy2** [comment]
@m4rs-mt , I confirm that a small example using shard memory would be very usefull. Thanks in advance for that.

**Comment by m4rs-mt** [comment]
Two small kernels that demonstrate the use of shared memory. Note that shared memory is *not* available when you use implicitly grouped kernels (as in older versions). 
```
/// <summary>
/// The group size.
/// </summary>
public const int GroupSize = 32;

/// <summary>
/// Allocates an array of elements in shared memory.
/// </summary>
internal static void SharedMemoryArrayKernel(GroupedIndex index, ArrayView<int> data)
{
    // Shared memory allocation is now accessible via the SharedMemory class.
    // Note that an allocation of an array view (currently) requires a compile-time known
    // constant array size (like 32).
    var sharedMemory = SharedMemory.Allocate<int>(GroupSize);

    // Write to shared memory
    sharedMemory[index.GroupIdx] = index.GroupIdx;

    // Synchronize group
    Group.Barrier();

    // Read shared memory
    var idx = index.ComputeGlobalIndex();
    data[idx] = sharedMemory[(index.GroupIdx + 1) % Group.DimensionX];
}

/// <summary>
/// Allocates a single variable in shared memory.
/// </summary>
internal static void SharedMemoryVariableKernel(GroupedIndex index, ArrayView<int> data)
{
    // Allocates a single variable (an array of size 1) in shared memory
    ref var sharedMemory = ref SharedMemory.Allocate<int>();

    // Reset shared memory
    if (index.GroupIdx.IsFirst)
	sharedMemory = 0;
    Group.Barrier();

    // Perform atomic operation on shared memory
    Atomic.Add(ref sharedMemory, 1);
    Group.Barrier();

    // Read shared memory variable
    var idx = index.ComputeGlobalIndex();
    data[idx] = sharedMemory;
}
```
You can use the launcher code below to try out the kernels:
```
/// <summary>
/// Launches both sample programs
/// </summary>
/// <param name="args"></param>
static void Main(string[] args)
{
    using (var context = new Context())
    {
	using (var accl = new CudaAccelerator(context, 0))
	{
	    using (var buffer = accl.Allocate<int>(GroupSize))
	    {
		var kernel = accl.LoadKernel<GroupedIndex, ArrayView<int>>(SharedMemoryArrayKernel);
		kernel(
		    accl.DefaultStream,
		    new GroupedIndex(1, GroupSize),
		    buffer);
		var arrayData = buffer.GetAsArray(accl.DefaultStream);
		// ...

		var variableKernel = accl.LoadKernel<GroupedIndex, ArrayView<int>>(SharedMemoryVariableKernel);
		variableKernel(
		    accl.DefaultStream,
		    new GroupedIndex(1, GroupSize),
		    buffer);
		var arrayData2 = buffer.GetAsArray(accl.DefaultStream);
		// ...
	    }
	}
    }
}
```
I am going to update all samples when I release the next beta version.

**Comment by samy2** [comment]
@m4rs-mt , very nice ! I will try that soon.

**Comment by m4rs-mt** [comment]
To come back to the original question: I will add appropriate new overloads for jagged arrays in the next version. The new functions will extend the `CopyTo` and `CopyFrom` methods of the `MemoryBuffer2D` and `MemoryBuffer3D` classes.

**Comment by xman236** [comment]
@m4rs-mt @msvaillant Could you please upload a work-around example of jagged array? It would really great, since I am also struggling with passing `List<Rgba32>` to the kernel.

**Comment by msvaillant** [comment]
@xman236  Well, I would like to share examples, but in fact I have nothing cause project I was working on stopped

**Comment by xman236** [comment]
> @xman236 Well, I would like to share examples, but in fact I have nothing cause project I was working on stopped

Nooooo....

**Comment by m4rs-mt** [comment]
I will add an additional sample related to jagged arrays to the ILGPU sample repository next week.
