### ISSUE TITLE
New API (1.0.0) samples needed

### ISSUE THREAD

**Issue by yuryGotham** [m4rs-mt/ILGPU#604]
Could somebody provide some basic samples for how to use the new API?

1) How do I copy a portion for a 1D C# array into gpu memory (say MemoryBuffer1D<float, Stride1D.Dense>):

```c#
            var data = new float[1024];
            for (int i = 0; i < data.Length; i++) data[i] = i;

            foreach (var device in context) {
                using (var acc = device.CreateAccelerator(context)) {
                        using (var gpuA = acc.Allocate1D<float>(256)) {
                                // need to copy first 256 floats from data into gpuA
                        }
                }
            }
```

2) How do I use the locked memory copy, same as above , but data is defined:
```c#
                    using (var data= acc.AllocatePageLockedArray1D<float>(1024)) {
                        for (int i = 0; i < data.Length; i++) data[i] = i;
                    }

```

**Comment by MoFtZ** [comment]
hi @yuryGotham, I have updated [this PR](#600) to show an example of offset copying.

In your case, you can use something like:
```CSharp
gpuA.SubView(0, 256).CopyFromCPU(acc.DefaultStream, data.AsSpan().Slice(256));
```

Regarding the use of locked memory copy, have a look at [existing PinnedMemoryCopy sample.](https://github.com/m4rs-mt/ILGPU/blob/361795308390e0e3752448a14891ef686e5cf6ab/Samples/PinnedMemoryCopy/Program.cs#L86). It shows how to copy from an page locked array into a GPU buffer, and a few different ways to retrieve values from the GPU.
