### ISSUE TITLE
About MemSet function - How to initializes whole memory buffer to Non-Zero value.

### ISSUE THREAD

**Issue by conghuiw** [m4rs-mt/ILGPU#606]
Greetings!

I use ILGPU for a while, it's pretty cool!

```c#
static void SampleInitialization(Accelerator accelerator)
{
            using var data = accelerator.Allocate1D<int>(1024);
            // Note that allocated memory is not initialized in general and
            // may contain random information.

            // Initialize the whole memory buffer to 0.
            data.MemSetToZero();

            **//how to init all contents values to 1 ?
            data.MemSet(1);**
}
```

Thank you for your help

**Comment by conghuiw** [comment]
btw I use [SimpleAlloc] Sample for testing.

**Comment by m4rs-mt** [comment]
@conghuiw Thank you very much for your question. The general "issue" is that ILGPU exposes the low-level `MemSet` functions from the driver APIs. Therefore, we support direct buffer-focused operations working on `byte` values only. If you want to initialize a buffer with a different value type (like an `int`) you can use the `Algorithms` library and its provided `Initialize` extension method:
```c#
accelerator.Initialize(data, 42);
```
