### ISSUE TITLE
Use case of LoadAutoGroupedStreamKernel - Action<T1,T2,T3...> max delegate parameters 

### ISSUE THREAD

**Issue by conghuiw** [m4rs-mt/ILGPU#612]
Hi, 

I saw LoadAutoGroupedStreamKernel function takes parameter Action<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14> up to 14 max. would like to know your opinion about use LoadAutoGroupedStreamKerne function in case of more than 14 data structures.

regards.

**Comment by MoFtZ** [comment]
hi @conghuiw. The `Action<>`  delegate of the .NET runtime provides up to 16 generic arguments. ILGPU makes use of up to 2 arguments for some kernels, as these kernels include `AcceleratorStream` and/or `KernelConfig`.

If you need to pass more parameters, you can consider using a `struct` to group parameters together. ILGPU supports structs with unmanaged types, so they can have the basic types (like `int`, `float`, etc) as struct member variables, as well as `ArrayView<>` member variables.

Note that there is no support for arrays in structs, unless you used fixed size buffers. And fixed sized buffers are limited to the basic types, so you cannot have an array of `ArrayView`s.

You might also want to have a look at the `SimpleStructures` and `FixedSizedBuffers` sample projects.

**Comment by conghuiw** [comment]
Hi, MoFtZ
Thank you for your guidance, I'm going to read more samples in ILGPU.
