### ISSUE TITLE
`AccessViolationException` trying to run a specialized kernel on CPU

### ISSUE THREAD

**Issue by lostmsu** [m4rs-mt/ILGPU#614]
Sorry I did not narrow the issue down further.

There's the gist demonstrating the problem (about 100 lines total):
https://gist.github.com/lostmsu/debe2a5f4565189f9e722f1dfeb6050f

This is on `1.0.0-beta3`. I have not tested earlier versions or other accelerator implementations.

OS: Windows 10

**Comment by lostmsu** [comment]
```csharp
Kernel<Add, N2<bool>>(11,
    leftData.View, rightData.View,
    result,
    cpu.Allocate1D(new long[] { 4, 3 }).View,
    cpu.Allocate1D(new long[] { 3, 1 }).View,
    SpecializedValue.New(EquatableFixedArray.New(new FixedArray<N2<bool>, bool> {
        [0] = false, [1] = true,
    })),
    SpecializedValue.New(EquatableFixedArray.New(new FixedArray<N2<bool>, bool> {
        [0] = true, [1] = false,
    })));
```

**Comment by lostmsu** [comment]
In case it is the culprit, implementation of `UnsafeRef`:
https://github.com/losttech/TypeNum/blob/f28befa00b82d2d154cc947b529520f77db2c5a6/src/FixedArray.cs#L39

**Comment by MoFtZ** [comment]
hi @lostmsu. OK, I've managed to reduce the problem down to a small example:
```CSharp
public class Program
{
    public struct MyStruct : IEquatable<MyStruct>
    {
        public int Data;

        public MyStruct(int data)
        {
            Data = data;
        }

        public bool Equals(MyStruct other) =>
            Data.Equals(other.Data);

        public override bool Equals(object? obj)
            => obj is MyStruct other && Equals(other);
    }

    static void Main()
    {
        var compute = Context.CreateDefaultAutoDebug();
        var cpu = CPUDevice.Default.CreateCPUAccelerator(compute);

        var kernel = cpu.LoadAutoGroupedStreamKernel<
            Index1D,
            SpecializedValue<MyStruct>,
            SpecializedValue<MyStruct>>(MyKernel);
        kernel(12,
            SpecializedValue.New(new MyStruct(1)),
            SpecializedValue.New(new MyStruct(2)));
    }

    static void MyKernel(
        Index1D index,
        SpecializedValue<MyStruct> first,
        SpecializedValue<MyStruct> second)
    {
    }
}
```
The issue appears to be that you overrode `bool object.Equals(object?)` but not `int object.GetHashCode()`.

The compiler generates the warning:
`CS0659: 'Program.MyStruct' overrides Object.Equals(object o) but does not override Object.GetHashCode()`.

If you implement `GetHashCode`, even if it is a really bad hash, the problem goes away:
```CSharp
public override int GetHashCode() => 12;
```

Also of interest, `AccessViolationException` is thrown when there are two SpecializedValues. If there is only one, a `NullReferenceException` is thrown - probably indicating that it could not find the `GetHashCode` implementation.

**Comment by lostmsu** [comment]
@m4rs-mt why is this an issue? Do generated kernels ever call `.GetHashCode()`?

AFAIK the default `GetHashCode()` implementation is not guaranteed to be suitable for hashtables, but in practice it usually is, especially in your narrowed down example. See [SharpLab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRjzwDcBDMAAgAsDKBeSqAUwHdKAJZgG24HsA3pQAiZYGQaUALOkoBfANykKNWYxbsuvQSLETGM+Utx5UBAJwAKWgDoA4s2AcyAZ2oBhPnGaWAlL+MzK2p0e0dnN09vPwDiXBdgSABjYE4efhBKAEkAUQBHCD0AI25mAB4tfgA+SgE8SgbKVABmSgBLKFTRcWNGynrGlsoivj5uSnzC7hdLSr5KPmBqZjBfBhqltpcbbv1GReWwHb1jAYahvhIVsDbvYdHxybJpyz4igCtmFIWPtfoat7vdouNLaBZLFaUABkUMom22TxeBxWsVwciAA==).

If it is indeed the problem, is it possible to warn user about this? I would add a static constructor to `SpecializedValue<T>` that checks T for this extra restriction.

**Comment by m4rs-mt** [comment]
@lostmsu kernels do not call the `GetHashCode` method in any case. However, the way the `SpecializedValue` cache works (since we need to check if a kernel has already been compiled for the given parameter combination) is that it calls the `GetHashCode` method in automatically generated code. This is the reason why this could cause the internal `AccessViolationException`.

Also, I like the idea of adding additional checks to the `SpecializedValue` class to test if the specified method is actually overwritten.

**Comment by lostmsu** [comment]
@m4rs-mt got a fix for the generated code. Do the custom structs for specialized kernel launches actually speed things up enough to justify complexity of code generation?
