### ISSUE TITLE
Use GPU and CPU Accelerator in parallel?

### ISSUE THREAD

**Issue by weierstrass1** [m4rs-mt/ILGPU#62]
Is possible use an accelerator that use all CPU cores and GPU cores to process the same kernel and improve the performance?

**Comment by m4rs-mt** [comment]
@weierstrass1 It is possible to use the `CPUAccelerator` and the `CudaAccelerator` in parallel. Furthermore, it is also possible to load the same kernel on multiple accelerators. If you want to exchange information between those accelerators you have to use the `CopyTo`/`CopyFrom` functions manually.

However, if you want to run the same kernel on the CPU and GPU at the same time on the same buffer to improve performance, the answer is: Sorry, this is not currently possible.

**Comment by weierstrass1** [comment]
thanks for your response, i am using ILGPU, it is a nice library, i hope you can implement that feature on the future because could be very useful.
