### ISSUE TITLE
PTX JIT compilation failed when compiling a kernel with a double atomic add operation

### ISSUE THREAD

**Issue by cino189** [m4rs-mt/ILGPU#620]
Hi, first of all thank you very much for your work, this package is really powerful. 

I designed a kernel to lookup and aggregate values on a large 2d array. The search operation is done on a int 2d memory buffer, while the aggregation is done on a float or a double 2d memory buffer.

With float it works perfectly but with double I get PTX JIT compilation failed, CUDA_ERROR_INVALID_PTX

If I run the kernel on cpu it works fine either with double or float, no problems there. 

I am quite a novice on GPU so bear with me if the design of the kernel is poor. 

This is the kernel itself

```C#
//Search across all the dimensions are aggregate the data
static void MultipleDimensionsSearchReduceKernel(Index1 Index, ArrayView<int> MemberIds, ArrayView<int> MemberColumns, ArrayView2D<int> DimGenerations, ArrayView2D<double> MatrixData, ArrayView<double> DataResult)
      {
	//Starting setting the row as valid
	bool validRow = true;
	
	//Loop on all the member IDs
	for (int i = 0; i < MemberIds.Length; i++)
	{
		//Chech each member column to verify if the row satisfy the query
		int memberCol = MemberColumns[i];
		if (DimGenerations[Index, memberCol] != MemberIds[i])
		{
			validRow = false;
		}
	}

	//If the row is valid increase the rows found counter and add amount to the result array
	if (validRow == true)
	{
		for(int i = 0; i < DataResult.IntLength; i++)
              {
			Atomic.Add(ref DataResult[i], MatrixData[Index, i]);
              }
	}
}

```

So essentially this is a map reduce operation, where each row in the matrix is parsed and if all the member ids in the corresponding columns satisfy the query it will take the value on the data matrix and atomically increase the amount in the result memory buffer, that is a 1d buffer with as many 1d elements as the data matrix dimension 2. This way with a single pass i can find the rows i need and sum them app for all the data columns in the data matrix.

The way I call the kernel is also as simple as it gets:
```C#
//Load the kernel into GPU
var GPUMultipleDimensionsSearchReduceKernel = this.GPUAccelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<int>, ArrayView<int>, ArrayView2D<int>, ArrayView2D<double>, ArrayView<double>>(MultipleDimensionsSearchReduceKernel);

...

//Setup the kernel
GPUMultipleDimensionsSearchReduceKernel(Index, gpuMemberIDs, gpuMemberColumns, GPUCubeDims.DimsGenerations, this.MatrixData.DataMatrix, DataResult);
```

It crashes on the LoadAutoGroupedStreamKernel, (obviously since it is a compiler error)

I am using an RTX2080, ILGPU v0.10.1 and ILGPU.Algorithms v0.9.2

I tried to upgrade to v1.0 rc but there is quite some work to convert the syntax so I wanted to reach out first in case this issue is not fixed in the rc either.

**Comment by cino189** [comment]
I think I narrowed down the problem, it is actually the atomic operation causing the issue, apparently it is not working correctly for float. I searched a bit online and i found that after pascal double atomic operations are supported in cuda.

**Comment by MoFtZ** [comment]
hi @cino189. The reason is that `ILGPU v0.10.x` is not compatible with `ILGPU.Algorithms v0.9.x` - there was a breaking change in the ILGPU APIs.

You should either use:
- `ILGPU v0.10.1` with `ILGPU.Algorithms v0.10.0-beta1`, or
- `ILGPU v0.9.2` with `ILGPU.Algorithms v0.9.2`.

Hope that helps.

**Comment by cino189** [comment]
hi @MoFtZ indeed upgrading algorithms to v0.10.0-beta1 solved the issue. Thanks!
