### ISSUE TITLE
Can not access internal ctor

### ISSUE THREAD

**Issue by a-a-k** [m4rs-mt/ILGPU#621]
I'm just trying to getting started but faced that error on the `using var context = new Context();` line. What am I doing wrong? I'm using 1.0.0-rc1 version.

**Comment by MoFtZ** [comment]
hi @a-a-k. There has been some major/breaking changes in the API between v0.10.x and v1.x. One of the changes is that the `Context` class is no longer directly constructed. Instead, use something like:
```CSharp
using var context = Context.CreateDefault();
```
More information can be found in the [release notes](https://github.com/m4rs-mt/ILGPU/releases/tag/v1.0-beta1) or [samples](https://github.com/m4rs-mt/ILGPU/tree/master/Samples). Hope that helps.

**Comment by a-a-k** [comment]
@MoFtZ very much thanks for so quick answer!
