### ISSUE TITLE
Question: calculate Euclidian distances with ILGPU

### ISSUE THREAD

**Issue by sanikolov** [m4rs-mt/ILGPU#633]
I looked carefully at the samples and open and closed issues for this repo but am still struggling with the following task.
Suppose we have 50K pairs of vectors (A1,B1), (A2,B2),...etc where each vector A[i], B[i] contains 3000 floats.
I'd like to calculate 50K Euclidian distances as floats between these vectors, i.e.
`float d[i] = distance(A[i],B[i]),` for i = 0 to 50K-1
The way I wanted to go about this problem is to declare 2 kernels, one for calculating the distance between 2 vectors
and another kernel for calculating all 50K distances in parallel.
But I don't have solid GPU background and have struggled to come close to a solution.
Any guidance? I found the existing ILGPU samples far too simple for what I'm trying to do.

**Comment by MoFtZ** [comment]
hi @sanikolov.

I've put together an example program that hopefully covers your problem description.

The kernel is the entry point to code that runs on the GPU. The code for calculating the distance does not have to be another kernel, it can be part of the main kernel.

For your input vectors, I have used a struct to hold the 3000 values. This could also have been represented by a 15,000,000 element array (50,000 x 3,000).

To make the concept easier to understand, I have used an auto-grouped kernel. This hides the details of kernel grouping, and works more like `Parallel.For`.

**EXAMPLE**
```CSharp
using System;
using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;

namespace Issue633
{
    public class Program
    {
        public const int NumVectors = 50_000;
        public const int NumElementsPerVector = 3_000;

        // Define a vector with 3000 elements.
        // Normal .NET arrays are not supported by ILGPU, so we are using a fixed buffer.
        public unsafe struct MyVector
        {
            public fixed float Values[NumElementsPerVector];
        }

        // Kernel that runs on the GPU.
        // We are using an auto-grouped kernel, so `index` is between 0 and 50,000 (exclusive).
        public static void MyKernel(Index1 index, ArrayView<MyVector> aView, ArrayView<MyVector> bView, ArrayView<float> distanceView)
        {
            distanceView[index] = CalculateDistance(aView[index], bView[index]);
        }

        // This is just a regular C# function. It can be called from the CPU, or from
        // a kernel running on the GPU.
        static unsafe float CalculateDistance(MyVector a, MyVector b)
        {
            // TODO: Calculate the Euclidian Distance between 'a' and 'b'.
            return a.Values[0] + b.Values[0];
        }

        static unsafe void Main(string[] args)
        {
            // Generate some initial data values.
            var aValues = new MyVector[NumVectors];
            var bValues = new MyVector[NumVectors];

            for (var i = 0; i < aValues.Length; i++)
            {
                for (var v = 0; v < NumElementsPerVector; v++)
                    aValues[i].Values[v] = i;
            }

            for (var i = 0; i < bValues.Length; i++)
            {
                for (var v = 0; v < NumElementsPerVector; v++)
                    bValues[i].Values[v] = i;
            }

            // Create the accelerator.
            using var context = new Context();
            using var accelerator = new CudaAccelerator(context);

            // Populate aBuffer and bBuffer with values.
            using var aBuffer = accelerator.Allocate<MyVector>(aValues.Length);
            using var bBuffer = accelerator.Allocate<MyVector>(bValues.Length);

            aBuffer.CopyFrom(aValues, 0, 0, aValues.Length);
            bBuffer.CopyFrom(bValues, 0, 0, aValues.Length);

            // Create a buffer to hold the distance results.
            using var distanceBuffer = accelerator.Allocate<float>(NumVectors);

            // Create and launch the kernel
            var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<MyVector>, ArrayView<MyVector>, ArrayView<float>>(MyKernel);
            kernel(NumVectors, aBuffer.View, bBuffer.View, distanceBuffer.View);

            // Retrieve the calculated distance values. Implicitly waits for the kernel
            // to complete by calling accelerator.DefaultStream.Synchronize() internally.
            var distanceValues = distanceBuffer.GetAsArray();

            for (var i = 0; i < distanceValues.Length; i++)
                Console.WriteLine($"Distance[{i}] = {distanceValues[i]}");
        }
    }
}
```

**Comment by sanikolov** [comment]
thank you so much!

**Comment by sanikolov** [comment]
@MoFtZ as written I didn't observe any speedup on the GPU compared to the CPU accelerator.
I renamed Main to Main1 and wrote a `while(true) { Main1(); } ` loop as the body of the new Main.
According to the windows task manager the calculations in `CalculateDistance` are taking place on the CPU
instead of CUDA.
I saw only GPU copy operations take place every so often but other than that the GPU usage remained at 0
for the entire duration of my infinite loop.

Here is CalculateDistance
```
        // This is just a regular C# function. It can be called from the CPU, or from
        // a kernel running on the GPU.
        static unsafe float CalculateDistance(MyVector a, MyVector b)
        {
            // TODO: Calculate the Euclidian Distance between 'a' and 'b'.
            var sum = 0.0;
            for (var i = 0; i < NumElementsPerVector; i++)
            {
                var diff = a.Values[i] - b.Values[i];
                sum += diff * diff;
            }
            return (float) System.Math.Sqrt(sum);
        }
```

My expectation was that given the size 50K x 3K = 150 M floats I should see a difference.
For small sizes I am well aware that CPU calcs often outperform GPU calcs.
But for larger sizes the GPU tends to outperform.
For size 100K x 3K = 300 M the same thing was true.
But in this case it seems as if the GPU is not doing anything.
Any ideas?

**Comment by sanikolov** [comment]
@MoFtZ your comments above are highly appreciated. I was able to find the CUDA graph in task manager and it showed high utilization. Also GPU memory utilization was high. GPU temperature goes up 5 degrees or more. There is no doubt that calculations are happening on the GPU.
However, I find the performance of the GPU calculations about the same as the CPU even though the sizes are relatively large.
In the attached test.cs file I'm allocating 100K arrays of size 3K each, for a total of 300 M floats.
Better yet, I don't include any allocations and copies in the elapsedMilliseconds measurements.
The elapsed milliseconds represent raw kernel performance.
100_000 nearly parallel calculations, kernel is allocated only once.
It takes 93 seconds on my NVDIA GeForce GTX 1050 Ti which is not a great card.
Can somebody try the attached cs on a proper high performance GPU and tell me if it makes any difference?
I hope that my crappy hardware is to blame.
If calculations are noticeably faster on a Tesla GPU or better I'd be happy to spend the $ to upgrade my card.

**Comment by MoFtZ** [comment]
@sanikolov
I have run your test code on an Intel i7-7700, and Nvidia GeForce GTX 1070.
It takes approx. 45 seconds to run the calculation 500 times.

However, I'm not sure why you say that the CPU is about the same as the GPU. My CPU, running the calculation 500 times, takes around 110 seconds.
```CSharp
sw.Start();
for (var i = 0; i < 500; i++)
{
    Parallel.For(0, aValues.Length, d =>
    {
        CalculateDistance(aValues[d], bValues[d]);
    });
}
sw.Stop();
```

Are you using a more optimized CPU algorithm?

**Comment by sanikolov** [comment]
On my outdated hardware the difference is less noticeable.
Calculations take about 98 seconds on i5-4590 and about 93 seconds on Nvdia GeForce GTX 1050 Ti.
On your high end hardware the difference is noticeable.
No, the CPU algo is the same as shown in the test.cs sample.
