### ISSUE TITLE
Custom INumeric<t>

### ISSUE THREAD

**Issue by SomeUserName6474** [m4rs-mt/ILGPU#639]
Im build my own INumeric )

            
            float_numeric f1 = 0.0f;
            float_numeric f2 =1f;
            float_numeric f3 = 2f;

            f1 = (float_numeric)((IBaseMathPrimitive<float>)f2 + (IBaseMathPrimitive<float>)f3);
            OR 
            f1 = (float_numeric)(f2 + f3);

3
Works fine, in kernel doesnt works.

**Comment by MoFtZ** [comment]
@SomeUserName6474
What is `float_numeric`? class? struct?

Do you have a full example of working code that you could share?

Also, how is this different to #638?

**Comment by SomeUserName6474** [comment]
Its a struct with IBaseMathPrimitive<float> interface.
#638 - that code not working in c#.

**Comment by SomeUserName6474** [comment]
public interface IBaseMathPrimitive<T>
        where T : unmanaged
    {
        public  static  int CompareTo(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return 0;
        }

        public static bool operator <(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) < 0;
        }
        public static bool operator >(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) > 0;
        }
        public static bool operator <=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) <= 0;
        }
        public static bool operator >=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) >= 0;
        }
        public T GetValue();
        IBaseMathPrimitive<T> Add(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator +(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Add(b);
        }

        IBaseMathPrimitive<T> Sub(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator -(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Sub(b);
        }

        IBaseMathPrimitive<T> Mul(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator *(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Mul(b);
        }

        IBaseMathPrimitive<T> Div(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator /(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Div(b);
        }
    }

**Comment by SomeUserName6474** [comment]
`public interface IBaseMathPrimitive<T>
        where T : unmanaged
    {
        public  static  int CompareTo(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return 0;
        }

        public static bool operator <(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) < 0;
        }
        public static bool operator >(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) > 0;
        }
        public static bool operator <=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) <= 0;
        }
        public static bool operator >=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) >= 0;
        }
        public T GetValue();
        IBaseMathPrimitive<T> Add(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator +(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Add(b);
        }

        IBaseMathPrimitive<T> Sub(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator -(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Sub(b);
        }

        IBaseMathPrimitive<T> Mul(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator *(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Mul(b);
        }

        IBaseMathPrimitive<T> Div(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator /(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Div(b);
        }
    }`

**Comment by SomeUserName6474** [comment]
public struct float_numeric : IBaseMathPrimitive<float>
        {
            public  static int CompareTo(IBaseMathPrimitive<float> x, IBaseMathPrimitive<float> y)
            {
                return x.GetValue()>y.GetValue()?1:x.GetValue()==y.GetValue()?0:-1;
            }

            public static bool operator ==(float_numeric x, IBaseMathPrimitive<float> y)
            {
                return CompareTo(x, y) == 0;
            }

            public static bool operator !=(float_numeric x, IBaseMathPrimitive<float> y)
            {
                return CompareTo(x, y) != 0;
            }

            public float_numeric(float val)
            {
            Value = val;
            }

            public float Value;

            public float GetValue() => Value;

             public IBaseMathPrimitive<float> Add(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value+b.GetValue()));
             }

             
             public IBaseMathPrimitive<float> Mul(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value*b.GetValue()));
             }

             public IBaseMathPrimitive<float> Div(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value/b.GetValue()));
             }

             public IBaseMathPrimitive<float> Sub(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value-b.GetValue()));
             }

            public static IBaseMathPrimitive<float> operator +(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Add(b);
            }
                public static IBaseMathPrimitive<float> operator *(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Mul(b);
            }
                public static IBaseMathPrimitive<float> operator -(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Sub(b);
            }
                public static IBaseMathPrimitive<float> operator /(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Div(b);
            }

            public static implicit operator float( float_numeric d) => d.Value;
            public static implicit operator float_numeric(float d) => new float_numeric(d);

        }

**Comment by SomeUserName6474** [comment]
public interface IBaseMathPrimitive<T>
        where T : unmanaged
    {
        public  static  int CompareTo(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return 0;
        }

        public static bool operator <(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) < 0;
        }
        public static bool operator >(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) > 0;
        }
        public static bool operator <=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) <= 0;
        }
        public static bool operator >=(IBaseMathPrimitive<T> x, IBaseMathPrimitive<T> y)
        {
            return CompareTo(x, y) >= 0;
        }
        public T GetValue();
        IBaseMathPrimitive<T> Add(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator +(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Add(b);
        }

        IBaseMathPrimitive<T> Sub(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator -(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Sub(b);
        }

        IBaseMathPrimitive<T> Mul(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator *(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Mul(b);
        }

        IBaseMathPrimitive<T> Div(IBaseMathPrimitive<T> b);
        public static IBaseMathPrimitive<T> operator /(IBaseMathPrimitive<T> a, IBaseMathPrimitive<T> b)
        {
            return a.Div(b);
        }
    }

**Comment by SomeUserName6474** [comment]
public struct float_numeric : IBaseMathPrimitive<float>
        {
            public  static int CompareTo(IBaseMathPrimitive<float> x, IBaseMathPrimitive<float> y)
            {
                return x.GetValue()>y.GetValue()?1:x.GetValue()==y.GetValue()?0:-1;
            }

            public static bool operator ==(float_numeric x, IBaseMathPrimitive<float> y)
            {
                return CompareTo(x, y) == 0;
            }

            public static bool operator !=(float_numeric x, IBaseMathPrimitive<float> y)
            {
                return CompareTo(x, y) != 0;
            }

            public float_numeric(float val)
            {
            Value = val;
            }

            public float Value;

            public float GetValue() => Value;

             public IBaseMathPrimitive<float> Add(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value+b.GetValue()));
             }

             
             public IBaseMathPrimitive<float> Mul(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value*b.GetValue()));
             }

             public IBaseMathPrimitive<float> Div(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value/b.GetValue()));
             }

             public IBaseMathPrimitive<float> Sub(IBaseMathPrimitive<float> b)
             {
                return new float_numeric((float)(Value-b.GetValue()));
             }

            public static IBaseMathPrimitive<float> operator +(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Add(b);
            }
                public static IBaseMathPrimitive<float> operator *(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Mul(b);
            }
                public static IBaseMathPrimitive<float> operator -(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Sub(b);
            }
                public static IBaseMathPrimitive<float> operator /(IBaseMathPrimitive<float> a, float_numeric b)
            {
                return a.Div(b);
            }

            public static implicit operator float( float_numeric d) => d.Value;
            public static implicit operator float_numeric(float d) => new float_numeric(d);

        }

**Comment by SomeUserName6474** [comment]
Class kernels<t,u>
where t : unmanaged, IAdditable<u>
where u : unmanaged
{
public static void kernel1(index2 index, arrayView2d<t> array1, arrayView2d<t> array2)
{
array1[index] = (T) (array1[index] + array2[index]);
}
}

**Comment by SomeUserName6474** [comment]
And here is ildasm. As i can see, there is no way to translate that calls with boxing into something like 
add
Conv.r4
newobj instance void float_numeric::.ctor?

// float_numeric = (float_numeric)(object)((IBaseMathPrimitive<float>)float_numeric2 + (IBaseMathPrimitive<float>)float_numeric3);
 IL_0022: ldloc.1
 IL_0023: box float_numeric
 IL_0028: ldloc.2
 IL_0029: box float_numeric
 IL_002e: call class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<!0> class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32>::op_Addition(class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<!0>, class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<!0>)
 IL_0033: unbox.any float_numeric
 IL_0038: stloc.0
.method public final hidebysig newslot virtual 
 instance class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32> Add (
  class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32> b
 ) cil managed 
{
 // Method begins at RVA 0x2518
 // Code size 30 (0x1e)
 .maxstack 2
 .locals init (
  [0] class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32>
 )
 // {
 IL_0000: nop
 // return new float_numeric(Value + b.GetValue());
 IL_0001: ldarg.0
 IL_0002: ldfld float32 float_numeric::Value
 IL_0007: ldarg.1
 IL_0008: callvirt instance !0 class NlpGpuTools.Data.Types.IBaseMathPrimitive`1<float32>::GetValue()
 IL_000d: add
 IL_000e: conv.r4
 IL_000f: newobj instance void float_numeric::.ctor(float32)
 IL_0014: box float_numeric
 IL_0019: stloc.0
 // (no C# code)
 IL_001a: br.s IL_001c
 IL_001c: ldloc.0
 IL_001d: ret

**Comment by SomeUserName6474** [comment]
Ok, defined static operators must include at least one  member with IBaseMathPrimitive<T>, so, it will take a while to write a weaver.

**Comment by SomeUserName6474** [comment]
Ok, according to cil, to use our custom numeric interface without boxing and unboxing we must preform following changes via fody:

```
Consructor change (for all types)
 From:
 // IBaseMathPrimitive<float> baseMathPrimitive = new float_numeric(0f);
 IL_0001: ldc.r4 0.0 (value)
 IL_0006: newobj instance void float_numeric::.ctor(float32)
 IL_000b: box float_numeric
 IL_0010: stloc.0 (addr)
 To:
 // float_num float_num = new float_num(0f);
 IL_003a: ldloca.s 3 (addr)
 IL_003c: ldc.r4 0.0 (value)
 IL_0041: call instance void ConsoleApp2.Новая_папка.float_num::.ctor(float32)
 
 
 Operator change
 From:
 // baseMathPrimitive = baseMathPrimitive2 + baseMathPrimitive3;
 IL_0031: ldloc.1
 IL_0032: ldloc.2
 IL_0033: call class NlpGpuTools.Data.Types.IBaseMathPrimitive1<!0> class NlpGpuTools.Data.Types.IBaseMathPrimitive1<float32>::op_Addition(class NlpGpuTools.Data.Types.IBaseMathPrimitive1<!0>, class NlpGpuTools.Data.Types.IBaseMathPrimitive1<!0>)
 IL_0038: stloc.0
 To:
 // float_num = float_num2 + float_num3;
 IL_005d: ldloc.s 4
 IL_005f: ldloc.s 5
 IL_0061: call valuetype ConsoleApp2.Новая_папка.float_num ConsoleApp2.Новая_папка.float_num::op_Addition(valuetype ConsoleApp2.Новая_папка.float_num, valuetype ConsoleApp2.Новая_папка.float_num)
 IL_0066: stloc.3
```

**Comment by SomeUserName6474** [comment]
> @SomeUserName6474 @MoFtZ I'm not sure if I haven't already entered this conversation too late.... Anyway, you can define an abstract interface that in turn depends on a generic parameter which depends on the interface declaration itself to avoid boxing:
> 
> ```cs
>     public interface INumeric<T>
>         where T : unmanaged, INumeric<T>
>     {
>         T Add(T other);
>     }
> 
>     public readonly struct MyInt : INumeric<MyInt>
>     {
>         public MyInt(int value)
>         {
>             Value = value;
>         }
> 
>         public int Value { get; }
> 
>         public readonly MyInt Add(MyInt other) =>
>             new MyInt(Value + other.Value);
>     }
> ```
Yep, and write kernels like array[index] = array[index].Add(constant);

?)

**Comment by SomeUserName6474** [comment]
All operators and constructors translates well .
Now method parameters, return types and generics type resolving. Next - lists, arrays(even 2d), working kernel.

            Single_numeric f111 = new Single_numeric(0.0f);
            Single_numeric f112 = new Single_numeric(1.1f);
            Single_numeric f113 = new Single_numeric(2.11f);

            f111 = f112 + f113;

            IBaseMathPrimitive<Single> f1 = new Single_numeric(0.0f);
            IBaseMathPrimitive<Single> f2 = new Single_numeric(1.1f);
            IBaseMathPrimitive<Single> f3 = new Single_numeric(2.11f);
            f1 = f2 + f3;

.method private hidebysig static 
 void Main (
  string[] args
 ) cil managed 
{
 // Method begins at RVA 0x33ec
 // Code size 92 (0x5c)
 .maxstack 2
 .entrypoint
 .locals init (
  [0] valuetype Single_numeric f111,
  [1] valuetype Single_numeric f112,
  [2] valuetype Single_numeric f113,
  [3] valuetype [ConsoleApp2.dll]Single_numeric,
  [4] valuetype [ConsoleApp2.dll]Single_numeric,
  [5] valuetype [ConsoleApp2.dll]Single_numeric
 )

 // {
 IL_0000: nop
 // Single_numeric single_numeric = new Single_numeric(0f);
 IL_0001: ldloca.s 0
 IL_0003: ldc.r4 0.0
 IL_0008: call instance void Single_numeric::.ctor(float32)
 // Single_numeric single_numeric2 = new Single_numeric(1.1f);
 IL_000d: ldloca.s 1
 IL_000f: ldc.r4 1.1
 IL_0014: call instance void Single_numeric::.ctor(float32)
 // Single_numeric single_numeric3 = new Single_numeric(2.11f);
 IL_0019: ldloca.s 2
 IL_001b: ldc.r4 2.11
 IL_0020: call instance void Single_numeric::.ctor(float32)
 // single_numeric = single_numeric2 + single_numeric3;
 IL_0025: ldloc.1
 IL_0026: ldloc.2
 IL_0027: call valuetype Single_numeric Single_numeric::op_Addition(valuetype Single_numeric, valuetype Single_numeric)
 IL_002c: stloc.0
 // Single_numeric single_numeric4 = new Single_numeric(0f);
 IL_002d: ldloca.s 3
 IL_002f: ldc.r4 0.0
 IL_0034: call instance void Single_numeric::.ctor(float32)
 // single_numeric4 = new Single_numeric(1.1f);
 IL_0039: ldloca.s 3
 IL_003b: ldc.r4 1.1
 IL_0040: call instance void Single_numeric::.ctor(float32)
 // Single_numeric b = new Single_numeric(2.11f);
 IL_0045: ldloca.s 5
 IL_0047: ldc.r4 2.11
 IL_004c: call instance void Single_numeric::.ctor(float32)
 // single_numeric4 = Single_numeric.Add(single_numeric4, b);
 IL_0051: ldloc.s 3
 IL_0053: ldloc.s 5
 IL_0055: call valuetype Single_numeric Single_numeric::Add(valuetype Single_numeric, valuetype Single_numeric)
 IL_005a: stloc.3
 // }
 IL_005b: ret
} // end of method Program::Main

**Comment by SomeUserName6474** [comment]
Call valuetype executed on gpu or on cpu in ilgpu?

**Comment by SomeUserName6474** [comment]
Methods with simple args - done.
``
static IBaseMathPrimitive<Single> MethodExample(IBaseMathPrimitive<Single> a, IBaseMathPrimitive<Single> b, IBaseMathPrimitive<Single> c)
        {
            var d = b / c;
            return (a + d);
        }

        static void Main(string[] args)
        {

            IBaseMathPrimitive<Single> f1 = new Single_numeric(0.0f);
            IBaseMathPrimitive<Single> f2 = new Single_numeric(1.1f);
            IBaseMathPrimitive<Single> f3 = new Single_numeric(2.11f);
            IBaseMathPrimitive<Single> f4 = new Single_numeric(3.11f);
            f1 = MethodExample(f2, f3, f4);

**Comment by SomeUserName6474** [comment]
INumeric in net6 based on overriding static abstract interface methods, anyway interface is reference type

**Comment by m4rs-mt** [comment]
We are closing this issue for now. Once we have support for the `INumber<T>` interface (see #802), you will be able to rewrite your code in a really nice way.

**Comment by SomeUserName6474** [comment]
Note that you should clone generic methods because in normal operation they compile to IBaseMathPrimitive<T> and cant be processed without type resolving.
