### ISSUE TITLE
Looking for sample/guide of use multiple GPUs

### ISSUE THREAD

**Issue by conghuiw** [m4rs-mt/ILGPU#649]
Greetings!
 
Has someone tried using multiple GPUs with ILGPU?  
It would be great if you can give one sample to explain this, I appreciate your input on this help.

**Comment by MoFtZ** [comment]
hi @conghuiw, the example is a bit old, but does this answer your question?
https://github.com/m4rs-mt/ILGPU/issues/397#issuecomment-778529864

**Comment by conghuiw** [comment]
@MoFtZ Thanks for you quick reply.
