### ISSUE TITLE
Array addition assignment operators do not compile properly in kernel function

### ISSUE THREAD

**Issue by BenjaminPelletier** [m4rs-mt/ILGPU#65]
Inside a kernel function, I put the following code:

```
float[] dispositions = new float[2];
dispositions[0] = 0;
dispositions[0] += 1;
```

When attempting to run, I see the following error:

![image](https://user-images.githubusercontent.com/11224086/74049278-a886ae00-4988-11ea-966e-0c67118fad42.png)

I can resolve this error by rewriting my code as:

```
float[] dispositions = new float[2];
dispositions[0] = 0;
float prevValue = dispositions[0];
dispositions[0] = prevValue + 1;
```

I can also resolve the error by simply commenting out the `dispositions[0] += 1;` line.  A same or similar error happens if I change that line to `dispositions[0]++;`.  Note that the following code does not produce an error:

```
float x = 0;
x += 1;
```

So, it seems that the problem is limited to array references.

(thanks for a great tool, it's working really well for me otherwise!)

**Comment by weierstrass1** [comment]
You can't instantiate arrays into a kernel. You can't use any reference type, only structs.
