### ISSUE TITLE
My GPU goes missing when enabling algorithms

### ISSUE THREAD

**Issue by mfagerlund** [m4rs-mt/ILGPU#674]
The test below shows a CUDA, but when I enable algorithms, it goes away;

Without EnableAlgorithms
  CUDA Devices
    GeForce GTX 1070 [Type: Cuda, WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 8589934592]
CPU Devices
    CPUAccelerator [Type: CPU, WarpSize: 4, MaxNumThreadsPerGroup: 16, MemorySize: 9223372036854775807]

With EnableAlgorithms
  CUDA Devices
  CPU Devices
    CPUAccelerator [Type: CPU, WarpSize: 4, MaxNumThreadsPerGroup: 16, MemorySize: 9223372036854775807]

This issue exists with RC2 and the latest code from the repo.

cheers,
m

    public class TestGetDevices
    {
        private readonly ITestOutputHelper _output;

        public TestGetDevices(ITestOutputHelper output)
        {
            _output = output;
        }

        protected void WriteLine(object obj) =>
            _output.WriteLine(obj?.ToString() ?? "null");

        protected void WriteLine(string text) => _output.WriteLine(text);

        [Fact]
        public void GetAndShowDevices()
        {
            WriteLine("Without EnableAlgorithms");
            using (var context = Context.CreateDefault())
            {
                WriteLine("  CUDA Devices");
                foreach (var device in context.GetDevices<CudaDevice>())
                {
                    WriteLine("    " + device);
                }

                WriteLine("CPU Devices");
                foreach (var device in context.GetDevices<CPUDevice>())
                {
                    WriteLine("    " + device);
                }
            }

            WriteLine("\nWith EnableAlgorithms");
            using (var context = Context.Create(b => b.EnableAlgorithms()))
            {
                WriteLine("  CUDA Devices");
                foreach (var device in context.GetDevices<CudaDevice>())
                {
                    WriteLine("    " + device);
                }

                WriteLine("  CPU Devices");
                foreach (var device in context.GetDevices<CPUDevice>())
                {
                    WriteLine("    " + device);
                }
            }
        }
    }

**Comment by MoFtZ** [comment]
@mfagerlund When you enable algorithms, you still need to call `Default()` to add the default accelerators.

`var context = Context.Create(b => b.Default().EnableAlgorithms()))`

**Comment by mfagerlund** [comment]
You're right, that worked a treat!
