### ISSUE TITLE
Kernel compilation error

### ISSUE THREAD

**Issue by pavlexander** [m4rs-mt/ILGPU#68]
I have been testing `ILGPU`, but an exception is thrown when compiling more-or-less complicated kernel:

```
namespace GPU_ILGPU
{
    public class IlgpuTest
    {
        public IlgpuTest()
        {

        }

        public void GenerateKernel()
        {
            using (var context = new Context())
            {
                context.EnableAlgorithms();

                using (Backend b = new PTXBackend(context, PTXArchitecture.SM_50, PTXInstructionSet.ISA_50, TargetPlatform.X64))
                {
                    var methods = typeof(IlgpuTest).GetMethods(BindingFlags.Static | BindingFlags.Public);
                    var method = methods.FirstOrDefault(f => f.Name == nameof(MyKernel));
                    var compiledKernel = b.Compile(method, default);

                    var ptxKernel = compiledKernel as PTXCompiledKernel;
                    System.IO.File.WriteAllText("MyKernel.ptx", ptxKernel.PTXAssembly);
                }
            }
        }

        public static void MyKernel(
                    Index index,
                    ArrayView<bool> results,
                    ArrayView<int> in1,
                    ArrayView<int> in2,
                    ArrayView<double> in3,
                    ArrayView2D<bool> in4
                    )
        {
            bool isTrue = false;
            int varA = in1[index];
            int varB = in2[index];

            double calculatable = 0;

            for (int i = 0; i < in3.Length; i++)
            {
                if (isTrue == true)
                {
                    var i2 = new Index2(i, varA);

                    bool bo = in4[i2];
                    if (bo == true)
                    {
                        continue;
                    }

                    calculatable = calculatable + in3[i] + 2;
                    isTrue = false;
                }
                else
                {
                    var i2 = new Index2(i, varB);

                    bool bo = in4[i2];
                    if (bo == true)
                    {
                        continue;
                    }

                    calculatable = calculatable + in3[i] - 1;
                    isTrue = true;
                }
            }

            if (calculatable >= 0)
                results[index] = true;
        }
    }
}
```

Error:

> System.AggregateException: 'One or more errors occurred.'
> NotSupportedIntrinsicException: The function 'Equal' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?

It is thrown at line `Compile`.

By excluding sections of code 1 by 1 from my kernel function - I was able to deduct the problematic code. It's the:

```
bool bo = in4[i2];
if (bo == true)
{
	continue;
}
```

It seems like the kernel compilation fails when I try to retrieve a `boolean` value from a 2-dimensional array. Is there an easy fix for it? It seems like the problem is gone when I change the primitive type to `byte`. Is this due to boolean being non-blittered type? is there a guideline or a list of limitations when using non-blittable types in `ILGPU`?

The error is a bit misleading.

using

- Microsoft Visual Studio Community 2019, Version 16.4.5
- win 10, x64
- compile in x64, debug
- ilgpu 0.7.1.0

thanks!
and thank you for the awesome product

**Comment by m4rs-mt** [comment]
@pavlexander Thank you for your bug report. I was able to reproduce your issue using the code provided. A quick analysis revealed that the issue could be reproduced using the kernel code below:
```c#
        public static void MyKernel(
            Index1 index,
            ArrayView<bool> values
            )
        {
            bool bo = values[0];
            if (bo == true)
                return;
        }
```
The error message is misleading because this code snippet causes an internal compiler problem in the `PTXInstructions` class: A comparison operation could not be determined. Please note that the problem does not occur in release mode, as the comparison is converted into some other operations.

Regarding your question about blittable types: You cannot pass views to `bool` values at the moment since these types are not blittable by default in all cases. You will recognize this issue once you allocate some memory buffers containing bools.
