### ISSUE TITLE
AMD GPU is not recognized(R9 390) as CLAccelerator

### ISSUE THREAD

**Issue by JohnMasen** [m4rs-mt/ILGPU#69]
I've wrote a test application to list all accelerators in my machine. it works perfect on my Surface book 2. however, it only lists CPU accelerator on my workstation with AMD R9 390 GPU. I can provide more information if you need.

Radeon software version is 20.11
Windows 10 with latest update

--------------------------------------------
using (Context c=new Context())
            {
                c.EnableAlgorithms();
                foreach (var item in Accelerator.Accelerators)
                {
                    using (Accelerator accelerator = Accelerator.Create(c, item))
                    {
                        Console.WriteLine($"{accelerator.AcceleratorType}, {accelerator.Name}");
                        //doAccTest(accelerator);
                    }
                    
                }
            }

**Comment by 12345swordy** [comment]
Make sure that your drivers are at the latest version.

**Comment by m4rs-mt** [comment]
I have fixed several minor problems with the 'OpenCL` runtime. One of them was the detection of the `OpenCL C` language version. This could cause ILGPU to ignore the actual accelerator. 

I will close this issue for now. If the problem still occurs in the new version, feel free to reopen this issue or submit another bug report.
