### ISSUE TITLE
OpenCL 3.0

### ISSUE THREAD

**Issue by RER009** [m4rs-mt/ILGPU#692]
Hello,

I have new PC for PROD that use Intel IRIS Xe Graphics (INTEL 11th Gen Core i5). 

My code use ILGPU 0.10.1.

When I launch my app or  ILGPU samples, I see that CLAccelerator.CLAccelerators is empty but CLAccelerator.AllCLAccelerators has 1 item.

I deduce that my GPU is not supported by ILGPU. Could you tell me why?

I have updated GPU drivers to the latest version.
When I use GPUz tool, OpenCL informations are :  Supported version : Full | Supported Profile : OpenCl 3.0 NEO.

Informations about ILGPU :
  Device: Intel(R) Iris(R) Xe Graphics [ILGPU InstanceId: 19]
  Platform name:                           Intel(R) OpenCL HD Graphics
  Platform version:                        3.0
  Vendor name:                             Intel(R) Corporation
  Vendor:                                  Intel
  Device type:                             CL_DEVICE_TYPE_GPU
  Clock rate:                              1300 MHz
  OpenCL C version:                        CL1.2
  Has FP16 support:                        True
  Has Int64 atomics support:               True
  Has sub group support:                   True

Could you tell me how to solve this issue ? 
There is an urgent need.

Thanks in advance. 

Renaud.

**Comment by MoFtZ** [comment]
hi @RER009.

Unfortunately, ILGPU v0.10.x does not support OpenCL 3.0. However, we [added support](https://github.com/m4rs-mt/ILGPU/pull/464) for OpenCL 3.0 in ILGPU v1.0.

Are you able to update your version of ILGPU? It is currently ILGPU v1.0 rc2.

**Comment by RER009** [comment]
Ok. I will try this new version. Do you have a small guide to upgrade to 1.0 ? 
I see that most of objects have changed.

Thanks for your help.

**Comment by MoFtZ** [comment]
We do not have an upgrade guide yet. The two main changes are to do with the initialization of the `Context`, and the Memory API.

There is some information in the [release notes](https://github.com/m4rs-mt/ILGPU/releases/tag/v1.0-beta1). And the [sample projects](https://github.com/m4rs-mt/ILGPU/tree/master/Samples) have also been updated.

**Comment by RER009** [comment]
Great. I will read this note carefully.

Just a question. I have made all changes in my code with 1.0.0-rc2. When I launch my app and try to load my kernel, I have this exception : CapabilityNotSupportedException: Float64 (double) type is not supported on this device.

Are there some limitations in this new version ? Or perhaps it simply my code that is not correct :-)

**Comment by MoFtZ** [comment]
That was actually part of the [OpenCL 3.0](https://github.com/m4rs-mt/ILGPU/pull/464) change. The OpenCL device is supposed to advertise the features/capabilities that it supports.

It sounds like `cl_khr_fp64` is missing.

On the `CLDevice` class, there is an `Extensions` property that lists all the advertised features from the device driver. Could you tell us what this contains?

You can get the `CLDevice` from the `Context` or `CLAccelerator` classes.

**Comment by RER009** [comment]
You will find below the features list:

cl_khr_byte_addressable_store
cl_khr_fp16
cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics
cl_khr_icd
cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics
cl_intel_subgroups
cl_intel_required_subgroup_size
cl_intel_subgroups_short
cl_khr_spir
cl_intel_accelerator
cl_intel_driver_diagnostics
cl_khr_priority_hints
cl_khr_throttle_hints
cl_khr_create_command_queue
cl_intel_subgroups_char
cl_intel_subgroups_long
cl_khr_il_program
cl_intel_mem_force_host_memory
cl_intel_spirv_media_block_io
cl_intel_spirv_subgroups
cl_khr_spirv_no_integer_wrap_decoration
cl_intel_unified_shared_memory_preview
cl_khr_mipmap_image
cl_khr_mipmap_image_writes
cl_intel_planar_yuv
cl_intel_packed_yuv
cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics
cl_khr_image2d_from_buffer
cl_khr_depth_images
cl_intel_media_block_io
cl_khr_3d_image_writes
cl_khr_gl_sharing
cl_khr_gl_depth_images
cl_khr_gl_event
cl_khr_gl_msaa_sharing
cl_intel_dx9_media_sharing
cl_khr_dx9_media_sharing
cl_khr_d3d10_sharing
cl_khr_d3d11_sharing
cl_intel_d3d11_nv12_media_sharing
cl_intel_unified_sharing
cl_intel_subgroup_local_block_io
cl_intel_simultaneous_sharing

Yes. That's correct.  cl_khr_fp64 is missing.
Interresting, because kernel that I load dont't use double. See below my kernel:

LoadAutoGroupedStreamKernel<Index1D, ArrayView<byte>, ArrayView<byte>, ArrayView<byte>, ArrayView<byte>, ArrayView<BoundArray>, int, int, Size, int, int, ArrayView<int>, ArrayView<int>, ArrayView<Line>, int>

**Comment by MoFtZ** [comment]
The use of `double` type could be within the kernel itself.

The exception thrown by ILGPU should have an inner exception, which has information about the line where the compilation error occurred. Does that help?

**Comment by m4rs-mt** [comment]
@RER009 Do you use some of the "official" `Math.XYZ` methods? These are usually preset to some 64-bit math double implementations.

**Comment by RER009** [comment]
InnerException | {"Float64 (double) type is not supported on this device."} 

StackTrace :

   at ILGPU.Backends.OpenCL.CLTypeGenerator.GetBasicValueType(BasicValueType basicValueType)
   at ILGPU.Backends.OpenCL.CLTypeGenerator..ctor(IRTypeContext typeContext, CLCapabilityContext capabilities)
   at ILGPU.Backends.OpenCL.CLBackend.CreateKernelBuilder(EntryPoint entryPoint, BackendContext& backendContext, KernelSpecialization& specialization, GeneratorArgs& data)
   at ILGPU.Backends.CodeGeneratorBackend`4.Compile(EntryPoint entryPoint, BackendContext& backendContext, KernelSpecialization& specialization)
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)

**Comment by RER009** [comment]
@m4rs-mt,
I don't use Math.XYZ in kernel implementation.

I did a little test. When I try to load an empty kernel with an integer parameter, I have the same issue:


` this._kernelTemp = this._gpu.LoadAutoGroupedStreamKernel<Index1D,int>(ApplyKernelTemp);`
 ...
` private static void ApplyKernelTemp(Index1D curIndex,int test) { }`

**Comment by RER009** [comment]
I did other tests with ILGPU samples :

DeviceInfo, SimpleAlloc works fine (no exceptions).

SimpleAtomics sample has the same issue : {"Float64 (double) type is not supported on this device."}

**Comment by m4rs-mt** [comment]
@RER009 I am able to reproduce this issue. It turns out to be a problem with the initialization of the `CLTypeGenerator` on devices that generally do not support 64-bit floating-point values. Regardless of whether they actually use 64-bit floating point values or not...

**Comment by RER009** [comment]
It works on 1.0.0-rc4. 👍
Thanks.
