### ISSUE TITLE
Sample for OpenGL interop

### ISSUE THREAD

**Issue by diwot** [m4rs-mt/ILGPU#695]
Hello, 
is there a sample somewhere about how to share a ILGPU cuda buffer with OpenGL, e. g. to render a triangle mesh generated by cuda without having to copy the data to the CPU? I saw that there is a library for SharpDX interop but I could not find an equivalent for OpenGL. With some hints about how to get started, I might be able to write one myself. OpenTK is used as C# OpenGL library.

**Comment by m4rs-mt** [comment]
@Joey9801 has been working on an interop example to exchange data between [Cuda and OpenGL](https://github.com/Joey9801/IlgpuSims/tree/master/IlgpuSims) via the `Interop` API. We are currently thinking about reviving the old [ILGPU.SharpDX](https://github.com/m4rs-mt/ILGPU.SharpDX) project while adding support for `Vulkan` and `OpenGL`.

**Comment by Costigan** [comment]
I came wanting to ask a similar question.  In my case, I want to create textures using ILGPU, as opposed to vertex buffers. 
 Also, in my specific case, I'm using OpenGL-accelerated skia (via skiasharp) rather than OpenGL via OpenTK.  I'm hoping buffer sharing would be similar.  Examples would be great.

**Comment by MoFtZ** [comment]
@Costigan The core concepts for interfacing with OpenGL are the same. You need to call the [Graphics Interop functions](https://github.com/Joey9801/IlgpuSims/blob/master/IlgpuSims/CudaGlInterop.cs) to register, map, unmap, and get the buffer pointer.

I have not used SkiaSharp, but it looks like the base `SKNativeObject` class has a `Handle` property that will give you access to the native handle.

More information:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#graphics-interoperability

**Comment by Costigan** [comment]
@MoFtZ Thank you.  I'll check it out.

**Comment by m4rs-mt** [comment]
We are closing this issue for now. If the general problem persists, we can safely reopen this issue.
