### ISSUE TITLE
Upgrade ILGPU v0.10 To 1.0.0-rc4

### ISSUE THREAD

**Issue by RER009** [m4rs-mt/ILGPU#698]
Hello,
I have just finished the upgrade from 0.10 to 1.0.0-rc4. My code works correctly.

However, I see that when another process use GPU ressources, my software become unstable.
My test is : running my software only VS my software + live video on Youtube.

Do you have any idea on this issue? 
I suspect byte[] copy from CPU To GPU but it is not clear at this stage.

When I do the same test with ILGPU 0.10,  I have no problem.

Do you know if there are some parameters/priority settings to set for OpenCL 3.0 ?

Thanks for your help.

**Comment by m4rs-mt** [comment]
@RER009 Thanks for your feedback on the latest RC4 release. That sounds like a really interesting problem to investigate. What exactly do you mean by a `byte[]` copy from CPU to GPU memory? Are you using one of the copy methods that are equipped with an extra `AcceleratorStream` parameter?

**Comment by m4rs-mt** [comment]
@RER009 I'm closing this issue for now. If the problem persists, we can always reopen this issue.
