### ISSUE TITLE
__shfl_up_sync equivalent

### ISSUE THREAD

**Issue by diwot** [m4rs-mt/ILGPU#711]
Hi,
is there an equivalent for the cuda shuffle functions in their sync version? Specifically I'm trying to access __shfl_up_sync in ILGPU but Warp.ShuffleUp has no overload that takes a mask as first argument like all the sync warp shuffles do. It looks like the non-sync shuffle functions were deprecated according to the cuda manual: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-shuffle-functions

**Comment by m4rs-mt** [comment]
@diwot Thank you for your question. Indeed, `Warp.ShuffleUp` is lowered to a `__shfl_up_sync` instruction in the PTX world. However, the mask is generated by the compiler. If you want to do a "sub-warp" shuffle, you can use one of the `Warp.Shuffle` instructions.

**Comment by m4rs-mt** [comment]
@diwot I'm closing this issue for now. If you have any further questions and/or feature requests, please let us know.
