### ISSUE TITLE
Feature Request: Asynchronous CopyTo

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#715]
It appears that on at least some platforms, CopyTo is synchronous. Right now I want to be able to issue more simultaneous copy requests than I have conveniently accessible threads. Would it be possible to add an asynchronous version of CopyTo?

**Comment by MoFtZ** [comment]
`CopyToCPU` and `CopyFromCPU` have an implied call to `stream.Synchronize`.

Have you seen `CopyToCPUUnsafeAsync` and `CopyFromCPUUnsafeAsync`?

**Comment by Ruberik** [comment]
Sorry for the ambiguity. I mean CopyTo from GPU to GPU.

**Comment by MoFtZ** [comment]
Ah, I see. In that case, `CopyTo` does not have an implied call to `stream.Synchronize`. And it is already using the asynchronous copy command in Cuda.

Could this be a driver issue? Or something to do with how Cuda contexts/streams behave together?

**Comment by Ruberik** [comment]
This was my mistake. On a particularly beefy 8-GPU machine, it turns out the latency to issue to the CopyTo command (for 1GB of data) was about 4ms, which was also how long the copy itself happened to take. I see the same latency in C, so ILGPU is thoroughly uninvolved in this issue!
