### ISSUE TITLE
CLTypeGenerator generates wrong code for structure definition if the structure contains many nested structures

### ISSUE THREAD

**Issue by nguyenvuduc** [m4rs-mt/ILGPU#72]
I have created pull request for fixing this. Below is a copy of the error description

Issue: compiling kernel code that contains a struct like this will generate invalid kernel code for OpenCL:

        public struct CompositeStruct
        {
            public CompositeStructComponent1 Field;
        }

        public struct CompositeStructComponent1
        {
            public CompositeStructComponent2 Field;
        }

        public struct CompositeStructComponent2
        {
            public int Field1;
            public float Field2;
        }

Generated kernel code:

	struct internal_type_10;
	struct internal_type_11;
	struct internal_type_12;
	struct internal_type_13;

	struct internal_type_10
	{
		int field_0;
	};
	struct internal_type_12
	{
		struct internal_type_13 field_0;
	};
	struct internal_type_11
	{
		struct internal_type_12 field_0;
	};
	struct internal_type_13
	{
		int field_0;
		float field_1;
	};

which will cause an error: 

	3:12:26: error: field has incomplete type 'struct internal_type_13'
			struct internal_type_13 field_0;
									^
	3:4:8: note: forward declaration of 'struct internal_type_13'
	struct internal_type_13;
		   ^

Suggested fix: the GetSerializedTypeList method should do a deep check when it is checking if a structure is referencing another structure.

**Comment by m4rs-mt** [comment]
@nguyenvuduc Thank you for your bug report. I am currently restructuring large parts of the code, including the OpenCL backend. There will be no more nested structures in the near future in the scope of the ILGPU IR. This will implicitly solve this problem.
