### ISSUE TITLE
Suggestion : References or dependency downloads of CUDA(+else if possible) DLLs

### ISSUE THREAD

**Issue by PascalSoftwares** [m4rs-mt/ILGPU#722]
While testing through ilgpu examples, meeting System.DllNotFoundException for cuda dlls is quite often.

I know I can guess CUDA SDK version from error message and install it manually, but I hope there will be some reference document of version of CUDA currently library requires (i.e CUDA SDK version xx.x, cublas64_xx.dll etc).

And hopefully, providing exact dll files itselves for download will be much more grateful if could...

**Comment by MoFtZ** [comment]
hi @PascalSoftwares. There is no need to guess the Cuda SDK version.

ILGPU supports CUDA SDK v10 and v11. Some parts may even support CUDA SDK v9. You should install the version of the SDK that suits your needs. If you are not sure, then install the latest CUDA SDK.

Note that the Cuda SDK version number may not match the DLL required. For example, the Cuda v11 SDK comes with the cublas v10 DLLs.

ILGPU is a standalone library, and does not need the Cuda SDK DLLs to run. You only need to install the Cuda SDK if you want to use the Cuda-specific libraries.

Unfortunately, I don't think it would be appropriate for ILGPU to provide the Cuda DLLs. The first reason is that there are potential licensing issues with distributing the Cuda SDK DLLs. The second reason is that this would limit the support to that specific Cuda SDK version, rather than a broad range of SDKs.

**Comment by PascalSoftwares** [comment]
Thank you for answer, and could I make clear some of my comprehensions?

> hi @PascalSoftwares. There is no need to guess the Cuda SDK version.
> 
> ILGPU supports CUDA SDK v10 and v11. Some parts may even support CUDA SDK v9. You should install the version of the SDK that suits your needs. If you are not sure, then install the latest CUDA SDK.
> 
> Note that the Cuda SDK version number may not match the DLL required. For example, the Cuda v11 SDK comes with the cublas v10 DLLs.
> 
> ILGPU is a standalone library, and does not need the Cuda SDK DLLs to run. You only need to install the Cuda SDK if you want to use the Cuda-specific libraries.
> 
> Unfortunately, I don't think it would be appropriate for ILGPU to provide the Cuda DLLs. The first reason is that there are potential licensing issues with distributing the Cuda SDK DLLs. The second reason is that this would limit the support to that specific Cuda SDK version, rather than a broad range of SDKs.

From your answer, you seem suggested not to read from exception messages and just to install latest cuda sdk, right? I hope it is correct.

> ILGPU is a standalone library, and does not need the Cuda SDK DLLs to run. You only need to install the Cuda SDK if you want to use the Cuda-specific libraries.

Sorry but little confused with this... Is this means cuda-related parts(cudaaccelerator class and related codes?) of ILGPU is not 'standalone' ILGPU itself and considered as additional 'specific' ones requires users to help themselves? Or is there some differences between 'cuda sdk installation for ilgpu' and 'cuda sdk dlls not needed for ilgpu' I currently missing?

**Comment by MoFtZ** [comment]
To use ILGPU, you need to install the Nvidia Graphics Drivers for your GPU. The CudaAccelerator class is part of ILGPU, and can be used without installing the Cuda SDK.

The Cuda SDK is required if you want to use the libraries provided by Nvidia, such as CuRand, CuBlas, CuFFT, NVML, etc.

If you run the ILGPU sample projects that use these Cuda libraries, ILGPU will attempt to automatically detect the location of the Cuda DLLs, and the installed version of the Cuda SDK. ILGPU will try to load the latest version of the Cuda SDK first, and then try older versions.

**Comment by PascalSoftwares** [comment]
> To use ILGPU, you need to install the Nvidia Graphics Drivers for your GPU. The CudaAccelerator class is part of ILGPU, and can be used without installing the Cuda SDK.
> 

Thank you, the ' (cudaaccellerator?) ' guess was totally my miss.

> The Cuda SDK is required if you want to use the libraries provided by Nvidia, such as CuRand, CuBlas, CuFFT, NVML, etc.
> 
> If you run the ILGPU sample projects that use these Cuda libraries, ILGPU will attempt to automatically detect the location of the Cuda DLLs, and the installed version of the Cuda SDK. ILGPU will try to load the latest version of the Cuda SDK first, and then try older versions.

So samples requiring CUDA SDKs are actually needs additional libraries outside ILGPU itself, right? Cublas glue class was in ILGPU.Algorithm, then you mean ILGPU, not ILGPU.Algorithm is fully independent and to call some codes in ILGPU.Algorithm I need to install cuda SDK.

I am convinced to install the latest sdk. But at the beginning the post was originally for reference hint of CUDA version number itself currently utilizing through samples, first of all...

**Comment by MoFtZ** [comment]
The release notes for the Cuda SDK provides the version number of the DLLs:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions

You will notice that the Cuda v11 SDK includes CuRand v10.2.7.107 and CuFFT v10.6.0.107.

ILGPU.Algorithms provides access to functionality that will work without installing the Cuda SDK. However, to use CuBlas, CuRand, CuFFT and other Cuda libraries, you will need to install the Cuda SDK.

The next version of ILGPU (v1.1) will include support for LibDevice, which requires the the Cuda SDK if you want to use that functionality.

**Comment by m4rs-mt** [comment]
@PascalSoftwares We have discussed internally about this issue and we think that we will add better error messages. This way, it should be relatively easy to install the appropriate Cuda SDK, if needed, without adding the native Cuda libraries to our Nuget package.

We are closing this issue for now and will provide PRs when ready. Thanks again for your feature request 👍.
