### ISSUE TITLE
How to determine max # of concurrent threads for a Kernel

### ISSUE THREAD

**Issue by bnemetchek2** [m4rs-mt/ILGPU#725]
after loading a kernel with LoadAutoGroupedStreamKernel, is there a way to determine how many concurrent threads will execute on a device?

**Comment by MoFtZ** [comment]
@bnemetchek2 what would you do if you knew the number of threads?

Auto-grouped kernels are specific to ILGPU, and not part of Cuda. When launching an auto-grouped kernel, you specify the number of threads as the first argument.
e.g.
```CSharp
var kernel = accelerator.LoadAutoGroupedStreamKernel(....);
kernel(numThreads, .....);
```
If this is the number you want, it is not directly accessible from within the kernel. However, you can pass it as a separate kernel parameter yourself.

**Comment by m4rs-mt** [comment]
As @MoFtZ said, it is not intended to "control" the number of concurrent threads. Internally, the kernel launchers determine a "good" thread group configuration to setup the kernel grid for you. They use information about the supported group sizes and the maximum number of concurrent threads.

**Comment by bnemetchek2** [comment]
I believe I'm not looking something called occupancy.  ie, the kernel may be called to run 1M threads, but maybe only 10K of them can run at once.  Just wondering if this info is available?

**Comment by m4rs-mt** [comment]
@bnemetchek2 The maximum number of parallel threads of a single `Accelerator` can be determined by querying the `MaxNumThreads` property. To answer your question, an auto-grouped kernel may or may not use this number of threads to process your task in parallel. However, it will never exceed this number of parallel threads, as this is a hardware limitation. As for scheduled threads, the number may be higher than the maximum number of parallel threads on the device.
