### ISSUE TITLE
OpenCL local array compile error

### ISSUE THREAD

**Issue by NicolasG3** [m4rs-mt/ILGPU#73]
Try to use a local array (here in simple kernel sample) 
```
       static void MyKernel(
            Index index,               // The global thread index (1D in this case)
            ArrayView<int> dataView,   // A view to a chunk of memory (1D in this case)
            int constant)              // A sample uniform constant
        {
            float[] myArray = new float[32];
            myArray[0] = 0;
            //dataView[index] = index + constant;
        }
```
Result output (only for OpenCL accelerator):
```
Kernel loading failed:
Compilation started
2:61:17: error: initializing 'float *' with an expression of type '__generic float *' changes address space of pointer
        private float* var13 =  & var10.field_0[var11];
                       ^        ~~~~~~~~~~~~~~~~~~~~~~
Compilation failed
Exception levée : 'ILGPU.Runtime.OpenCL.CLException' dans ILGPU.dll
```

**Comment by m4rs-mt** [comment]
@NicolasG3 Thank you very much for your bug report. Please note that support for local arrays is very experimental at the moment, as these are reference types. Please also note that the OpenCL backend is still in an experimental state. However, this clearly seems to be a bug in the OpenCL backend.

**Comment by m4rs-mt** [comment]
I guess you are using an AMD accelerator? This problem does not occur on an Intel HD graphics device.

**Comment by m4rs-mt** [comment]
The OpenCL backend is currently being updated. All pointers are explicitly commented with their address space, and local assignments are cast into the appropriate pointer address spaces.
