### ISSUE TITLE
Is the largest 'Index' useable max value of int?

### ISSUE THREAD

**Issue by GaryMcD** [m4rs-mt/ILGPU#735]
Oops. Pressed enter on accident. Filling in now....

New to the community, so hopefully my question is not a waste of other's time. When utilizing the "LoadedKernel" method to initiate the work on my CUDA GPU the index parameter can only be an int value. Yet when working with that same Index1D object within the kernel it has methods for converting to a uint or long. 

Does this indicate we can initiate kernels with more work than Int.MaxValue?

**Comment by MoFtZ** [comment]
hi @GaryMcD, welcome to the community.

Short answer is that yes, the `Index1D` is limited to `Int.MaxValue`.

The Index structs are also used for indexing into the ArrayViews. For example, you can use `LongIndex1D` if you need to access a extremely large array. However, `LongIndex1D` cannot be used as a kernel parameter.

Regarding the kernel Index parameter:

Using the native CUDA API, it is possible to launch a kernel with X, Y and Z indices. X is limited to 2^31 - 1, and Y and Z are limited to 65535.

In ILGPU, this is referred to as an Explicitly Grouped Kernel. The kernel function does not use an Index parameter. Within the kernel, you can use the `Grid` and `Group` classes to access the indices. This is the equivalent to the native CUDA APIs `gridDim`, `blockIdx`, `blockDim` and `threadIdx`.
https://github.com/m4rs-mt/ILGPU/tree/master/Samples/ExplicitlyGroupedKernels/Program.cs

ILGPU also provides Implicitly/AutoGrouped kernels. This is the kernel function that uses an Index parameter.
https://github.com/m4rs-mt/ILGPU/blob/master/Samples/ImplicitlyGroupedKernels/Program.cs

**Comment by GaryMcD** [comment]
Thank you for the thorough answer. To ensure I understand the concepts correctly (as this is all new to me, even CUDA itself).

With the Implicitly Grouped Kernel when I load it, I provide a single integer value. And then the actual code within the kernel method I define is "initiated" with a different "index" along the way from 0 to the supplied integer value.

In comparison, the Explicitly grouped Kernel, when loaded is not provided an integer value. And when the actual code within the kernel method is "initiated" each "iteration" has access to a different triplet of XYZ indices with the static "Grid". Thus meaning I could sort of imagine one run of the internal code would see an XYZ of 0,0,0 and the "next" would see an XYZ of 0,0,1. This would continue through to the max values?

**Comment by MoFtZ** [comment]
Yes, this is all correct. But please note that it would start from 0, and up to, but excluding, the supplied integer value.

Also note that for Implicitly Grouped Kernels, you can use `Index1D`, `Index2D` or `Index3D` as the index parameter.

**Comment by GaryMcD** [comment]
Thank you all so much! This helps me immensely.
