### ISSUE TITLE
Not recognizing OpenCL driver on Linux/armhf

### ISSUE THREAD

**Issue by n8allan** [m4rs-mt/ILGPU#738]
I've compiled and installed the CPU based [pocl](https://github.com/pocl/pocl) driver and I get the below dump from clinfo, yet ILGPU fails to enumerate the device.  Is there something else I should be looking for, or a way to trace why the device isn't being picked up?
.Net 5.  OS is Raspberry Pi OS (~Debian).
Here's the code:
```CSharp
var builder = Context.Create().OpenCL().DefaultCPU().AutoAssertions().AutoIOOperations();
_context = builder.ToContext();
foreach (var device in _context.GetCLDevices())
    ... // nothing
```
And the dump from clinfo:
```
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 2.0 pocl 1.9-pre master-0-gadfd647c  Linux, Debug+Asserts, RELOC, LLVM 7.0.1, SLEEF, FP16, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_pocl_content_size
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-cortex-a72
  Device Vendor                                   ARM
  Device Vendor ID                                0x13b5
  Device Version                                  OpenCL 1.2 pocl HSTR: pthread-armv6k-unknown-linux-gnueabihf-cortex-a72
  Driver Version                                  1.9-pre master-0-gadfd647c
  Device OpenCL C Version                         OpenCL C 1.2 pocl
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               4
  Max clock frequency                             1500MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     equally, by counts
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              8
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    32, Little-Endian
  Global memory size                              2758772736 (2.569GiB)
  Error Correction support                        No
  Max memory allocation                           1073741824 (1024MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            67108864 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
  Local memory type                               Global
  Local memory size                               524288 (512KiB)
  Max number of constant args                     8
  Max constant buffer size                        524288 (512KiB)
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  printf() buffer size                            16777216 (16MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_fp16 cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
  clCreateContext(NULL, ...) [default]            Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-cortex-a72
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-cortex-a72
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-cortex-a72

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
```

**Comment by MoFtZ** [comment]
hi @n8allan.

ILGPU requires OpenCL v2.0 or greater. In addition, if using OpenCL v3.0 or greater, it also requires support for the Generic Address Space extension (this extension is mandatory in OpenCL v2.x).

It looks like your device is only capable of OpenCL v1.2.

You could try changing the OpenCL initialization to return all devices, even if not supported.
```CSharp
var builder = Context.Create().OpenCL(device => true);
_context = builder.ToContext();
foreach (var device in _context.GetCLDevices())
```

**Comment by n8allan** [comment]
Thank you for your assistance @MoFtZ .  Strangely, even with the `device => true` lambda, it still has no devices in the iterator. In the long dump I see several versions mentioned:
`Platform Version                                OpenCL 2.0 pocl 1.9-pre master-0-gadfd647c  Linux, Debug+Asserts, RELOC, LLVM 7.0.1, SLEEF, FP16, POCL_DEBUG`
`Device Version                                  OpenCL 1.2 pocl HSTR: pthread-armv6k-unknown-linux-gnueabihf-cortex-a72`
`Driver Version                                  1.9-pre master-0-gadfd647c`
`Device OpenCL C Version                         OpenCL C 1.2 pocl`
`ICD loader Profile                              OpenCL 2.2`
I'm not sure what to make of all that, but from what you're saying I infer that "Device Version" must be the issue.  In reading more on pocl I see that it talks about 2.0 features that it implements, but never expressly states that it supports 2.0 or advertises 2.0.

Oh well, I guess there aren't any easy answers for speeding up a critical function in .NET on Raspberry Pi 4.  Maybe I'll just write a C-loop and P/invoke into it to see if I can get a little more performance out of my function or try intrinsics.  Thanks anyway for the help!

**Comment by MoFtZ** [comment]
@n8allan according to the PoCL website, it is an "implementation of the OpenCL standard (1.2 with some 2.0 features supported)". So unfortunately, it would not be supported by ILGPU.

Also, I could not find any documentation to say that PoCL supports the GPU on the Raspberry PI 4. If that's the case, the `CPUAccelerator` provided by ILGPU would not be a good replacement. This accelerator is designed to help you debug your GPU algorithms, and will not "accelerate" anything. You will get much better performance using a pure CPU implementation rather than this CPU accelerator.

If you're trying to get the most performance out of .NET on the Raspberry PI 4, have you considered using the ARM hardware intrinsics?
https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.arm

Also, upgrading to .NET 6.0 might help too, as they appear to be making regular performance improvements.

**Comment by n8allan** [comment]
Yep, I've begun exploring intrinsics, though .NET 6 is also a great idea, thanks!  It's too bad nobody has built an OpenCL implementation for videocore VI yet.

In case you're curious, my application involves computing the "brightest" pixel in proximity, with a logarithmic falloff factor.  Under windows I was using OpenCL and turned the logarithmic function into a 41x41 mask grid.  My per pixel kernel did a nested loop on the mask grid for proximate pixels and took the max.  This took a fraction of a second on a low-end Intel Celeron.  My brute force algorithm in .NET currently takes about 30s per image on the Pi.  

Intrinsics are difficult and error prone development due to all the alignment issues, but seems relatively straight forward.  An OpenGL shader would probably be a more logical approach; it's just such an unfamiliar world to me and to try to get that working from .NET on Linux/armhf just seems like days of torture.

Maybe I'll start with .NET 6 though and see if some of the work in eliminating bounds checks etc. might make a big difference and I can see if a sprinkling of intrinsics pushes me over the finish line.  Y'all have done an excellent job with ILGPU BTW; looking forward to when I get to use it in something.

**Comment by MoFtZ** [comment]
Not sure if you've seen this project:
https://github.com/Idein/py-videocore6

It's a Python library for GPGPU programming the VideoCore VI. Looks pretty low-level, but it's the only library I've been able to find that even tries to talk to that GPU.

If it works, you could maybe even try a port to .NET interop? It doesn't appear to be a particular large library.

**Comment by n8allan** [comment]
I did notice that project; it's interesting.  I also found a BLAS library in C++ based on that project [here](https://github.com/Idein/qmkl6/blob/master/test/dot.cpp)  I am somewhere between impressed and frightened that they managed to repurpose python commands into a poor-man's assembler.  It wouldn't be very difficult to do similarly in .NET, but I think the bigger problem is that of having to program in GPU assembly to begin with.  Learning a new machine code would no doubt be a fun exercise, were I on the market for fun exercises.  :-)

A backend would be the ideal place to interface, of course.  I suspect the easiest lift for someone would be to fork the LLVM VideoCore IV backend and port to VideoCore VI since the changes aren't that extensive, then OpenCL and other options would be all but done.  I guess a bounty needs to be put up or something to make it worth someone's while.

**Comment by MoFtZ** [comment]
Another option to consider, the Raspberry Pi 4 [supports OpenGL ES 3.1](https://www.cnx-software.com/2020/02/03/raspberry-pi-4-opengl-es-3-1-conformant-vulkan-drivers/), which has support for Compute Shaders. Would this work for you?

**Comment by n8allan** [comment]
I found an [interesting project](https://github.com/Sergio0694/ComputeSharp) that's somewhat like what we're talking about but for HLSL shaders.

**Comment by MoFtZ** [comment]
Going further down the rabbit hole, the Raspberry Pi 4 is also [Vulkan 1.1 conformant](https://www.raspberrypi.com/news/vulkan-update-version-1-1-conformance-for-raspberry-pi-4/).

I have not used these projects before, but you can try:

Veldrid
https://github.com/mellinoe/veldrid
https://github.com/mellinoe/veldrid-samples

Vortice.Vulkan
https://github.com/amerkoleci/Vortice.Vulkan

@m4rs-mt might have some other suggestions too, regarding OpenGL ES and Vulkan libraries for .NET.

Regarding adding Compute Shader support to ILGPU, we have an old [feature request for SPIR-V](https://github.com/m4rs-mt/ILGPU/issues/16) that would be a step towards that. A member of the community was trying to [start the groundwork](https://github.com/m4rs-mt/ILGPU/pull/611), but it needs a proper review and further discussions. It is still a long way from completion, so I  would not rely on the milestone assigned.

You're welcome to join us on our [Discord server](https://discord.gg/X6RBCff). You could join in the discussions, help with that work, and/or propose your own solutions.

**Comment by n8allan** [comment]
I was thinking of trying out OpenTK, but Veldrid also looks viable, thanks for making me aware of that.  Also thanks for pointing me at the Discord server.
