### ISSUE TITLE
OpenCL IsNaNF not implemented

### ISSUE THREAD

**Issue by NicolasG3** [m4rs-mt/ILGPU#74]
I tried to use a float shared memory variable (replace int by float in SharedMemory sample)
```
       static void SharedMemoryVariableKernel(
            GroupedIndex index,               // The grouped thread index (1D in this case)
            ArrayView<int> dataView,          // A view to a chunk of memory (1D in this case)
            ArrayView<int> outputView)        // A view to a chunk of memory (1D in this case)
        {
            // Compute the global 1D index for accessing the data view
            var globalIndex = index.ComputeGlobalIndex();

            // 'Allocate' a single shared memory variable of type float
            ref float sharedVariable = ref ILGPU.SharedMemory.Allocate<float>();
            ...

```
This lead to an exception (only for OpenCL)
> NotSupportedIntrinsicException : The function 'IsNaNF' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?

**Comment by m4rs-mt** [comment]
The latest OpenCL backend updates should solve this problem. I will close this issue for now. If the problem persists in a future release, please reopen this issue or create another bug report.
