### ISSUE TITLE
Is the performance impact of implementing a progress monitor (like the sample 'MonitorProgress') negligible? If not, can its impact be reduced?

### ISSUE THREAD

**Issue by GaryMcD** [m4rs-mt/ILGPU#740]
Context. I am running a kernel that for the sake of my GPU's capabilities would in theory run forever. (The kernel has in the order of 2 to the power of 256 computations to accomplish). I would like to get progress updates on where it is at, but not at the cost of its work.

Prior to implementing an imitation of the sample 'MonitorProgress' I was just loading, resetting memory, and loading the kernel again with workloads in the 100s of millions. It would complete them in less than a second. Once I implemented the progress monitor, which utilized an atomic add on a long, and then checked the long value on the host side it wouldn't hit 100million for ~30 seconds.

Is there a way to monitor progress from a batch perspective, without having to stop and restart the kernel completely? As an example, some way to see updates every X amount of computations.

Additional Context, in reality I don't care as much about where it is at in number of computations, but rather number of computations that resulted in a desired value. I was first implementing the progress monitor to get a feel for how I might implement a monitor on successful/desired values found.

**Comment by MoFtZ** [comment]
The sample project for monitoring progress was created in response to a question from a member of the community:
https://github.com/m4rs-mt/ILGPU/issues/590

The original solution on stackoverflow suggested there was no performance penalty. However, I have not personally measured its performance, nor used it in any of my own projects.

The likely cause of any performance loss is the call to memory fence.
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions

Is there a way for your kernel to resume execution? So it can perform the first millions computations, stop, and then the next kernel call will pick up where it left off?

**Comment by MoFtZ** [comment]
Also, your performance loss is substantial. Have you tried reducing the frequency of reporting progress? Say just once every 100,000 computations?

**Comment by GaryMcD** [comment]
I want to start off by thank you all for your replies. You're all far more legit than I am with these things.

What I opted for was a solution as follows - under these circumstances I don't see any impact if at all.

```
public static void Kernel(....)
{
   // Some per thread var initialization

   do
   {
      // Work without any divergence

      // Obvious Divergence
      if(GlobalIndex % int.MaxValue == 0)
      {
         Atomic.Add(ref SchedulesChecked[0], int.MaxValue);
         MemoryFence.DeviceLevel();
      }
      
      // Per Thread Iteration of local vars

      // Ensures divergence is stopped for next iteration
      Group.Barrier();

   } while (condition)
}
```

Curious if the memory fence is even needed in my scenario above? My understanding of atomic activities is that they are ensured to not have thread issues. Please correct me if I am wrong.

**Comment by MoFtZ** [comment]
You are correct that the call to Atomic.Add does not have any threading issues.

My understanding of the original purpose of the memory fence was to make the changes visible to the host CPU thread that is monitoring the progress value, but I may be wrong here.

**Comment by GaryMcD** [comment]
Ah, that makes sense. Sounds like the memory fence allows for a thread safe read from the host side for the profiling marker?

I will close this, as my original question/purpose has been resolved.

**Comment by MoFtZ** [comment]
Not that it makes it thread safe. Sounds like the GPU is not required to perform certain updates/actions - or can perform them in a lazy manner.

The documentation for [memory fence](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions) says that the system fence:
> ensures that all writes to all memory made by the calling thread before the call to __threadfence_system() are observed by all threads in the device, host threads, and all threads in peer devices as occurring before all writes to all memory made by the calling thread after the call to __threadfence_system().
