### ISSUE TITLE
Regression in Interop.WriteLine affecting ILGPU v1.1.0-beta1.

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#744]
Using the ILGPU `SimpleWriteLine` sample project, the Cuda and OpenCL accelerators no longer write output.

Appears to be caused by #704. The `DeadCodeElimination` transform is removing the `WriteToOutput` IR nodes.

**Comment by m4rs-mt** [comment]
@MoFtZ I can confirm that the `DCE` transformation removes `WriteToOutput` values.
