### ISSUE TITLE
Question: copy memory between accelerator and unmanaged array

### ISSUE THREAD

**Issue by literaltofu** [m4rs-mt/ILGPU#755]
Hello,
I've been looking through the docs and the source code but could not find a solution to the following problem:
Is there a way to circumvent the allocation of managed memory when transferring memory from/to `MemoryBuffer`s? I'm mainly talking about unsafe code, for example an unmanaged array using a pointer or Unity Engine's `NativeArray`, which is Unity's wrapper around unmanaged memory for multi-threading. I'm curious because allocating something managed like `int[]` can be slower in certain situations, thus I'm trying to copy memory from the accelerator's device memory to a designated pointer/unamanaged array directly to minimize allocation time pre-copy. Is that currently possible?
Thank you for your time.
Kind regards,
ToFu

**Comment by MoFtZ** [comment]
hi @literaltofu.

The `CopyFromCPU` and `CopyToCPU` functions support the use of `Span<T>` as the source and destination. In addition, `Span<T>` provides a constructor that accepts a pointer and length. You might be able to use this to achieve your desired behaviour.

**Comment by literaltofu** [comment]
I must have overlooked that extension.
Works like a charm!
Thank you very much.
