### ISSUE TITLE
Problem with Algorithm of Unique

### ISSUE THREAD

**Issue by geobimmodeling** [m4rs-mt/ILGPU#757]
[AlgorithmsUnique.zip](https://github.com/m4rs-mt/ILGPU/files/8105382/AlgorithmsUnique.zip)

Please see attached sample code.  Exception of "Illegal memory access was encountered!" is thrown

**Comment by geobimmodeling** [comment]
the error occurs when length of array exceeds specific number.

**Comment by geobimmodeling** [comment]
I can't see fixed #758. The lasted change is #756

**Comment by MoFtZ** [comment]
#758 is still a pull request, and has not been merged into this repository yet.

If you want to try the changes now, you can directly access the PR here:
https://github.com/MoFtZ/ILGPU/tree/bug/unique

**Comment by MoFtZ** [comment]
Alternatively, you can access the nuget packages from the PR directly:
https://github.com/m4rs-mt/ILGPU/actions/runs/1879322147#artifacts

**Comment by geobimmodeling** [comment]
works now. thanks!
