### ISSUE TITLE
OpenCL backend constant handling

### ISSUE THREAD

**Issue by NicolasG3** [m4rs-mt/ILGPU#78]
Again with last 0.8 version, i tested the same code on 2 machines. One works and the other not.
I  found the difference in the backend generated kernel source.
On one machine, float constants are generated with local numeric separator (french,  comma)
```c#
	float var167 =  0,45f;
	float var168 =  0,1f;
```
on the other machine, it is correct
```c#
	float var167 =  0.45f;
	float var168 =  0.1f;
```
Another thing is integer negative constants.
I found  
```c#
int var175 =  4294967295;
```
 when expecting 
```c#
int var175 =  -1;
```

**Comment by m4rs-mt** [comment]
Seems to be a bug when using `ToString` it should be `ToString(CultureInfo.InvariantCulture)`.

**Comment by m4rs-mt** [comment]
@NicolasG3 Please note that `4294967295` is `-1` in two's complement. The value will be automatically converted into a signed int which will result in `-1`.
