### ISSUE TITLE
How can I apply exp or Bessel function to whole gpu array?

### ISSUE THREAD

**Issue by xichaoqiang** [m4rs-mt/ILGPU#780]
Hello,thanks for sharing this great package.

It seems the abs function can apply to whole array from example.

How can I apply exp or Bessel function to whole array?

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/161177430-a4501d4d-b067-4389-977d-201401c4a127.png)
Cuda has these api.

**Comment by MoFtZ** [comment]
hi @xichaoqiang, in ILGPU v1.1, we added support for `LibDevice`, which provides these functions on Cuda.

Have a look at the LibDevice sample code:
https://github.com/m4rs-mt/ILGPU/blob/master/Samples/LibDeviceKernel/Program.cs

Note that `LibDevice` is only available for Cuda, and will not work on the other accelerators (i.e. CPU and OpenCL).

**Comment by xichaoqiang** [comment]
Thanks @MoFtZ .The sample code works well.

But I can't understand how to define the value of input array.

Would you like to tell me?

Thank you very much.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply. @MoFtZ
