### ISSUE TITLE
Meet an error in JN function.

### ISSUE THREAD

**Issue by xichaoqiang** [m4rs-mt/ILGPU#781]
@MoFtZ 
I have try the build-in function in cuda library.

Abs,Cos, Sin, Exp,J0,Y0 are all OK.

But JN is not OK.

The error message is shown in the below figure.

My code is in the attachment.

Can you help me to check my code?
 
![image](https://user-images.githubusercontent.com/30900789/161217033-f82ed3a2-71e0-4bcb-9103-119fb8e7e7e7.png)

[Program.zip](https://github.com/m4rs-mt/ILGPU/files/8395603/Program.zip)

**Comment by MoFtZ** [comment]
Thanks for reporting this issue @xichaoqiang.

`LibDevice` is a new feature in ILGPU v1.1. It looks like ILGPU is failing to generate the correct Cuda/PTX instructions for the JN function.

**Comment by MoFtZ** [comment]
hi @xichaoqiang. I have raised a PR to fix this issue. It appears that the defect in ILGPU affects any `LibDevice` function that uses an `int`, `uint`, `long`, `ulong` or `Half` data types. For now, you should be able to use the `LibDevice` functions that use only `float`, `double` or `string` types.
