### ISSUE TITLE
How can I apply exp function a complex value array?

### ISSUE THREAD

**Issue by xichaoqiang** [m4rs-mt/ILGPU#782]
@MoFtZ 

I want to some scientfic compuation with complex value array.

How can I apply exp function to a complex value array?

Best regards,
Xi

**Comment by MoFtZ** [comment]
Unfortunately, Cuda/LibDevice does not provide any functions for complex numbers. You will need to write your own,or find an existing .NET implementation that can be ported to work on ILGPU.

**Comment by MoFtZ** [comment]
Thank you for the kind offer of adding this code to ILGPU. However, for now, I think we will not add support for complex numbers just for the `Exp` method.

Maybe in the future, we can consider adding support in ILGPU for complex numbers, for all the math functions.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
