### ISSUE TITLE
Instance kernel functions

### ISSUE THREAD

**Issue by maaron** [m4rs-mt/ILGPU#79]
It would be nice if the generic kernel load methods could work with type inference, so that you don't have to spell out the kernel argument types twice.  Unfortunately, it seems method groups aren't infer-able in this case, but I tried to do the following, which does compile but throws at runtime:

```
static class InferredKernel
{
    static Action<Index1, ArrayView<int>> Kernel =
        (index, output) =>
        {
            output[index] = index;
        };

    static void Test()
    {
        var kernel = accelerator.LoadAutoGroupedStreamKernel(Kernel);
    }
}
```

Is there any other way around this?

**Comment by m4rs-mt** [comment]
@maaron Thank you for your feedback. Unfortunately, type inference is currently performed very naively by the C# compiler, which leads to these detailed type annotations. There is not much we could do at the moment to solve these problems.

The problem with lambda functions in C# is that the C# compiler creates an instance method that references the parent lambda closure (also in your case). ILGPU does not currently support instance methods. However, I have already thought about adding support for lambda functions and limited support for reference types. This would allow you to compile this kernel function.

However, you might be able to use the @MoFtZ approach found [here](https://github.com/m4rs-mt/ILGPU.Samples/issues/7) to work around this problem.

**Comment by Kemsekov** [comment]
This is total madness but it actually works.

You can compile any predefined amount of functions only if they are stored as strings and reference them from `Execute` method which creates a loaded kernel.

So if you have a list of functions stored as string, you can just do some string concatenation and name referencing to generate c# source code for kernel creation that you need.

It is not a perfect solution, but hey, it works!

https://gist.github.com/Kemsekov/df25b58cd8b14b032685253cecacd641
