### ISSUE TITLE
I need help in creating Buffer using OpenCL

### ISSUE THREAD

**Issue by AbedKarmi** [m4rs-mt/ILGPU#794]
I tried to modify the code that allocates buffer to this  :

 CLException.ThrowIfFailed(CLAPI.CurrentAPI.CreateBuffer(accelerator.NativePtr, CLBufferFlags.CL_MEM_ALLOC_HOST_PTR, new IntPtr(LengthInBytes),IntPtr.Zero, out IntPtr resultPtr));

but the kernel throws an exception when it is called!     (INVALID_MEM_OBJECT)

_Originally posted by @AbedKarmi in https://github.com/m4rs-mt/ILGPU/issues/792#issuecomment-1100907643_

**Comment by m4rs-mt** [comment]
@AbedKarmi Thanks a lot for your question. I'm not 100% what you want to achieve. The easiest way to allocate a buffer using OpenCL is to use an OpenCL accelerator:
```c#
using var accelerator = context.CreateCLAccelerator(...);
using var buffer = accelerator.Allocate1D<int>(1024);
```

**Comment by AbedKarmi** [comment]
Yes, I want to monitor the progress and read the variable from cpu side. I tried to modify the code in the examples that achieve this for cuda devices, that worked greatly.

**Comment by AbedKarmi** [comment]
Here what I did 

// ---------------------------------------------------------------------------------------
//                                    ILGPU Samples
//                           Copyright (c) 2021 ILGPU Project
//                                    www.ilgpu.net
//
// File: OpenCLProgress.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------

using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.OpenCL;
using System;
using System.Runtime.CompilerServices;

namespace CryptoUtility
{
    /// <summary>
    /// Helper class to represent a single value that can be updated by the GPU to
    /// indicate progress of the kernel, and also read by the CPU to determine progress.
    /// </summary>
    class OpenCLProgress<T> : AcceleratorObject   where T : unmanaged
    {
        #region Nested Types

        /// <summary>
        /// Constructs a OpenCL buffer using host memory.
        /// </summary>
        class OpenCLProgressMemoryBuffer : MemoryBuffer
        {
          
            public OpenCLProgressMemoryBuffer(CLAccelerator accelerator, long length, int elementSize) : base(accelerator, length, elementSize)
            {
                CLException.ThrowIfFailed(CLAPI.CurrentAPI.CreateBuffer(accelerator.NativePtr, CLBufferFlags.CL_MEM_ALLOC_HOST_PTR , new IntPtr(LengthInBytes),IntPtr.Zero, out IntPtr resultPtr));
                NativePtr = resultPtr;
            }

            protected override void DisposeAcceleratorObject(bool disposing)
            {
                CLException.ThrowIfFailed(CLAPI.CurrentAPI.ReleaseBuffer(NativePtr));
                NativePtr = IntPtr.Zero;
            }

            protected override void CopyFrom(AcceleratorStream stream,
                                             in ArrayView<byte> sourceView,
                                             in ArrayView<byte> targetView) =>
                                    throw new NotImplementedException();

            protected override void CopyTo(AcceleratorStream stream,
                                            in ArrayView<byte> sourceView,
                                            in ArrayView<byte> targetView) =>
                                    throw new NotSupportedException();

            protected override void MemSet(AcceleratorStream stream,
                                           byte value,
                                           in ArrayView<byte> targetView) =>
                                    throw new NotSupportedException();
        }

        #endregion

        #region Properties

        /// <summary>
        /// Returns an array view that can be used to update the progress on the GPU.
        /// </summary>
        public readonly ArrayView<T> View;

        /// <summary>
        /// Holds the OpenCL memory buffer that contains the progress value.
        /// </summary>
        private readonly OpenCLProgressMemoryBuffer memoryBuffer;

        /// <summary>
        /// Gets or sets the current progress value from the CPU.
        /// </summary>
        public unsafe T Value
        {
            [NotInsideKernel]
            get
            {
                var ptr = (T*)memoryBuffer.NativePtr.ToPointer();
                return *ptr;
            }
            [NotInsideKernel]
            set
            {
                var ptr = (T*)memoryBuffer.NativePtr.ToPointer();
                *ptr = value;
            }
        }
        #endregion

        #region Instance
        
        public OpenCLProgress(CLAccelerator accelerator) : base(accelerator)
        {
                memoryBuffer = new OpenCLProgressMemoryBuffer(accelerator, 1, Interop.SizeOf<T>());
                View = new ArrayView<T>(memoryBuffer, 0, memoryBuffer.Length);
                Value = default;
        }

        protected override void DisposeAcceleratorObject(bool disposing) => memoryBuffer.Dispose();

        #endregion
    }
}

**Comment by m4rs-mt** [comment]
Alright, I see the problem you describe is not ILGPU specific, but related to the OpenCL API. Based on your use case of the `CLBufferFlags.CL_MEM_ALLOC_HOST_PTR` flag, I think you are missing the `CL_MEM_READ_WRITE` flag to make it accessible for read/write access. I also think you need to use `clEnqueueMapBuffer` to "turn" the buffer into read/write mode for further accesses. See [the official documentation](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueMapBuffer.html) for more information.

Please note that ILGPU does not include entry points for the `clEnqueueMapBuffer` method. Please also note that reading data on the host in parallel to running a kernel on the GPU is not guaranteed and does not work at all on any AMD GPUs I have tried.

**Comment by AbedKarmi** [comment]
Highly appreciated help. I would be so thankful if you provide a peice of code or information that helps how to implement this solution, so we can add it to samples with the working Cuda sample.

**Comment by MoFtZ** [comment]
@AbedKarmi
Regarding the use of `clEnqueueMapBuffer`, the documentation states that:
> If a memory object is currently mapped for writing, the application must ensure that the memory object is unmapped before any enqueued kernels or commands that read from or write to this memory object or any of its associated memory objects (sub-buffer or 1D image buffer objects) or its parent object (if the memory object is a sub-buffer or 1D image buffer object) begin execution; otherwise the behavior is undefined.
>
> If a memory object is currently mapped for reading, the application must ensure that the memory object is unmapped before any enqueued kernels or commands that write to this memory object or any of its associated memory objects (sub-buffer or 1D image buffer objects) or its parent object (if the memory object is a sub-buffer or 1D image buffer object) begin execution; otherwise the behavior is undefined. 

There is no way to satisfy the requirements for mapping in OpenCL and to perform what you want to do (aborting the kernel).

**Comment by m4rs-mt** [comment]
We are closing this issue for now. If the general problem persists, we can safely reopen this issue.
