### ISSUE TITLE
I want to create a temporary array in kernel， but  throw Exception, must be a compile-time constant and within the range of the array

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#801]
I want to create a temporary array in kernel， but  throw Exception, must be a compile-time constant and within the range of the array.
Can you tell me what to do? Thank you。ilgpu version 1.1.0.
my code:
```c#
 public static void FilterProjection(Index1D index, Int3 projectionDim, ArrayView<float> filterFactor,int filterCount, ArrayView<float> oneproj, ArrayView<float> filteredproj)
        {
            int i = index.X;
            var xdata = new Complex[filterCount];
            for (int j = 0; j < filterCount; j++)
            {
                if (j < projectionDim.Y)
                {
                    xdata[j] = new Complex(oneproj[j * projectionDim.X + i], 0.0f);
                }
                else
                {
                    xdata[j] = new Complex(0.0f, 0.0f);
                }
            }
            FTransfrom.fft(xdata)
            for (int j = 0; j < filterCount; j++)
            {
                xdata[j] *= filterFactor[j];
                //xdata[j] = new Complex(xdata[j].Real * filterFactor[j], xdata[j].Imaginary * filterFactor[j]);
            }
            FTransfrom.ifft(xdata);
            for (int j = 0; j < projectionDim.Y; j++)
            {
                filteredproj[j * projectionDim.X + i] = (float)xdata[j].Real;
            }
        }
```

**Comment by m4rs-mt** [comment]
Thank you for submitting this question/bug report @xxl-cc. Compiling kernels with dynamic memory allocations is not supported by ILGPU. There are several ways to "overcome" this problem in general: rewrite parts of your program to make them more generic, to avoid the memory allocation in the first place, or use `SpecializedValue` instances (which make dynamic values compile-time constants for kernels). What you can do is to change the signature of your kernel to
```c#
public static void FilterProjection(Index1D index, Int3 projectionDim, ArrayView<float> filterFactor, SpecializedValue<int> filterCount, ArrayView<float> oneproj, ArrayView<float> filteredproj)
```
and your allocation and loop code to
```c#
var xdata = new Complex[filterCount.Value];
for (int j = 0; j < filterCount.Value; j++)
```
However, adding `SpecializedValue` parameters also means that every time you pass a different value to this parameter, a completely new kernel is compiled and launched when invoked. This means improved kernel runtime performance on the one hand, but slower startup times on the other.
