### ISSUE TITLE
Stride1D.Dense doesn't have IStride1D interface

### ISSUE THREAD

**Issue by QsROg8320** [m4rs-mt/ILGPU#825]
Stride1D.Dense doesn't have IStride1D interface. 
I can't use View.As1DView(Stride1D.Dense)
https://github.com/m4rs-mt/ILGPU/blob/74d98289606c8af52550ccf0c56d6a074d7c38af/Src/ILGPU/Stride.cs#L261

**Comment by MoFtZ** [comment]
hi @QsROg8320.

`Stride1D.Dense` *does* implemented `IStride1D`.

`Stride1D.Dense` is a partial struct, so the rest of its code definition is in another location. In this particularly case, we are using T4 templates to provide the rest of the definition:
https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/StrideTypes.tt

Regarding your question of using `View.As1DView`, you actually need to create a new instance of `Stride1D.Dense`. So the code would be more like:
```CSharp
View.As1DView(new Stride1D.Dense())
```
Hope that helps.
