### ISSUE TITLE
Accessing Host Memory from Kernels

### ISSUE THREAD

**Issue by yuryGotham** [m4rs-mt/ILGPU#826]
Does ILGPU support accessing host memory from kernels? I would like to be able to (within kernel) to read data from CPU/Host memory, do some processing on it and write it back to another location on CPU/Host.

If it is possible to do with ILGPU, can somebody post code that does this - for example - read integers from one CPU-based array, increment them by 1 and write them to another CPU-based array.

The reason I need to do this from inside kernel is because I want to overlap to/from GPU memory transfers. I'm currently able to achieve the overlap effect by running copyToGpu / ProcessingOnGpu / CopyBack in parallel, but it requires a lot more complicated code and introduces latency.

My understanding is that CUDA has unified memory concept that makes running such kernels possible.

**Comment by SomeUserName6474** [comment]
Read wiki. First, allocate memory on gpu, copy integers from host, that launch kernel, syncronize accelerator (wait for all kernels done work) than get results.

Read QuickStart guide.
https://github.com/m4rs-mt/ILGPU/wiki

**Comment by SomeUserName6474** [comment]
Oh, my bad.
As i know, dma (direct memory access) used to transfer data between ram/gpu memory.
In other case its too expensive (in terms of delay/free host memory bandwidth)

**Comment by SomeUserName6474** [comment]
Three concepts are Zero-copy memory (gpu reads directly from dram), pinned memory(load/store), and unified memory - drivers do all memory managements for you.

**Comment by MoFtZ** [comment]
hi @yuryGotham, let me just start by saying that I would not recommend what you are trying to do.

If latency is an issue, perhaps we can investigate ways to reduce that latency - e.g. by reducing the number times that you have to copy from/to the GPU, or by queuing several operations on the same stream.

**The below information is "buyer-beware".**

The CUDA kernel is able to access host memory. This memory is required to be "page locked" into physical RAM, so that it does not move, and so that DMA calls can find it.

This host memory is unmanaged memory, and can be allocated using the CUDA native API. In ILGPU, this can be done using the low-level `CudaAPI` class (see [example](https://github.com/m4rs-mt/ILGPU/blob/master/Samples/MonitorProgress/CudaProgress.cs)). It would be necessary to wrap this into a `MemoryBuffer` class in order to use it.

Alternatively, it should be possible to "pin" managed memory, and then page-lock that memory into physical RAM so that the CUDA kernel can access it. ILGPU has limited support for applying a page-lock to pinned memory (see [example](https://github.com/m4rs-mt/ILGPU/blob/master/Samples/PinnedMemoryCopy/Program.cs#L38)). This could be combined with a custom memory buffer class in order to perform similarly to the previous example with the `CudaAPI`.

**Comment by MoFtZ** [comment]
@yuryGotham, the usual warning of buyer-beware 😅 

The following example code makes use of the `CudaAPI` to allocate host memory on the CPU. Note that this is unmanaged memory, so the code uses `Span<T>` to expose the memory to .NET. In addition, note that `Span<T>` is limited to `int.MaxValue` elements, but that the Cuda API has no such limit.

The other option is to pin a .NET array, page-lock it, and then use that pointer rather than the pointer from the Cuda API. ILGPU current has a `CreatePageLockFromPinned` method on the accelerator for this purpose.

```CSharp
// ---------------------------------------------------------------------------------------
//                                    ILGPU Samples
//                           Copyright (c) 2022 ILGPU Project
//                                    www.ilgpu.net
//
// File: Program.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------

using ILGPU;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;
using System;
using System.Linq;

namespace SimpleKernel
{

    class Program
    {
        static void MyKernel(
            Index1D index,
            ArrayView1D<int, Stride1D.Dense> srcView,
            ArrayView1D<int, Stride1D.Dense> dstView)
        {
            dstView[index] = srcView[index] + 1;
        }

        /// <summary>
        /// Launches a kernel using Cuda host memory.
        /// </summary>
        static void Main()
        {
            using var context = Context.CreateDefault();
            using var accelerator = context.CreateCudaAccelerator(0);

            var kernel = accelerator.LoadAutoGroupedStreamKernel<
                Index1D, ArrayView1D<int, Stride1D.Dense>, ArrayView1D<int, Stride1D.Dense>>(MyKernel);

            // Create a host memory buffers, and populate it with some values.
            using var srcBuffer = accelerator.AllocateHostMemory<int>(1024);
            using var dstBuffer = accelerator.AllocateHostMemory<int>(srcBuffer.Length);

            var srcSpan = srcBuffer.GetSpan(0, (int)srcBuffer.Length);

            Enumerable.Range(42, srcSpan.Length).ToArray().CopyTo(srcSpan);

            // Launch the kernel, and make sure to explicitly synchronize so that the
            // we know the kernel has finished, before trying to read from the host memory.
            kernel((int)srcBuffer.Length, srcBuffer.View, dstBuffer.View);

            accelerator.Synchronize();

            // Read values from the destination host memory.
            var dstSpan = dstBuffer.GetSpan(0, (int)dstBuffer.Length);
            for (int i = 0, e = dstSpan.Length; i < e; ++i)
                Console.WriteLine($"Element {i}: {dstSpan[i]}");
        }
    }

    class CudaHostMemory<T> : AcceleratorObject
        where T : unmanaged
    {
        #region Nested Types

        /// <summary>
        /// Constructs a Cuda buffer using host memory.
        /// </summary>
        class CudaHostMemoryBuffer : MemoryBuffer
        {
            public CudaHostMemoryBuffer(
                CudaAccelerator accelerator,
                long length,
                int elementSize)
                : base(accelerator, length, elementSize)
            {
                CudaException.ThrowIfFailed(
                   CudaAPI.CurrentAPI.AllocateHostMemory(
                       out IntPtr resultPtr,
                       new IntPtr(LengthInBytes)));
                NativePtr = resultPtr;
            }

            protected override void DisposeAcceleratorObject(bool disposing)
            {
                CudaException.ThrowIfFailed(
                    CudaAPI.CurrentAPI.FreeHostMemory(NativePtr));
                NativePtr = IntPtr.Zero;
            }

            protected override void CopyFrom(
                AcceleratorStream stream,
                in ArrayView<byte> sourceView,
                in ArrayView<byte> targetView) =>
                throw new NotImplementedException(); 

            protected override void CopyTo(
                AcceleratorStream stream,
                in ArrayView<byte> sourceView,
                in ArrayView<byte> targetView) =>
                throw new NotImplementedException();

            protected override void MemSet(
                AcceleratorStream stream,
                byte value,
                in ArrayView<byte> targetView) =>
                throw new NotImplementedException();
        }

        #endregion

        #region Properties

        /// <summary>
        /// Returns an array view that can be used to update the host memory from the GPU.
        /// </summary>
        public readonly ArrayView<T> View;

        /// <summary>
        /// Holds the Cuda memory buffer that contains the host memory.
        /// </summary>
        private readonly CudaHostMemoryBuffer memoryBuffer;

        /// <summary>
        /// Returns the length of the host memory buffer.
        /// </summary>
        public long Length => memoryBuffer.Length;

        /// <summary>
        /// Gets a Span to access the host memory.
        /// </summary>
        [NotInsideKernel]
        public unsafe Span<T> GetSpan(long offset, int length)
        {
            var ptr = (T*)memoryBuffer.NativePtr.ToPointer();
            ptr += offset;
            return new Span<T>(ptr, length);
        }

        #endregion

        #region Instance

        public CudaHostMemory(CudaAccelerator accelerator, long length)
            : base(accelerator)
        {
            memoryBuffer = new CudaHostMemoryBuffer(accelerator, length, Interop.SizeOf<T>());
            View = new ArrayView<T>(memoryBuffer, 0, memoryBuffer.Length);
        }

        protected override void DisposeAcceleratorObject(bool disposing) =>
            memoryBuffer.Dispose();

        #endregion
    }

    static class CudaHostMemoryExtensions
    {
        public static CudaHostMemory<T> AllocateHostMemory<T>(this CudaAccelerator accelerator, long length)
            where T : unmanaged =>
            new CudaHostMemory<T>(accelerator, length);
    }
}
```

**Comment by yuryGotham** [comment]
Thank you @MoFtZ. Your approach works and solves my latency and code complexity issues.

One the other hand I was only able to get up to ~5GB/s (bi-directional) host memory access speed... I'll read on how kernels should be accessing host memory to maximize the bandwidth and try to push it up to the theoretical 25GB/s...

**Comment by MoFtZ** [comment]
hi @yuryGotham, I'm going to close this ticket. Glad we could help.
