### ISSUE TITLE
IRBuilder cannot resolve missing Rcp hardware intrinsic

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#83]
I'm trying to get the unit tests for `Rcp` and `BinaryLog` working on OpenCL.

On OpenCL, `Rcp` is not a hardware intrinsic. As a workaround, I created a new `CLMath` class, based on code from `PTXMath`. i.e. I have registered a redirect for `UnaryArithmeticKind.RcpF` to `CLMath.Rcp`.

Assuming debugging the `RcpDouble` unit test, the program flow is roughly:
1. Disassemble `RcpDoubleKernel`, which calls `XMath.Rcp`.
1. When generating code for the kernel, the call to `XMath.Rcp` is replaced with a math intrinsic call to `UnaryArithmeticKind.RcpF`.
1. The kernel is further transformed, and the call to `UnaryArithmeticKind.RcpF` is replaced with the new `CLMath.Rcp` function.
1. The `CLMath.Rcp` function is disassembled, and when generating its code of `1.0 / value`, [line 141 of `Src\ILGPU\IR\Construction\Arithmetic.cs`](https://github.com/m4rs-mt/ILGPU/blob/e347ca342ffff20ab0bd5d98a0d8f4f3c94c9d3c/Src/ILGPU/IR/Construction/Arithmetic.cs#L141) converts `1.0 / value` into `UnaryArithmeticKind.RcpF`.

As a result of this last step, there is no way for OpenCL to resolve `UnaryArithmeticKind.RcpF`.

Do you have any thoughts for how to resolve this?

**Comment by MoFtZ** [comment]
My changes for `CLMath` are in this pull request:
https://github.com/m4rs-mt/ILGPU.Algorithms/pull/14

**Comment by m4rs-mt** [comment]
The overall problem is that the generic lowering pipeline is not designed to "re-introduce" code that has already been transformed before. In this case, I suggest that we use a backend code-generation callback (like the one in [PTXMath.cs](https://github.com/m4rs-mt/ILGPU.Algorithms/blob/master/Src/ILGPU.Algorithms/PTX/PTXMath.cs) `GenerateMathIntrinsic`) to explicitly generate the desired OpenCL implementation for `UnaryArithmeticKind.RcpF`. What do you think?

**Comment by MoFtZ** [comment]
Makes sense - PR updated.

**Comment by m4rs-mt** [comment]
Seems to be resolved for the moment. I'm closing this issue for now.
