### ISSUE TITLE
Sample request: How to use IScanReduceOperation for customized Reduce/WarpExtenstions.Reduce

### ISSUE THREAD

**Issue by artheru** [m4rs-mt/ILGPU#831]
This could be very useful. For example, if one want to perform an argmax operation and constructed a gpu array of struct PV{int pos;float val;}, how to use the internal Reduce function to get the max value and pos?

**Comment by MoFtZ** [comment]
hi @artheru.

To confirm my understanding, you have an array of items, where each item is of type `struct PV {int pos; float val;}`. And you want to use the GPU to find the "maximum" item?

Or, do you have an array of items, where each item is of type `float`. And you want to use the GPU to fix the index of the "maximum" value?

**Comment by artheru** [comment]
I think they're basically the same, but I prefer the former one: each item is of type `struct PV {int pos; float val;}`

**Comment by m4rs-mt** [comment]
Hi @artheru,

the following piece of code can be used to represent your tuple type (consisting of a `float` and an `int`) within out highly generic `Reduce` and `Scan` implementation pipeline:

```c#
    private readonly struct Entry :
        IScanReduceOperation<Entry>,
        IAtomicOperation<Entry>,
        ICompareExchangeOperation<Entry>
    {
        public Entry(float val, int pos)
        {
            Val = val;
            Pos = pos;
        }

        public string CLCommand => string.Empty;
        public Entry Identity => new Entry(float.MaxValue, int.MaxValue);

        public float Val { get; }
        public int Pos { get; }

        public Entry Apply(Entry first, Entry second) =>
            // TODO: you want to modify this to pay attention to epsilon deltas
            Utilities.Select(first.Val > second.Val, first, second);

        public Entry Operation(Entry current, Entry value) =>
            Apply(current, value);

        public void AtomicApply(ref Entry target, Entry value) =>
            Atomic.MakeAtomic(ref target, value, this, this);

        public Entry CompareExchange(
            ref Entry target,
            Entry compare,
            Entry value)
        {
            ref long targetL = ref Unsafe.As<Entry, long>(ref target);
            long compareL = Unsafe.As<Entry, long>(ref compare);
            long valueL = Unsafe.As<Entry, long>(ref value);
            long result = Atomic.CompareExchange(ref targetL, compareL, valueL);
            return Unsafe.As<long, Entry>(ref result);
        }

        public bool IsSame(Entry left, Entry right) =>
            // TODO: you want to modify this to pay attention to epsilon deltas
            left.Val == right.Val & left.Pos == right.Pos;

        public override string ToString() => $"({Val}, {Pos})";
    }
```

Please note that this operation cannot be used in combination with the OpenCL backend at the moment, since the `CLCommand` string to perform basic scan/reduce operations is currently empty.

**Comment by m4rs-mt** [comment]
I will close this issue for now. If the problem persists or there are further questions, we can always reopen this ticket.
