### ISSUE TITLE
System.TypeLoadException 

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#84]
i create a new consoleapp and copy  SimpleStructures  demo to my app ,use 8.0 beta2. but throw   System.TypeLoadException:“  “ILGPU.ArrayView`1[SimpleStructures.Program+CustomDataType]”。”
on line     var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<CustomDataType>>(MyKernel);
                    
Did I miss something?

**Comment by MoFtZ** [comment]
@xxl-cc, I think you are missing this line from [AssemblyAttributes.cs](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/SimpleStructures/AssemblyAttributes.cs#L4)

```
// Mark all internals to be visible to the ILGPU runtime
[assembly: InternalsVisibleTo(ILGPU.Context.RuntimeAssemblyName)]
```

**Comment by xxl-cc** [comment]
thank you ,it can work on my app,but cannot work in mstest

**Comment by MoFtZ** [comment]
what is the error that you get on mstest?

**Comment by xxl-cc** [comment]
ILGPU.Runtime.Cuda.CudaException:“a PTX JIT compilation

**Comment by MoFtZ** [comment]
Are you able to provide some sample code please?

**Comment by MoFtZ** [comment]
Also, what version of the CUDA drivers are you using?

**Comment by xxl-cc** [comment]
i intsalled cuda sdk10.1

**Comment by xxl-cc** [comment]
i moved the sample code to my test  SimpleStructures、SimpleKernel etc ,and throw that error

**Comment by MoFtZ** [comment]
I have attached sample code that uses SimpleStructures in an MSTest project.
I'm compiling using VS2019 v16.5.4.

[MSTest84.zip](https://github.com/m4rs-mt/ILGPU/files/4537692/MSTest84.zip)

Does this work for you?

**Comment by xxl-cc** [comment]
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”  when run to using (var context = new Context())

**Comment by m4rs-mt** [comment]
@xxl-cc Have you verified that you are using the correct "Processor Architecture" for alle test cases? If you are executing the tests in X86 mode on an X64 machine, the runtime can fail. Furthermore, you don't need to install the Cuda SDK :)

**Comment by MoFtZ** [comment]
When I change my 'Processor Architecture' to X86 on my X64 machine, I get the same error as @xxl-cc

**Comment by xxl-cc** [comment]
thanks,defult  anycpu throw that error ,i changed to x64,is ok.

**Comment by m4rs-mt** [comment]
We should add an additional check to the `Context` constructor that everything runs on the native machine platform using `Backend.EnsureRunningOnNativePlatform()`. I am going to add this.

**Comment by m4rs-mt** [comment]
I've fixed the TypeLoadException but did not add the runtime check, since the CPU accelerator (as well as most of the `Context` functionality) is available on all platforms.
