### ISSUE TITLE
Questions about cross-platform support for GPUs

### ISSUE THREAD

**Issue by LouChiSoft** [m4rs-mt/ILGPU#844]
Hi, I stumbled across this project from a Reddit thread asking about GPU accelleration in C# and I have to say it caught my interest. When I saw it lists cross-platform as a feature I had to ask; Just how cross-platform is ILGPU? 

I ask since I do a lot of GPU accellerated image processing at my job and it's entirely done in OpenCL and C++. One of the hassles we have is having to compile and store a cache of kernels for each GPU we support since we don't share source code and we can't use SPIR-V due to it not being supported for OpenCL on Nvidia GPUs (at least the last time we check). Is this something we would still have to do with ILGPU or is it possible to compile a single binary with kernels and it run on any supported machine?

If it does have that level of cross-platform support are there any examples of performance numbers between ILGPU and raw OpenCL/C++? If numbers are similar or better this could be a very enticing platform

**Comment by MoFtZ** [comment]
hi @LouChiSoft. Yes, ILGPU is cross-platform. It works by reading the C# code (MSIL) at runtime, using reflection, and transforming that to PTX assembly instructions (for Cuda) or C code (for OpenCL). The transformed code is then compiled at runtime using the respective Cuda or OpenCL compiler, into a GPU kernel.

Regarding performance, it is always best to profile on the target devices.

**Comment by LouChiSoft** [comment]
Okay, that's good to know. That makes ILGPU potentially viable as a true crossplatform solution to I current framework. Thanks.
