### ISSUE TITLE
Illegal memory access with double[,] ab=new double[2,2]

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#86]
I have a kernel using multiple array, "illegal memory access.." is thrown when running after updating to 0.8-beta2.  It worked before with version released on March 10.   Doesn't the latest version support multiple array in kernel? or because of some other problem? I have attached the test project to see if anyone can replicate the problem. Thanks!

   internal static void TestKernel(ArrayView<double> array1
                                       )
        {
            double[,] ab = new double[2, 2];
            for (int ielem = Grid.GlobalIndex.X; ielem < array1.Length; ielem +=
[WindowsFormsApp1.zip](https://github.com/m4rs-mt/ILGPU/files/4555645/WindowsFormsApp1.zip)
GridExtensions.GridStrideLoopStride)
            {
                ab[0, 1] = array1[ielem];
                ab[0, 0] = array1[ielem];
            }
        }

**Comment by MoFtZ** [comment]
@toolwtech, I can reproduce your issue. My guess is that ILGPU does not currently support multi-dimensional arrays.

When I changed the kernel to one-dimension, it works for me.
```
internal static void TestKernel(ArrayView<double> array1)
{
    double[] ab = new double[4];
    for (int ielem = Grid.GlobalIndex.X; ielem < array1.Length; ielem += GridExtensions.GridStrideLoopStride)
    {
        ab[0] = array1[ielem];
        ab[1] = array1[ielem];
    }
}
```

**Comment by m4rs-mt** [comment]
@toolwtech The new compiler release uses a completely different code-generation path leveraging different code optimization transformations. Support for array values has always been considered to be in an "alpha" state so far. However, the new version ensures valid code generation for single-dimensional arrays. We are going to extend these officially supported array features in the near future 🔢

**Comment by toolwtech** [comment]
Got you, thanks!
