### ISSUE TITLE
Question: What is the benefit of using ILGPU.Util.Double2,3,4?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#87]
Can it realize Instruction-Level Parallelism?  Is there primitives available with ILGPU to realize instruction level parallelism?

**Comment by m4rs-mt** [comment]
@toolwtech Thanks for posting this question.

The intended use case of these structures is the explicit performance tweaking using manual loop unrolling, which was requested by the community.

What exactly do you mean by talking about ways to realize ISP?

**Comment by toolwtech** [comment]
Please take look at 35.1.1 in the link regarding ISP
https://developer.nvidia.com/gpugems/gpugems2/part-iv-general-purpose-computation-gpus-primer/chapter-35-gpu-program-optimization

I expected ILGPU had some primitives such as int2(4), double2(4) to be used for ISP. also I like to see those primitives can be used as array, e.g. in OpenCL, 
int4 test;
for(int i = 0; i<4; i++)
{
   int j = test[i];
} 

One of reasons is,  I like to create a struct in which I can have member that is one/two dimensional array
e.g.
public struct Test
{
    public int[] Indexes
}

But currently it doesn't seem that ILGPU supports array in struct.   I have to create Array using struct such as Int2 below.  I am not sure if "switch..case" can be optimized in ILGPU when transformed to Cuda or OpenCL. 
  public struct Int2
    {
        int X;
        int Y;

        public Int2(int x, int y)
        {
            X = x; Y = y;
        }
     
        public int this[int i]
        {
            get
            {
                switch (i)
                {
                    case 0:
                        return X;
                    case 1:
                        return Y;
             
                }
                return 0;
            }

            set
            {
                switch (i)
                {
                    case 0:
                        X = value;
                        break;
                    case 1:
                        Y = value;
                        break;
             
                }
            }
        }
    }

**Comment by toolwtech** [comment]
@m4rs-mt, can struct of "Int2" using switch..case.. be optimized or replaced by existing ILGPU primitives?

**Comment by m4rs-mt** [comment]
@toolwtech I've got your point. Please note that a structure containing a managed array in C# will not be translated to an "inlined array of values". In other words:
```c#
struct Foo
{
    int[] data;
}
```
can be seen as a structure containing a pointer to a managed array (please note that this is pseudo C# code):
```c#
struct Foo
{
    ManagedHandleToIntArray* data;
}
```
What you want to do seems to be a [nested fixed array](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/fixed-size-buffers) of a basic type:
```c#
struct Foo
{
    fixed int data[128];
}
```
This will be supported in one of the next releases 🤓 
Optimization of `switch` and `if` statements will be available in v0.8.1.

**Comment by toolwtech** [comment]
@m4rs-mt Thanks for your hints!  look forward to seeing ILGPU supports fixed array and optimizes switch and if statement.

**Comment by m4rs-mt** [comment]
I have created separate issues to track the different feature requests of this umbrella issue (see #160 and #161). Therefore I will close this issue for the time being.
