### ISSUE TITLE
A Basic Question on Allocating Complex Objects

### ISSUE THREAD

**Issue by noumanqaiser** [m4rs-mt/ILGPU#882]
Dear Team, 

I am a beginner when it comes to utilizing GPU in .NET and have a basic question.

I see in most tutorials that you Allocate an array of Integers/Doubles on GPU Memory, I wanted to understand if you could allocate a List/Array of arbitrary objects onto GPU. Take the followig code as an example:

```c#
public void Main()
{
            List<DummyCalculationClass> dummyCalculationClasses = new List<DummyCalculationClass>();
            Random random = new Random();
            for (int i = 0; i < 1000; i++)
            {
                      dummyCalculationClasses.Add(new DummyCalculationClass() {NumberA = random.NextDouble(),NumberB = 
                           random.NextDouble() });
            }

            //Is there any way to allocate the List dummyCalculationClasses onto GPU and then calculate the numberResult = NumberA 
            //*NumberB.   
}

 public static class DummyCalculationClass
{
    public int NodeId { get; set; } 
    public double NumberA { get; set; } 
    public double NumberB { get; set; } 

    public double numberResult { get; set; } 
}
```

In the example above, I create an arbitrary complex object, Can an Array/List of arbitrary objects be loaded onto GPU. Would this be ever be more efficient than using CPU for such a task?

**Comment by MoFtZ** [comment]
welcome @noumanqaiser.

Yes, ILGPU supports arbitrary complex objects. However, you will need to use `struct` (value type) rather than `class` (reference type).

Have a look at the [SimpleStructures](https://github.com/m4rs-mt/ILGPU/blob/master/Samples/SimpleStructures/Program.cs) sample code.

**Comment by MoFtZ** [comment]
Regarding efficiency, it really depends on the algorithm and side of the data. There is an overhead with transferring data to/from the GPU, so it is not always "better" to blindly use the GPU. You should profile and measure the performance.

**Comment by m4rs-mt** [comment]
I close this issue for now. If you have further questions, feel free to contact us via `Discord` or open another issue on `GitHub`.
