### ISSUE TITLE
Question on how to achieve strided memory copy

### ISSUE THREAD

**Issue by TriceHelix** [m4rs-mt/ILGPU#883]
Dear ILGPU devs,

I am wondering how I could copy every second element of a dense buffer located on the GPU into an array on the CPU (or vice versa). Of course I could copy everything into another array first first and then do a strided memory copy on the CPU to achieve this selection, though that seems like a bit of a waste especially for large amounts of data or bigger strides like 3, 4, and so on.
Is there a feature that enables strided memory copy between devices directly without the use of an intermediate buffer?

Thank you for your time.

**Comment by MoFtZ** [comment]
ILGPU does not currently support strided copying of data to/from the GPU. This is not a particularly efficient operation.

This [stackoverflow post](https://stackoverflow.com/questions/14985667/efficient-way-to-copy-strided-data-to-and-from-a-cuda-device#17112259) I found suggests that it might be possible using the `cudaMemcpy2D` function from the Cuda Runtime API.

ILGPU does not use the Cuda Runtime API, instead using the lower level Cuda Driver API. The equivalent functionality is [cuMemcpy2DAsync](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g4acf155faeb969d9d21f5433d3d0f274).

OpenCL appears to have `clEnqueueReadBufferRect` and `clEnqueueWriteBufferRect`, which may be able to do something similar.

It might be possible for you to call these APIs directly. They are not currently used or exposed by the internals of ILGPU.

**Comment by TriceHelix** [comment]
I will look into those APIs, though as you've stated it might be a bit too ineffecient to be worth it. For now I will copy everything into a seperate array and do strided copying afterwards.
Thank you.
