### ISSUE TITLE
Deprecated warning when using Allocate1D?

### ISSUE THREAD

**Issue by leonbohmann** [m4rs-mt/ILGPU#895]
Hello! First of all, thanks for the great work on this! I've been implementing an OpenCL library using java, what a mess..
This is very user friendly and the fact that I can use all of my IDEs functionality to create kernels is just awesome!

I have a question regarding the method `Allocate1D`, which I am using as follows:

```csharp
mb_deviceLhs = CalcAccelerator.Allocate1D(MatVector.Matrix);
mb_deviceRhs = CalcAccelerator.Allocate1D(MatVector.Vector);
mb_deviceOut = CalcAccelerator.Allocate1D<double>(Length);
```

`CalcAccelerator` is a CudaAccelerator created elsewhere in the code. My concern is, that the method documentation of Allocate1D shows: "This method is not supported on accelerators!":
![grafik](https://user-images.githubusercontent.com/13386367/205498606-6e3284cd-499f-45d4-8cab-fd4f7f95894f.png)

Is this warning deprecated? What am I supposed to use then? I tried it nevertheless and it works just fine.

And, another thing, as far as I understood, this method allocates shared memory on the GPU, right?

**Comment by MoFtZ** [comment]
Do you mean the [References](https://github.com/m4rs-mt/ILGPU#references) for ILGPU?

**Comment by leonbohmann** [comment]
Yes. I wanted to read about how this works. Really interesting, because I tried to use CUDA directly but then just went straight to using ILGPU, much simpler!

Thanks!

**Comment by MoFtZ** [comment]
@leonbohmann feel free to join our Discord server. It will be easier to discuss topics there.

https://discord.com/invite/X6RBCff
