### ISSUE TITLE
Wrong values on GPUs

### ISSUE THREAD

**Issue by RadekHrabuska** [m4rs-mt/ILGPU#919]
Hi, I am new to computing on GPUs and Cuda. I am trying to make a basic neural network kernel just to experiment with CUDA. However, I have an issue where I am unable to get correct value from code.

Whatever I do I get an result about 6.9522261370503E-310 on an allocated 2D array, sometimes there is a exception thrown.
Here is the class I have tried to create:

` using ILGPU;
using ILGPU.Algorithms;
using ILGPU.Runtime;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Piskvorky.Ai
{
    public class GpuNN 
    {
        protected int[] layers;//layers    
        protected MemoryBuffer1D<double, Stride1D.General>[] biases;//biasses    
        protected List<MemoryBuffer1D<double, Stride1D.General>[]> weights;

        protected Accelerator Accelerator;
       
        protected static Accelerator GetAccelerator(int device)
        {
            var context = Context.CreateDefault();
            return context.Devices[device].CreateAccelerator(context);
        }

        public GpuNN(int[] layers, double[] allItems) : base(1)
        {
            Accelerator = GetAccelerator(device);
            this.layers = layers;
            var initBiases = allItems.Take(GetBiasLength(layers)).ToArray();
            InitBiases(initBiases);
            var connectionWeigths = allItems.Skip(GetBiasLength(layers)).ToArray();
            InitWeights(connectionWeigths);
        }

        public async Task<double[]> Calculate(double[] input)
        {
            var inputBuffer = Accelerator.Allocate1D<double, Stride1D.General>(input.Count(), new Stride1D.General());
            inputBuffer.View.CopyFromCPU(input);
            Accelerator.Synchronize();
            var layerCnt = layers.Count();
            for (int i = 0; i < layerCnt-1; i++)
            {
                MemoryBuffer1D<double, Stride1D.General> nextLayer = Layer(inputBuffer, weights[i], biases[i], layers[i+1]);
                Accelerator.Synchronize();
                inputBuffer.Dispose();
                inputBuffer = nextLayer;
            }

            var res = inputBuffer.GetAsArray1D();
            return res;
        }

        private MemoryBuffer1D<double, Stride1D.General> Layer(
            MemoryBuffer1D<double, Stride1D.General> input,
            MemoryBuffer1D<double, Stride1D.General>[] weigths, 
            MemoryBuffer1D<double, Stride1D.General> biases,
            int neuronCnt)
        {
            var output = Accelerator.Allocate1D<double, Stride1D.General>(neuronCnt, new Stride1D.General());
            NNKernel(new Index1D(), input.View, weigths, biases.View, output.View);
            return output;
        }

        private static ArrayView1D<double, Stride1D.General> NNKernel(
        Index1D index, // The global thread index (1D in this case)
        ArrayView1D<double, Stride1D.General> inputs, // A view to a chunk of memory (1D in this case)
        MemoryBuffer1D<double, Stride1D.General>[] weights,
        ArrayView1D<double, Stride1D.General> biases,
        ArrayView1D<double, Stride1D.General> output // A view to a chunk of memory (1D in this case)
            )  // A view to a chunk of memory (1D in this case)
        {

            for (LongIndex1D i = 0, e = inputs.Extent; i < e; ++i)
            {
                output[index] += (inputs[i] * weights[new Index1D((int)i.X)].View[new Index1D((int)index.X)]);
            }

            output[index] = XMath.Tanh((output[index] + biases[index]) / 2);
            return output;
        }

        //initializes and populates array for the biases being held within the network.
        protected void InitBiases(double[] initBiases)
        {
            var arrIndex = 0;
            List<MemoryBuffer1D<double, Stride1D.General>> biasList = new List<MemoryBuffer1D<double, Stride1D.General>>();
            for (int i = 0; i < layers.Length -1; i++)
            {
                double[] bias = new double[layers[i]];
                for (int j = 0; j < layers[i]; j++)
                {
                    bias[j] = (double)(initBiases[arrIndex]);
                }
                var biasMem = Accelerator.Allocate1D<double, Stride1D.General>(bias.Count(), new Stride1D.General());
                biasMem.CopyFromCPU(bias);
                biasList.Add(biasMem);
            }
            biases = biasList.ToArray();
        }

        //initializes random array for the weights being held in the network.
        protected void InitWeights(double[] chromosome)
        {
            var arrIndex = 0;
            List<MemoryBuffer1D<double, Stride1D.General>[]> weightsList = new List<MemoryBuffer1D<double, Stride1D.General>[]>();
            for (int i = 1; i < layers.Length; i++)
            {
                double[] layerWeightsList = new double[layers[i]];
                int neuronsInPreviousLayer = layers[i - 1];
                MemoryBuffer1D<double, Stride1D.General>[] nnW = new MemoryBuffer1D<double, Stride1D.General>[layers[i]];
                for (int j = 0; j < layers[i]; j++)
                {
                    for (int k = 0; k < neuronsInPreviousLayer; k++)
                    {
                        layerWeightsList[k] = chromosome[arrIndex];
                        arrIndex++;
                    }
                    nnW[j] = Accelerator.Allocate1D<double, Stride1D.General>(neuronsInPreviousLayer, new Stride1D.General());
                    nnW[j].CopyFromCPU(layerWeightsList);
                }
                weightsList.Add(nnW);
            }
            weights = weightsList;
        }

        public static int GetBiasLength(int[] layers)
        {
            var biasLength = 0;
            for (int i = 0; i < layers.Length-1; i++)
            {
                biasLength += (layers[i]);
            }

            return biasLength;
        }

        public static int GetConnectionsLength(int[] layers)
        {
            var connectionsLength = 0;
            for (int i = 1; i < layers.Length; i++)
            {
                connectionsLength += (layers[i - 1] * layers[i]);
            }

            return connectionsLength;
        }
    }
}
`

From this the line `output[index] += (inputs[i] * weights[new Index1D((int)i.X)].View[new Index1D((int)index.X)]);` always fail to deliver a expected value (1) in my testing scenarion. I have tried multiple approches with the same result. The variable weights (in whichever form, even simple weights[index,i]) always causes issues.

**Comment by MoFtZ** [comment]
hi @RadekHrabuska. It looks like you are not running the calculations on the GPU.

You have a method `NNKernel` that is the code you want to run on the GPU. However, you are calling that method directly, as if it were normal CPU code.

You need to use the `Accelerator`, and call methods like `LoadAutoGroupedStreamKernel` to transform the `NNKernel` method into a GPU kernel. Then, run the GPU kernel, passing in the parameters.

Have a look at the `SimpleKernel` sample code:
https://github.com/m4rs-mt/ILGPU/blob/master/Samples/SimpleKernel/Program.cs#L65

We also have some tutorials to help you get started:
https://github.com/m4rs-mt/ILGPU/tree/master/Docs

Hope that helps.

**Comment by MoFtZ** [comment]
@RadekHrabuska I am closing this issue for the now. If the problem persists, please let us know.
