### ISSUE TITLE
Unit tests fail when using .NET 7.0.3

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#932]
On Feb 14th 2023, Microsoft released the .NET 7.0.3 ([SDK 7.0.200](https://github.com/dotnet/core/issues/8191)). This is causing unit tests in our CI pipeline to fail.

After installing SDK 7.0.200, I can reproduce the failures on Windows 10 using the command line `dotnet test`. However, I am unable to reproduce the test failures in VS2022 (v17.4.5).

**Comment by lostmsu** [comment]
You could hold SDK at 7.0.2 until VS v17.5 is released.

**Comment by MoFtZ** [comment]
Looks like the SDK changed the IL emitted for C# extension methods that use generics. The newly added boxing instructions then caused issues when ILGPU parsed the MSIL.

I have raised #933 to fix this issue by removing the boxing.
