### ISSUE TITLE
ILGPU throw error if variable in generic struct use Atomic operation

### ISSUE THREAD

**Issue by GeoBIM2020** [m4rs-mt/ILGPU#977]
Please take a look at attatched sample code.
[EmptyAlgorithms.zip](https://github.com/m4rs-mt/ILGPU/files/11009007/EmptyAlgorithms.zip)

**Comment by MoFtZ** [comment]
`Atomic.Add` only supports working on global memory.

The kernel code is loading from `TestArray[index]` into a local variable, and then performing the atomic call on stack memory.

Try changing the assignment from `T test = TestArray[index];` to `ref T test = TestArray[index];`
