### ISSUE TITLE
What is the difference between Stride2D.Infinite, Stride2D.DenseX, and Stride2D.General

### ISSUE THREAD

**Issue by jessiepathfinder** [m4rs-mt/ILGPU#980]

**Comment by MoFtZ** [comment]
hi @jessiepathfinder, as discussed on Discord,
> the strides control how the 2d indexing is calculated, infinite and general are for special use cases
the same thing exists for 1d, and 3d

 > We also recently created a sample project for this:
https://github.com/m4rs-mt/ILGPU/blob/master/Samples/MemoryBufferStrides/Program.cs
