### ISSUE TITLE
Is there a similar function to thrust::fill(stream, arrayStart, arrayEnd, -1) 

### ISSUE THREAD

**Issue by Liudeke** [m4rs-mt/ILGPU#987]
Is there a similar function to thrust::fill(stream, arrayStart, arrayEnd, -1)  Thanks very much

**Comment by MoFtZ** [comment]
hi @Liudeke. This can be achieved using the `Initialize` functionality.

Please have a look at the `AlgorithmsInitialize` sample project:
https://github.com/m4rs-mt/ILGPU/blob/master/Samples/AlgorithmsInitialize/Program.cs

**Comment by MoFtZ** [comment]
hi @Liudeke. I'm closing this ticket for now. If there are is anything else to add, please let us know.
